### ISSUE TITLE
How to disable javascript in splash json http api ?

### ISSUE THREAD

**Issue by chinmayjatana** [scrapinghub/splash#1000]

**Comment by Gallaecio** [comment]
Why would you disable JavaScript? Do you want to take a screenshot without JavaScript? Otherwise using Splash seems pointless to me.

**Comment by chinmayjatana** [comment]
yes i want to take screenshot .

**Comment by lopuhin** [comment]
Rendering a page without JS can be useful to improve speed, to check how page looks without JS, or to avoid popups which are triggered by JS.

But I think it's not exposed in the HTTP API - you'd need to write a lua script, see https://splash.readthedocs.io/en/stable/scripting-ref.html#splash-js-enabled

**Comment by chinmayjatana** [comment]
Thanks :)
