### ISSUE TITLE
Javascript rendering problem

### ISSUE THREAD

**Issue by chinmayjatana** [scrapinghub/splash#1002]
Can anyone please suggest how to improve java script rendering in splash . Like in the link mentioned below the left bottom element not rendered and as a result i can't scrap its value .

link : https://www.tokopedia.com/japaniqos/iqos-3-pen-holden-stick-black-original?src=topads

**Comment by binishjoshi** [comment]
How did you fix it? I'm having problems with Splash, too. JS doesn't render at all.

**Comment by MADDY312** [comment]
How did you fix it? I'm having problems with Splash, too. JS doesn't render at all.
