### ISSUE TITLE
Running multiples instances on multiple ports

### ISSUE THREAD

**Issue by mwbelt** [scrapinghub/splash#1012]
I'm trying to run multiple instances on multiple ports, with no success.

docker run -p 8050:8050 scrapinghub/splash
docker run -p 8055:8055 scrapinghub/splash

Both of these start successfully, but both claim to be listening on port 8050, no matter what I pass with the -p option.

What am I doing wrong?

**Comment by Gallaecio** [comment]
Internally, the port is always 8050 (not sure if it can be configured otherwise).

So the second Docker command must map 8050 to 8055, not 8055 to 8055. I don’t remember if the right syntax is `-p 8055:8050` or `-p 8050:8055`, but one of those should work.

**Comment by mwbelt** [comment]
@Gallaecio Thank you so much.  I just found that and came back to close my ticket.  

Thanks for answering such a noob question.

**Comment by deeprony7** [comment]
> -p 8055:8050

For clarity, port mapping is in the format - `host:container`
`docker run -p 8055:8050 scrapinghub/splash`
