### ISSUE TITLE
/bin/sh: 1: /tmp/provision.sh: Permission denied

### ISSUE THREAD

**Issue by tiziano777** [scrapinghub/splash#1019]
when a try to build  locally splash 3.2 using docker build command the installation stopped here:

/bin/sh: 1: /tmp/provision.sh: Permission denied
The command '/bin/sh -c /tmp/provision.sh     prepare_install     install_deps     install_qtwebkit_deps     install_official_qt     install_qtwebkit     install_pyqt5     install_python_deps     install_flash     install_msfonts     install_extra_fonts     remove_builddeps     remove_extra &&     rm /tmp/provision.sh' returned a non-zero code: 126

**Comment by Gallaecio** [comment]
What steps are you using to build it?

**Comment by tiziano777** [comment]
I first downloaded scrapy-splash locally, after i used: 
docker build --tag mysplash -f [PATH]/Dockerfile
docker build --tag mysplash  [PATH]/Dockerfile

tried on Windows and Ubuntu,same problem...

**Comment by Gallaecio** [comment]
Can you indicate which commit or version of Splash you are using?
