### ISSUE TITLE
iframe option in run/execute endpoints

### ISSUE THREAD

**Issue by chinmayjatana** [scrapinghub/splash#1027]
Hi
is there any option in lua script to get information about iframes like render.json because i want to use splash:init_cookies function as well .

**Comment by ezDataCode** [comment]
@chinmayjatana , did you find a solution for this? 
I am encountering a similar issue where in I need to use lua script to set cookies, and to also click a button within an iframe, but I can not find a way to interact with the iframe and its contents within the lua script.

**Comment by chinudada** [comment]
@ezDataCode I dont think splash has functionality to interact with iframes. Setting up the cookies and clicking button in iframe can be done in selenium, although its slow and heavy as compare to splash.

**Comment by chinmayjatana** [comment]
@ezDataCode I dont think splash has functionality to interact with iframes. Setting up the cookies and clicking button in iframe can be done in selenium, although its slow and heavy as compare to splash.
