### ISSUE TITLE
amazon.com not working

### ISSUE THREAD

**Issue by manojprithvee** [scrapinghub/splash#1028]
I am getting this error 
`{"error": 502, "type": "RenderError", "description": "Error rendering page", "info": {"type": "Network", "code": 1, "text": "Connection refused", "url": "https://aax-eu.amazon-adsystem.com/s/iu3?d=amazon.in&slot=navFooter&a2=010158e1336508edded5d0e53699a63d54865ba8f34fbf4435b636602f1606948d32&old_oo=0&ts=1589273023853&s=Ab6Z0-2cAwqGWp3d28rVkBIHzARqlfHipMFMP7ktYrST&cb=1589273023853"}}`
can anyone help

**Comment by manojprithvee** [comment]
other websites are working

**Comment by lucywang000** [comment]
amazon has very strong anti-bot measures, so you need to using some proxies to crawl it, e.g. crawlera https://scrapinghub.com/crawlera
