### ISSUE TITLE
Splash does not render the javascript of this website at all

### ISSUE THREAD

**Issue by hhamud** [scrapinghub/splash#1034]
I have tried to use the Splash website to render this website however it does not render the javascript of this website at all despite increasing the waiting time to 30 seconds to allow the javascript time to render.

Here is the website

https://groceries.asda.com/product/cornflakes-honey-nut/kelloggs-corn-flakes-big-pack/910000043501

Why does this not work with Splash?

**Comment by alternativshik** [comment]
it also stucks on https://www.tiktok.com/trending/

**Comment by lucywang000** [comment]
1. it could be the website doesn't work well with the webkit engine used by splash
2. try disable private mode in splash, sometimes it could fix these problems.

**Comment by binishjoshi** [comment]
Same problem here, JS is not rendered at all. Just blank old site without JS. I even tried 10 seconds wait.
