### ISSUE TITLE
How to use filters with execute

### ISSUE THREAD

**Issue by maxifom** [scrapinghub/splash#1045]
I see filters args in render.html and others? How can I get filters to work with execute endpoint?

**Comment by lopuhin** [comment]
If you're fine with them working in the same way as for render.hml, then you can pass the same argument, as per https://splash.readthedocs.io/en/stable/api.html#execute 

> filters : string : optional
> Same as ‘filters’ argument for render.html.

**Comment by maxifom** [comment]
> If you're fine with them working in the same way as for render.hml, then you can pass the same argument, as per https://splash.readthedocs.io/en/stable/api.html#execute 
> 
> 
> 
> > filters : string : optional
> 
> > Same as ‘filters’ argument for render.html.

Thanks, I somehow missed it in the docs
