### ISSUE TITLE
jquery ERR_CONNECTION_REFUSED

### ISSUE THREAD

**Issue by HOWIE-CH** [scrapinghub/splash#1063]
The jquery plugin failed to load.
The console prints as follows.
GET http://code.jquery.com/jquery-1.11.1.min.js net::ERR_CONNECTION_REFUSED

**Comment by FanLucifer** [comment]
because of http://code.jquery.com/ can not access in China，you can change the cdn of jquery.
Here is the solution but it is still has problems
[https://www.jianshu.com/p/72b0663f6dea](url)
I  think if you like we can discuss with it

**Comment by Gallaecio** [comment]
This does not look like an issue in Splash itself. Please, feel free to move this topic to [StackOverflow](https://stackoverflow.com/questions/tagged/splash-js-render).
