### ISSUE TITLE
Ouota ExceededError: DOM Exception 22

### ISSUE THREAD

**Issue by songhao8080** [scrapinghub/splash#1151]
When i get some web url render the page
![image](https://user-images.githubusercontent.com/10607039/154225364-8f10578f-9554-4be6-8c41-d57938001fbb.png)
![image](https://user-images.githubusercontent.com/10607039/154225997-cfbcd5b0-d3f6-4a04-b4e1-663f4f03a490.png)

render the page error

**Comment by lime-n** [comment]
This does not look like a splash issue; likely you have been rate-limited. You can try scraping with a proxies or change your vpn, that's what your error is about.

**Comment by songhao8080** [comment]
> This does not look like a splash issue; likely you have been rate-limited. You can try scraping with a proxies or change your IP with a VPN, that's what your error is about.

No, this is the first time crawl test
and  i can test with selenium success
