### ISSUE TITLE
allow to yield to Lua from a JS callback

### ISSUE THREAD

**Issue by kmike** [scrapinghub/splash#122]
We should support something like this; I think it's doable:

```lua
local res = splash:runjs([[
function main(splash){
    window.setTimeout(function(){
        splash.return("I'm a result!");
    }, 1000);
}
]])
-- res is now "I'm a result!"
```

``runjs`` function will probably need another name, it is already taken.

**Comment by mehaase** [comment]
Hey Mikhail, I have a working implementation of this here: https://github.com/mehaase/splash/commit/ef04d75a2fc67f361e6e063432dc391f95767bd7. 

I chose the name `splash:runjs_async()`. Please look it over and let me know what you think. I can send a PR if you wish.

**Comment by mehaase** [comment]
Oh, here is a sample lua test script to demonstrate:

    function main(splash)
      local url = splash.args.url

      splash:autoload(splash.args.js_source)
      assert(splash:go(url))

      local async_result, err = splash:runjs_async([[
        setTimeout(function () {
          lua_resume("Good things come to those who wait.");
        }, 2000);
      ]])
      print(async_result, err)

      local async_result, err = splash:runjs_async([[
        setTimeout(function () {
          lua_error("But sometimes bad things come to those who wait.");
        }, 2000);
      ]])
      print(async_result, err)

      local async_result, err = splash:runjs_async([[
        setTimeout(function () {
          lua_resume(["Return","multiple","arguments","in","a","list!"]);
        }, 2000);
      ]])
      print(async_result, err)

      local async_result, err = splash:runjs_async([[
        setTimeout(function () {
          lua_resume("Don't wait too long or you might get interr-");
        }, 2000);
      ]], 1)
      print(async_result, err)

      splash:stop()
      splash:set_viewport("full")

      return {
        png = splash:png{width=640},
      }
    end

When executed, this prints out (with the appropriate delays in between):

    Good things come to those who wait.     nil
    nil     error: But sometimes bad things come to those who wait.
    Return,multiple,arguments,in,a,list!    nil
    nil     error: Timed out while waiting for runjs_async()

Cheers!

**Comment by kmike** [comment]
@mehaase looks great!
Could you please open a PR so that we can discuss it more easily? 
I have a lot of comments :)

**Comment by kmike** [comment]
Fixed by https://github.com/scrapinghub/splash/issues/162.
