### ISSUE TITLE
Any plans to upgrade to PyQt 5?

### ISSUE THREAD

**Issue by Ecno92** [scrapinghub/splash#139]
Splash is using PyQt4 while PyQT5 is already available. 
I was wondering if there are already plans or ongoing efforts related to upgrading to PyQt5.

If not: is it desireable and realistic to set a goal for this project to upgrade to the newer Qt version incuding the newer webkit browser in the near future?

**Comment by kmike** [comment]
See https://github.com/scrapinghub/splash/pull/222. Current code lives in https://github.com/scrapinghub/splash/tree/qt5 branch; tests pass, but there are some things missing - Dockerfile, doc updates, etc. I think it'll be merged to master after 1.7 release - there will be one more qt4-based Splash release.
