### ISSUE TITLE
Add "css" param to splash

### ISSUE THREAD

**Issue by pawelmhm** [scrapinghub/splash#142]
Currently splash gets all stylesheets by default. We could add parameter css=(0 or 1). This would work just like images param, when you set this to 1 you get images otherwise you don't.

**Comment by kmike** [comment]
I'm closing it in favor of https://github.com/scrapinghub/splash/pull/225. You can filter out requests based on URLs; with that PR you'll be able to filter CSS based on their Content-Type.
