### ISSUE TITLE
problems with splash:runjs and jquery

### ISSUE THREAD

**Issue by kmike** [scrapinghub/splash#149]
```
splash:runjs([[
  $(function(){
    //...
  });
]])
```
is problematic because $ returns an object, splash:runjs tries to convert it to Python and then to Lua. This is inefficient. For me it sometimes fail with "Can't convert object: depth limit is reached" error which means the object is huge. For @mehaase it even segfaults sometimes.

It is too easy to write such code, and the problem is not obvious; this means splash:runjs API is not good and we should think about how to fix it. 

Segfaults @mehaase is getting is another issue (there shouldn't be any); it'd be good to reproduce and fix them as well.

**Comment by kmike** [comment]
a temporary workaround:

```
splash:runjs([[
  $(function(){
    //...
  });
  42
]])
```

**Comment by mehaase** [comment]
Yes, @kmike, adding the extra expression (42) eliminates the segfault. Here's a reproducible test case:

```lua
function main(splash)
  local url = splash.args.url

  splash:autoload(splash.args.js_source)
  assert(splash:go(url))

  splash:runjs([[
    $(console.log('foo'));
  ]])

  splash:stop()
  splash:set_viewport("full")

  return {
    html = splash:html(),
    png = splash:png{width=640},
    har = splash:har(),
  }
end
```

This assumes that jQuery has been included via the js_source argument. Download [this gist](https://gist.githubusercontent.com/mehaase/73a82e9a4b99f89fc551/raw/54799bdc0273f41b9c0a39be143c98ffa1353b3e/gistfile1.json) and name it `body`, then run `curl -d @body -H 'content-type:application/json' 'http://192.168.31.1:8050/execute'`. This triggers a segfault on my machine reliably (16GB RAM, intel i7, Kubuntu).

**Comment by kmike** [comment]
@mehaase FYI: instead of POSTing jQuery via js_source argument it could be better to load it from CDN using [splash:autoload](http://splash.readthedocs.org/en/master/scripting-ref.html#splash-autoload), e.g. 

```
local jquery_url = "http://ajax.googleapis.com/ajax/libs/jquery/2.1.3/jquery.min.js"
assert(splash:autoload(jquery_url))
```

Make sure CDN uses Expires: header, it should allow library to be cached in memory.
