### ISSUE TITLE
Rendering doesn't work correctly when viewport size != image size

### ISSUE THREAD

**Issue by kmike** [scrapinghub/splash#169]
Example: http://127.0.0.1:8050/render.png?url=http://google.com&viewport=800x600&width=700

![render-google](https://cloud.githubusercontent.com/assets/107893/5882630/fd09337a-a36c-11e4-9b7f-df39cbc91c1e.png)

When width=800 (matching the viewport size) the result looks fine.

**Comment by immerrr** [comment]
It appears that some of 3d decorations cannot catch up with the resize of the viewport.

I cannot seem to reproduce this, neither on my local ubuntu nor on docker image of current master. Could you share your versions and/or logs for this situation?

**Comment by kmike** [comment]
Yeah, the example in ticket description works fine in Docker. 
I'm using OS X 10.10.1, Qt 4.8.6, PyQt 4.11.3, WebKit 534.34, sip 4.16.5.

But if you add some wait time there will be a rendering issue in Docker as well:
http://192.168.59.103:8050/render.png?url=http://google.com&viewport=800x600&width=700&wait=0.5
![render-docker](https://cloud.githubusercontent.com/assets/107893/5888054/038affda-a412-11e4-83a1-9fe0484144b3.png)

Note the button in upper-right. When width=800 the screenshot becomes correct.

**Comment by immerrr** [comment]
Yup, that I can reproduce.

There is indeed something wrong with rendering of that button: as the scale goes down, the button changes its size drastically while staying in bottom-right corner. Also its text doesn't change size: http://imgur.com/a/0uY5Z#0

**Comment by kmike** [comment]
Fixed by #172 by switching to raster rendering by default.
