### ISSUE TITLE
render_all=1 not rendering full webpage

### ISSUE THREAD

**Issue by pawelmhm** [scrapinghub/splash#177]
To reproduce:

localhost:8050/render.png?url=http%3A%2F%2Fwww.sainsburys.co.uk%2Fwebapp%2Fwcs%2Fstores%2Fservlet%2FSearchDisplayView%3FbeginIndex%3D0%26pageSize%3D30%26storeId%3D10151%26langId%3D44%26catalogId%3D10122%26searchTerm%3DELECTRONIC&wait=3&render_all=1

This is url: http://www.sainsburys.co.uk/webapp/wcs/stores/servlet/SearchDisplayView?beginIndex=0&pageSize=30&storeId=10151&langId=44&catalogId=10122&searchTerm=ELECTRONIC

with wait and render_all parameters.

I see full page is not rendered in screenshot.

Possibly related to https://github.com/scrapinghub/splash/issues/170

**Comment by kmike** [comment]
Are you sure you're using splash master? `render_all` is not present in Splash 1.3.1; it may explain why it doesn't work.

**Comment by kmike** [comment]
Your exmple query works for me.

**Comment by pawelmhm** [comment]
sorry! we have to update our splash servers
