### ISSUE TITLE
Viewport=full returning mobile version of page

### ISSUE THREAD

**Issue by pawelmhm** [scrapinghub/splash#178]
Seems like some pages are returning mobile content to users when you pass viewport=full as parameter to Splash render.png endpoint. 

For example this page: http://groceries.asda.com/asda-webstore/landing/home.shtml#search/chocoloate/1/relevance_desc

Following request to Splash:
```
localhost:8050/render.png?url=http%3A%2F%2Fgroceries.asda.com%2Fasda-webstore%2Flanding%2Fhome.shtml%23search%2Fchocoloate%2F1%2Frelevance_desc&wait=5&viewport=full
```

with viewport full returns mobile version of page:

![render](https://cloud.githubusercontent.com/assets/2700942/6062265/9c8a98d6-ad4e-11e4-9c7b-7cb9cf541845.png)

I get proper view only after changing default dimensions of viewport: 

```
localhost:8050/render.png?url=http%3A%2F%2Fgroceries.asda.com%2Fasda-webstore%2Flanding%2Fhome.shtml%23search%2Fchocoloate%2F1%2Frelevance_desc&wait=5&viewport=1366x768
```

This gives me desktop view

![render 1](https://cloud.githubusercontent.com/assets/2700942/6062295/d86605fc-ad4e-11e4-8294-40e8c08f4c89.png)

`

**Comment by kmike** [comment]
@pawelmhm the image you've posted is 640px wide; with Splash master it should be 1024px. Can you please confirm 1024px doesn't trigger mobile view for you?

**Comment by pawelmhm** [comment]
ah yes @kmike if I pass 1024x I get desktop view. So maybe this is something in viewport=full? Docs says that it should be have 1024x768.

**Comment by pawelmhm** [comment]
I'm aware that viewport=full is deprecated, but seems like render_all does not work well

**Comment by kmike** [comment]
This likely means you're using an older Splash version (or, in another words, docs for a wrong Splash version). 640px width and no `render_all` option is Splash 1.3.1 behaviour.

**Comment by pawelmhm** [comment]
ok, so online docs are outdated? https://splash.readthedocs.org/en/latest/api.html#arg-render-all

**Comment by kmike** [comment]
No, online docs are for splash master, and it seems you're using an older Splash version. You can use https://splash.readthedocs.org/en/1.3.1/api.html to get the docs for v1.3.1. 

I agree this is confusing, maybe we should point to stable docs by default.
