### ISSUE TITLE
Basic benchmark suite

### ISSUE THREAD

**Issue by pablohoffman** [scrapinghub/splash#184]
We need basic benchmark suite for Splash, something that renders a few typical web pages, hosted locally (to avoid network latencies affecting the results). Just a few (5-10) diverse enough websites should be enough to get started.

Goals for this benchmark in order of priority:
1. compare Splash performance reliable on different server configurations/deployments
2. find out typical render metrics, like average/peak memory consumption. This should help to figure out the optimal SLASH_SLOTS value for different server configurations
3. compare Splash performance with other tools (see #99)

**Comment by pablohoffman** [comment]
@immerrr could you work on this soon?

**Comment by immerrr** [comment]
FTR, this is the benchmark script I used when hacking on splash: https://gist.github.com/immerrr/a1419c4175d9c59d1cb6

**Comment by immerrr** [comment]
yup, will do

**Comment by immerrr** [comment]
Could you try the code from #185 and see if it is usable?
