### ISSUE TITLE
Allow to set result HTTP header from a Splash script

### ISSUE THREAD

**Issue by kmike** [scrapinghub/splash#188]

**Comment by pawelmhm** [comment]
are we talking about setting headers of response from target website in splash? Can this be implemented by adding :on_response method to splash, similar to :on_request method that we have? Or is this issue about setting HTTP header of response returned by splash?

**Comment by kmike** [comment]
> Or is this issue about setting HTTP header of response returned by splash to splash client?

Yes, this issue is about setting HTTP header of response returned by splash to splash client.

**Comment by pawelmhm** [comment]
ok @kmike I upvote both senses :)

**Comment by kmike** [comment]
Second sense is fixed by #227; for the first sense there is now #230.
