### ISSUE TITLE
Running splash from source code

### ISSUE THREAD

**Issue by HotSushi** [scrapinghub/splash#189]
I installed all the requirements from (https://github.com/scrapinghub/splash/blob/master/requirements.txt).

Say, I cloned the repository here..
user@ubuntu:~/splash$

Should I directly do 
user@ubuntu:~/splash$ python -m splash.server --port=5000
(if I do that than this is the error < https://gist.github.com/HotSushi/5600ce2742041ef3bc95 >

or Do I need to Build something first?

**Comment by HotSushi** [comment]
How do I start the splash server like the one from docker?

**Comment by kmike** [comment]
Hi @HotSushi,

It seems that xvfb system package is missing. Install it using apt-get.

**Comment by kmike** [comment]
Or maybe some other dependencies are not met. As it looks related to xvfb you can also try starting Splash with --disable-xvfb option.

**Comment by HotSushi** [comment]
thanks kmike, I have a new error please check it from this gist comment < https://gist.github.com/HotSushi/5600ce2742041ef3bc95 >

**Comment by HotSushi** [comment]
I think its because of the splash server that is running from docker.. How do I stop the server  http://0.0.0.0:8050/ ?

**Comment by kmike** [comment]
> How do I stop the server http://0.0.0.0:8050/

It depends on how did you start it :) If you start it with docker then run 'docker ps' to see running containers, find a name of splash container and run `docker stop <name>`. See https://www.docker.com/ for more info.

You can also use --proxy-portnum argument to run proxy server on another port.

**Comment by HotSushi** [comment]
Thanks very much kmike :) , it works now!
