### ISSUE TITLE
Allow to enable/disable JavaScript 

### ISSUE THREAD

**Issue by kmike** [scrapinghub/splash#191]
See https://github.com/scrapinghub/splash/blob/a18dbac13c8b13afe8c744d928650cbb2ce0b03f/splash/browser_tab.py#L110

This should be exposed as a Lua commands - `splash:enable_js()` and `splash:disable_js()`?

**Comment by kmike** [comment]
+ we should add an argument to the HTTP server.

**Comment by kmike** [comment]
It also worths it to expose other options; it could be a separate issue though.

**Comment by HotSushi** [comment]
Please test this patch for this issue(#191)  
https://gist.github.com/HotSushi/4b5189e4d626f6484717

**Comment by HotSushi** [comment]
Output of following Lua script
```
function main(splash)
    assert(splash:go('https://www.whatismybrowser.com/is-javascript-enabled'))
    png=splash:png()
    return png
end
```

![Image](https://cloud.githubusercontent.com/assets/6441597/6604868/991325ba-c851-11e4-9d29-06cfea5fc4f0.png)

**Comment by HotSushi** [comment]
After calling splash:disable_js() ..
```
function main(splash)
    splash:disable_js()
    assert(splash:go('https://www.whatismybrowser.com/is-javascript-enabled'))
    png=splash:png()
    return png
end
```
![imagedisablejs](https://cloud.githubusercontent.com/assets/6441597/6604920/06863cfe-c852-11e4-81f1-55c9f6b9fac2.png)

**Comment by HotSushi** [comment]
The function only works, if it called in the beginning not later!
```
function main(splash)
    assert(splash:go('https://www.whatismybrowser.com/is-javascript-enabled'))
    splash:disable_js()
    png=splash:png()
    return png
end
```
The output png will say 'Is Javascipt Enabled? YES' 

Any solution?

**Comment by kmike** [comment]
Hey @HotSushi,

Your patch is in a right direction, but it has some issues:

1. the indentation is off (we use 4 spaces consistently, as per PEP8);
2. these methods should be documented like all other methods (see https://github.com/scrapinghub/splash/blob/master/docs/scripting-ref.rst);
3. why is `self.web_view.setPage(self.web_page)` needed?
4. there should be automated tests for this feature (see https://github.com/scrapinghub/splash/blob/master/splash/tests/test_execute.py).

> The output png will say 'Is Javascipt Enabled? YES' 

The JS code which produces YES is executed before the JS was turned off. So this example doesn't show that the function is not working.

**Comment by kmike** [comment]
I'd also move these methods closer to other similar methods in BrowserTab.

**Comment by kmike** [comment]
Could you please also submit a PR instead of sending a link to the gist with a patch?

**Comment by HotSushi** [comment]
Hi @kmike,
Thanks for your comments, I'll make the necessary changes.

> Could you please also submit a PR instead of sending a link to the gist with a patch?

Ok I'll do that, Just wanted to make sure if the patch was working as expected!

**Comment by HotSushi** [comment]
@kmike , can you help me write test for this,
 I was thinking something like..

```python
def test_disable_js(self):
resp = self.request_lua("""
function main(splash)
    splash:disable_js()
    ok, error = splash:runjs("hello")
    local status = 'disabled'
    if ok == True then status = 'enabled' end
    return status
end
""")
self.assertStatusCode(resp, 200)
self.assertEqual(resp.text, "disabled")
```
AND


```python
def test_enable_js(self):
resp = self.request_lua("""
function main(splash)
    splash:disable_js()
    splash:enable_js()
    ok, error = splash:runjs("hello")
    local status = 'disabled'
    if ok == True then status = 'enabled' end
    return status
end
""")
self.assertStatusCode(resp, 200)
self.assertEqual(resp.text, "enabled")
```

but the Lua script seems to crash because runjs returns nil,
Any way around it?

**Comment by kmike** [comment]
1. I think it is better to test how webpage behaves, not how runjs/evaljs behave. I.e. if a web page has some js code then this code should work when js is enabled, and it should stop working when js is disabled. 
2. You also said that 'The function only works, if it called in the beginning not later!' - we should have a test case for it - load a web page, check that js is working, then disable js and check that it stopped working.
3. "hello" is not a valid JavaScript statement, it is probably a reason why splash:runjs returns nil. Try running it in a browser console - you'll get an exception. To understand why splash:runjs returns ok=nil you can also check 'error' value.

For tests which involve custom web pages you can use mock server (see how other tests are using it). Another way is to use splash:set_content.

**Comment by kmike** [comment]
Fixed by https://github.com/scrapinghub/splash/pull/192.
