### ISSUE TITLE
[GSoC Proposal] Modernize Splash to use Python 3.x, PyQt 5.x and asyncio/aiohttp. 

### ISSUE THREAD

**Issue by sunu** [scrapinghub/splash#195]
Hello everyone,
I'm interested to take up the Python3 and Qt5 porting project for Splash during GSoC. So here's the initial draft of my proposal. I'm also submitting this on Melange, but I'm submitting it here because the students are advised to do so on the idea page and it'll be easily and publicly accessible for further discussion and improvement even after the proposal deadline.  

# Python Software Foundation

 

## Sub-organization information

- Sub-organization with whom you hope to work(*): Scrapinghub

## Student Information

- Name(*): Tarashish Mishra
- Email(*): sunu AT sunu.in
- Time zone(*): UTC + 5:30
- IRC handle including network: sunu on freenode and oftc
 

- Source control username(s)(*): sunu on Github
- Home Page(s): http://sunu.in/about/
- Blog(s)(*): http://sunu.in/
- GSoC Blog RSS feed(*):http://sunu.in/tag/gsoc/rss/ 
 

## Project Proposal Information

-  **Proposal Title (*):** Scrapinghub: Modernize Splash
-  **Proposal Abstract (*):** Port Splash to run on Python 3.x and Qt 5.x and make it run on a recent OS (Ubuntu 14.04). Replace Twisted with asyncio and [aiohttp](https://github.com/KeepSafe/aiohttp) because Twisted is not Python 3 compatible yet.
-  **Proposal Detailed Description/Timeline (*):**
    * 27 April - 25 May: Get familiar with the code base. Read up on Python 2 to 3 porting guidelines. Try to increase test coverage of the codebase. Read up more on asyncio and aiohttp for replacing Twisted. (Twisted doesn't support py3 yet, so has to be replaced.)
    * 25 May - 14 June: Port the codebase to PyQt5. PyQt5 supports python 2.7 and from the little digging I have done so far, it seems porting from PyQt4 to PyQt5 is supposed to be fairly straightforward.
    * 14 June - 25 June: Begin the Python 3 porting process by [modernizing](http://python-modernize.readthedocs.org/en/latest/) the code base and try to make it both python 2.7 and 3.x compatible.
    * 26 June - 3 July: Buffer time.
    * 3 July: Midterm Evaluation
    * 3 July - 3 August: Complete the Py3 porting process. Replace the Twisted bits with asyncio and aiohttp.
    * 3 August - 17 August: 2 weeks of buffer time in case I lose time somewhere. If everything is on time I can spend this time to write helper scripts as described [here](http://gsoc2015.scrapinghub.com/ideas/#web-scraping-helpers).
    * 17 August - 21 August: Improve documentation, tests. 

## Links to additional information
- Successfully participated in GSoC 2013 under PSF. Worked on [OpenHatch training missions](https://openhatch.org/missions/)  and [Oppia](https://www.oppia.org/about). Worked on making Oppia more modular and platform independent. Ported the Openhatch tar training mission to Oppia.
- Contributed to MoinMoin wiki development. https://bitbucket.org/thomaswaldmann/moin-2.0/commits/all?search=sunu
- Contributed patches to various Mozilla projects including [Mozillians](https://github.com/mozilla/mozillians/commits/master?author=sunu), [ReMo](https://github.com/mozilla/remo/commits/master?author=sunu)
 

## Other Schedule Information

Finals will be during April last week and May first week tentatively.

I would love some feedback on the proposal. :smile:

**Comment by sunu** [comment]
@kmike ping! Please take a look :)

**Comment by kmike** [comment]
Hey @sunu,

Thanks for putting the proposal online!

Some notes:

1. Most of Twisted does support Python 3;
2. The issue with PyQT5/Qt5 port is that qt4reactor package doesn't support QT5/PyQT5 yet, and also it doesn't support Python 3. See also: https://github.com/scrapinghub/splash/issues/139. So there should be a plan on what to do with that: either fix this package, use a fork, or switch to something else; one options is asyncio + aiohttp + https://github.com/harvimt/quamash.
3. It is better for a timeline to be more detailed; per-week plan is the best; 2-week periods are also OK.
4. It should beclearly stated: will Splash support Python 2.x after the porting? What are the downsides of not supporting Python 2.x? What are the benefits? You said Splash will support both Python 2.7 and Python 3.3, but then you propose to use aiohttp which doesn't work in Python 2.x. The same question for Qt4 and PyQt4. Note that you can use PyQt5 with Qt4, but not PyQt4 with Qt5.
5. It is better to write docs and tests along the way, not to fix them later. This will allow to merge changes in small steps, and not in one huge PR. Huge PRs are much harder to get merged.
6. qt4reactor is not the only Splash dependency. Do other dependencies support Python 3? What to do if they don't? 

Proposal should contain more technical details, it should be more concrete - check e.g. the proposal we've accepted last year: https://gist.github.com/Curita/83851743f0db0d5b825c

**Comment by sunu** [comment]
@kmike I have updated the proposal. Here's the updated copy. https://gist.github.com/sunu/34bcffece5a4a22a58cd
Please let me know what you think.

**Comment by sunu** [comment]
Hello @kmike and other mentors!
 
Thanks for accepting my proposal. I'm pretty excited :) I was wondering what's the preferred way of communication from now  on?

**Comment by kmike** [comment]
Welcome onboard @sunu!

I think that for long discussions github issues / PRs are good because here it is easy to comment on code. Also, there is now a public chat room for Splash: https://gitter.im/scrapinghub/splash.

**Comment by estan** [comment]
Hi folks. I just stumbled across this proposal. We're using qt4reactor for some PyQt 4 applications at work, but we're (naturally) moving to PyQt 5. We haven't tried the qt5reactor from the Aether project discussed in the proposal yet, mostly because of lack of time.

Since I guess you'll be using qt5reactor from there in going forward, I was just going to ask: Should we perhaps approach them and ask if it can be broken out into a separate GitHub repo, and also packaged and released in PyPI, like qt4reactor?

**Comment by kmike** [comment]
Hey @estan,

@sunu created a repo with qt5reactor here: https://github.com/sunu/qt5reactor. I don't know if he approached @nehbit or @ghtdak.

**Comment by estan** [comment]
Excellent.

**Comment by kmike** [comment]
The code lives in a branch: https://github.com/scrapinghub/splash/pull/288; there is also `scrapinghub/splash:tmp-qt5` Docker image available which is updated automatically after each commit to #288.
