### ISSUE TITLE
proxy https

### ISSUE THREAD

**Issue by pawelmhm** [scrapinghub/splash#199]
from docs:

> Proxying of HTTPS requests is not supported.

Can this be supported somehow?

**Comment by dangra** [comment]
AFAIK only by hihacking the CONNECT method and returning a fake certificate as mitmproxy project does.

**Comment by cp2587** [comment]
+1, Is there any way around this ?

**Comment by kmike** [comment]
@cp2587 yes, use `application/json` POST requests instead of proxy mode.

**Comment by cp2587** [comment]
I am using scrapyJS so i think i am using a POST request. I was referring to this line of code in splash.proxy
`if protocol != 'http':  # don't try to proxy https
            return False
`
It seems i cannot use a proxy to query a remote https site ?

**Comment by kmike** [comment]
@cp2587 mm, you're right; there are two meanings of "proxy" in Splash - running Splash-as-a-proxy and using proxy servers from Splash. AFAIK the ticket was for Splash-as-a-proxy. 

As for using HTTPS proxies in Splash, just uncommenting this line could make it work (given that a proxy server supports https). But Im not sure. It was not tested, and that's the reason the line you quoted exists.

> if protocol != 'http': # don't try to proxy https return False

**Comment by kmike** [comment]
If it works with HTTPS out of the box I'd be happy to merge a PR removing this line :)

**Comment by cp2587** [comment]
Alright, i can test using one of my server (the actual version does not use the proxy, i verified) but i am not sure how to write an unittest for this. I will try to create a PR, thanks for your replies !

**Comment by kmike** [comment]
Thanks @cp2587! If you can confirm it works (fingers crossed) then it's fine to fix it without an unittest; I'm also not sure how to write a test.

**Comment by kmike** [comment]
Closed by #367.
