### ISSUE TITLE
adding lua console?

### ISSUE THREAD

**Issue by pawelmhm** [scrapinghub/splash#202]
There is experimental support for IPython which is really cool, but is it possible to add some way to execute lua scripts locally? 

I'd imagine something like this: start splash server in one terminal, connect to server in other terminal - execute some Lua commands and see results immediately. This would allow us to play around with Lua scripts before sending them as contents of GET or POST requests. Currently if you want to develop your scripts you have to send them to Splash in request.

**Comment by kmike** [comment]
Hi @pawelmhm,

How is it different from IPython support? Splash-Jupyter starts a local Splash renderer, connects to it and allows to enter Lua commands, execute them and see the results.

Differences from your proposal:

* server is started from IPython notebook UI when you start a notebook; 
* this server is called "kernel";
* the "kernel" is not the same server as standard HTTP API server - HTTP API server is stateless and talks via HTTP; kernel keeps the QWebView open and talks via zeromq. They both use the same rendering code ans scripting engine, but provide different API to access it.

You can start server from terminal yourselves using "ipython kernel" command, but you'll also need a frontent for it to enter commands and get the results. IPython notebook is such a frontend.

splash-jupyter docker image is just a way to make installation easier - Qt / PyQt development environment can be hard to get working. But if you can get Splash working locally you can install IPython Notebook and splash kernel locally - there are some [docs](http://splash.readthedocs.org/en/latest/kernel.html) about it. Installing it locally has benefits - you'll get a real browser window.

**Comment by pawelmhm** [comment]
ah thanks @kmike! so you say I can use Splash-Jupyter to execute lua as well? will check this out

**Comment by kmike** [comment]
Splash-Jupyter only allows to execute Lua, it is not doing anything else :)

Btw, it seems the docker images are currently broken.

**Comment by pawelmhm** [comment]
I am able to build and start docker container but following instructions in docs does not give me working ipython notebook in browser under http://0.0.0.0:8888/

**Comment by kmike** [comment]
1. do you use boot2docker? The ip address is not 0.0.0.0 in this case.
2. which docker image ar you using? Is it splash-jupyter?

**Comment by pawelmhm** [comment]
1. no, localhost:8888 does not work as welll
2. yes splash-jupiter from github repo (I'm not doing $ docker pull scrapinghub/splash-jupyter) but just building image from github

**Comment by kmike** [comment]
There are 2 dockerfiles in github repo: https://github.com/scrapinghub/splash/blob/master/Dockerfile and https://github.com/scrapinghub/splash/blob/master/dockerfiles/splash-jupyter/Dockerfile - do you use the latter? I think `docker build` should be called from the source root, and the proper docker file should be set using -f option.

**Comment by pawelmhm** [comment]
sure I know I use this one: https://github.com/scrapinghub/splash/blob/master/dockerfiles/splash-jupyter/Dockerfile I'm not calling from source root, will try calling from source root with -f option

**Comment by pawelmhm** [comment]
BTW is it okay to give also docs about initialization for people who don't want docker? I don't mind installing some dependencies if they are needed - i probably have most of them anyway.

**Comment by kmike** [comment]
Yes, it'd be a welcome addition. There are unfinished [notes](http://splash.readthedocs.org/en/latest/install.html#ubuntu-12-04-manual-way) for Ubuntu 12.04. Once you have splash installed this way you don't need anything extra to run splash-jupyter - install IPython notebook and run `python -m splash.kernel install`.

**Comment by pawelmhm** [comment]
okay works!
