### ISSUE TITLE
increase default MAX_WAIT_TIME

### ISSUE THREAD

**Issue by kmike** [scrapinghub/splash#209]
What about increasing MAX_WAIT_TIME to e.g. 50s? People keep asking about it: https://github.com/scrapinghub/splash/issues/141, https://github.com/scrapinghub/scrapy-splash/issues/6. It is possible to use any timeout with splash:wait() anyways, and the total execution time is limited by a timeout. //cc @pablohoffman

**Comment by cp2587** [comment]
Hello,
We have the same problem. The 'wait' args in scrapy-splash (which is linked to wait arg in the render endpoint i believe) is limited to 10s while using a Lua script you can wait for a much longer time. Is that something intentional ?

**Comment by kmike** [comment]
No, I think we should fix that. Pull request is welcome :)

Currently for /render endpoints effective timeout is `timeout+wait`, i.e. time spent in `wait` is not accounted in `timeout` for /render endpoints. If we keep this logic then there still should be a limit on `wait`, just a larger one. 

I'm also fine with changing this to be more straightforward: no limit on `wait`, effective timeout doesn't depend on `wait` (the same as in /execute endpoint with `splash:wait`). But this change would be backwards incompatible, so it is better to do it in a major release, e.g. together with https://github.com/scrapinghub/splash/issues/541. 

As a temporary measure increasing max `wait` to e.g. 30s sounds fine to me.

**Comment by adamgotterer** [comment]
Would also love to see an increase to the wait time
