### ISSUE TITLE
rename /debug to /_debug

### ISSUE THREAD

**Issue by kmike** [scrapinghub/splash#211]
What about using underscores for endpoints which are not related to rendering? //cc @pablohoffman 

Other possible endpoints:

* [_gc](https://github.com/scrapinghub/splash/pull/210)
* [_profile](https://github.com/scrapinghub/splash/pull/46)

(of course, we can keep /debug as an alias for backwards compatibility)

**Comment by pablohoffman** [comment]
SGTM
