### ISSUE TITLE
allow to get PNG snapshots of arbitrary page areas 

### ISSUE THREAD

**Issue by kmike** [scrapinghub/splash#213]
We should provide a way to render only a specified rectangular part of a page.

**Comment by pawelmhm** [comment]
I see this can be done by selecting node and calling render() method on selected element, it's not difficult to implement in qt 5.5 I discovered this when testing #380

**Comment by Youwotma** [comment]
Hey @pawelmhm, I think the method should accept an area (i.e. a table with top, left, width and height properties) rather than an element. If you want to capture an element, generally you will get what you want by using the elements bounding client rect as area (this is not exactly the same as rendering the element, but more often than not is what you actually want)

**Comment by pawelmhm** [comment]
> I think the method should accept an area (i.e. a table with top, left, width and height properties) rather than an element.

**Comment by pawelmhm** [comment]
@Youwotma I see it is also possible to render some region with parameters as you say, so your proposal is doable as well: [webframe.render()](http://doc.qt.io/qt-5/qwebframe.html#render) method has optional [QRegion](http://doc.qt.io/qt-5/qregion.html)  argument that could be used for that:

**Comment by kmike** [comment]
I think it should be (x,y,w,h) or (x1,y1,x2,y2) as @Youwotma said; you can find coordinates of an element using JS. 

As for API, it may be also better to specify coordinates in splash:png and splash:jpeg; it'll make API stateless which is good (so -1 for a separate `splash:select` call before `splash:png`).

This looks good:
```py
element = splash:select("some css selector")
return element:png()
```
we'll be on a path to a selection/scraping library this way. But it require some thought, and this feature can be built on top of (x,y,w,h) screenshots anyways.

It is good to implement as many features in JS and Lua (without using QWebView methods) because of two reasons:

1. this will make moving to qwebengine easier;
2. Qt has bugs, and it is much easier to fix an issue in our js/lua code than in upstream QWebView / QWebEngineView methods.

**Comment by pawelmhm** [comment]
> But it require some thought, and this feature can be built on top of (x,y,w,h) screenshots anyways.

actually coordinates are not necessary to get element matched by css selector. QT allows to take screenshot of webelement without specifying coordinates. Web page has method findElement which returns Element, and this Element has render() method same as mainFrame(). 

I did quick working demo here: https://github.com/pawelmhm/splash/commit/f4150dd999ea995358013a1df44137fb4add19f0#diff-ae7624b6441b7be8d29362b2755bf8daR34

Matching by css would be same as [firefox Screenshot Node functionality](https://developer.mozilla.org/en-US/docs/Tools/Page_Inspector/How_to/Examine_and_edit_HTML#Screenshot Node)

My only problem with coordinates is that it may be difficult from user point of view to get proper coordinates of element - what user sees in his browser may not match 1 to 1 to how page is rendered in Splash, e.g. some popups or alerts or other things can cause some trouble. Also user may have different viewport or zoom from Splash, so it could be difficult to use.

**Comment by kmike** [comment]
> My only problem with coordinates is that it may be difficult from user point of view to get proper coordinates of element - what user sees in his browser may not match 1 to 1 to how page is rendered in Splash, e.g. some popups or alerts or other things can cause some trouble. Also user may have different viewport or zoom from Splash, so it could be difficult to use.

To get coordinates user should select element (in a splash script) and call something like `.getBoundingClientRect()`; there is no need to use another browser and try to match coordinates.

**Comment by kmike** [comment]
I understand that taking a screenshot of element using element.render() is an easy win, but rendering arbitrary area is much more powerful, even if user only wants to get a screenshot of a single element. E.g. it may be nice to render an area which is a bit larger than he element itself, to give some context.

**Comment by kmike** [comment]
The problem is that our rendering code is quite convoluted (I don't fully understand this code): it has 4 separate modes of rendering (vector/raster scaling, tiling/no tiling).

It means adding an option to render an arbitrary area is more complex that adding an option to render a single DOM node matched by a CSS selector, but IMHO it worths the hassle. I did a minor cleanup in a branch (https://github.com/scrapinghub/splash/commit/dd2e8da2ef5272d32000592d98bcd26487499c90), maybe it can aid implementation.

**Comment by pawelmhm** [comment]
> there is no need to use another browser and try to match coordinates.

you are right about lua script, but in http api? here you would have to specify coordinates explicitly and you would have to take them from your browser, no?

so you say first do coordinates and css later?

**Comment by immerrr** [comment]
> It means adding an option to render an arbitrary area is more complex that adding an option to render a single DOM node matched by a CSS selector

I don't think so. When implementing this code I had this precise use-case in mind. There might be untested corner cases, but this should be the only place where viewport coordinates are "hard-coded":
https://github.com/scrapinghub/splash/blob/2b7b135/splash/qtrender_image.py#L101

You could probably move the majority of `render_qwebpage` method into `render_viewport(viewport)` and implement `render_qwebpage` on top of it.

**Comment by immerrr** [comment]
Also, FTR, all this hoop-jumping was to sidestep couple nasty Qt bugs that revealed themselves once the image exceeded 32k in any dimension. If the new version of Qt is free of those bugs, I suppose one could use the `Element.render()` method directly, if not, we're probably stuck with the convoluted code.

**Comment by pawelmhm** [comment]
seems like majority votes for coordinates so probably we'll go with that

**Comment by kmike** [comment]
@pawelmhm 

> you are right about lua script, but in http api? here you would have to specify coordinates explicitly and you would have to take them from your browser, no?

Well, script is HTTP API :) Are you suggesting to add an argument for render.png/jpeg to limit rendering to specific DOM element matched by a CSS selector? It can be useful in some cases, but in my projects I usually wanted something more dynamic, like rendering multiple elements (i.e. multiple screenshots, not a single picture) or rendering elements which satisfy some condition computed by lua/js. What is your use case?

Yep, I think doing coordinates first and css later makes sense - first get foundation right, then add shortcuts for common cases.

@immerrr 

> I don't think so. When implementing this code I had this precise use-case in mind.

That're good news! 

> I suppose one could use the Element.render() method directly, if not, we're probably stuck with the convoluted code. 

Hm, that's a good point - if Element.render() doesn't work for elements taller than 32K we'll need our rendering code anyways. That'd be an example of `Qt has bugs, and it is much easier to fix an issue in our js/lua code than in upstream QWebView / QWebEngineView methods.` :)

**Comment by pawelmhm** [comment]
>  Are you suggesting to add an argument for render.png/jpeg to limit rendering to specific DOM element matched by a CSS selector? 

Yeah I was thinking about something like this. If we add area to splash Lua api we can just as well add `area` parameter for render.jpeg or render.png or even render.html it may work in different way but general idea would be same.

**Comment by pawelmhm** [comment]
> .  like rendering multiple elements (i.e. multiple screenshots, not a single picture) or rendering elements which satisfy some condition computed by lua/js

hmm yeah this could be difficult with css if those elements dont have common ancestor, probably rendering with css selector and rendering with coordinates would serve different purpose.

My main use case would be: say you have 100 html pages with book products and you want to get price and title of each one of them. You just specify css for each one of them and it will always get proper element regardless of actual position - one page will have cookie popup, other page will have some other quirk which would mean that coordinates wont match, but html element will be something constant.
