### ISSUE TITLE
how install splash

### ISSUE THREAD

**Issue by agramesh** [scrapinghub/splash#217]
how could configure splash in windows, i receive error in final with vc++

**Comment by kmike** [comment]
Hi @agramesh,

I don't have an experience with Windows, but VC++ error sounds like a misconfigured build environment, not a Splash issue.

The recommended way to install Splash is to use Docker; this way you won't have to build anything on your machine. See http://splash.readthedocs.org/en/latest/install.html

**Comment by kmike** [comment]
Windows install instructions should be very similar to OS X + Docker.
