### ISSUE TITLE
Freezed while Initialization

### ISSUE THREAD

**Issue by dizlv** [scrapinghub/splash#220]
Created clean droplet on DigitalOcean (512MB ram). Tried to run via docker image. Server actually works, but when I provide url and click "Render", state changes on "Initializing..." and hangs.

In console I can see only requests to web-interface and nothing more. How to solve this issue?

**Comment by kmike** [comment]
Do you by chance use an ad blocker? See https://github.com/scrapinghub/splash/issues/163

**Comment by dizlv** [comment]
Oh, god. Thank you. I'm using uBlock.
