### ISSUE TITLE
configure with portia

### ISSUE THREAD

**Issue by agramesh** [scrapinghub/splash#223]
Hi
Is this splash support for portia to render javascript, I tried to crawl data from using portia  from javascript urls, so i need splash, I try to configure this splash by 'pip install requirements.txt', but it shows error like
"  Could not find a version that satisfies the requirement requirements.txt (from
 versions: )
No matching distribution found for requirements.txt"

please help me how to configure spalsh with portia
thanks in advance

**Comment by kmike** [comment]
Hi @agramesh,

There is a branch in Portia which allows to use Splash for JS rendering. But I don't know about it much; it is a work in progress. It seems this issue belongs to Portia, not to Splash. I don't know how to use them together.

`pip install requirements.txt` is incorrect; you need `pip install -r requirements.txt`. Also, not all dependencies can be installed with pip, notably PyQT. The official way to install Splash is to use Docker. See http://splash.readthedocs.org/en/latest/install.html.
