### ISSUE TITLE
document how to install Splash without Docker

### ISSUE THREAD

**Issue by kmike** [scrapinghub/splash#224]
Useful link, at least for Ubuntu: https://github.com/scrapinghub/splash/blob/master/dockerfiles/splash/provision.sh

Current docs: http://splash.readthedocs.org/en/latest/install.html#ubuntu-12-04-manual-way

**Comment by kmike** [comment]
It is documented for Ubuntu 16.04, and at the same time Docker should be preferred in most cases, so I'm closing this issue.

**Comment by goelayu** [comment]
Looks like both the above links return a 404. Could you point me to the relevant links? @kmike
