### ISSUE TITLE
provide splash:on_response_headers method

### ISSUE THREAD

**Issue by kmike** [scrapinghub/splash#231]
It should allow to register a callback called when response headers are received. This callback should allow to filter out responses based on their headers, URL and status code.

See also: https://github.com/scrapinghub/splash/pull/225, https://github.com/scrapinghub/splash/issues/106. 

This method should be called before splash:on_response proposed in #230; its purpose is to allow to filter out responses without having to download their bodies.

**Comment by pawelmhm** [comment]
I started impleneting this but I found out that there are obstacles if you want to actually modify QNetworkReply from python code, if you try to do something like

```python
reply = self.sender() # returns QNetworkReply object
reply.setRawHeader("foo", "bar")
```
you will get
```
RuntimeError('no access to protected functions or signals for objects not created from Python',)
```
this seems to mean that c++ objects such as QNetworkReply cannot be modified from Python, I looked into docs and setter methods like [setHeader or setUrl are protected](http://doc.qt.io/qt-5/qnetworkreply.html), public methods of reply are for reading only. 

I'm not exactly sure how we can bypass this, I don't see any code in splash that would actually modify responses. Perhaps we could recreate QNetworkReply object in python?

**Comment by pawelmhm** [comment]
I see access to protected functions is even listed as gotcha on PyQt docs page: http://pyqt.sourceforge.net/Docs/PyQt4/gotchas.html#access-to-protected-member-functions

**Comment by kmike** [comment]
@pawelmhm thanks for looking at it - hmm, yes, it could be tricky. You can try creating a reply copy [here](https://github.com/scrapinghub/splash/blob/aec50a784e3ccf920c3acfa1e5ce26d273da4887/splash/network_manager.py#L380) and return it, but I'm not sure Python object will be preserved after Python -> C++ -> Python roundtrip. The same applies to a subclass - maybe it won't work; there was a similar issue with QNetworkRequest, and subclassing it didn't help - bare QNetworkRequest was returned instead of a subclass after going through C++ grounds.

**Comment by pawelmhm** [comment]
to be clear we can still add splash:on_response_headers callback and have response object in lua with method abort() and some ways of accessing headers, this would still be useful for filtering out responses based on some criteria.

 Perhaps we can do this in first step, and try dealing with problem of protected methods later?

**Comment by kmike** [comment]
Yes, response.abort() and response.get_header() are both very useful.

It'd be great to have this feature in next Splash release because after https://github.com/scrapinghub/splash/pull/225 there is a way to filter out responses in render.xxx endpoints, but no way to do it from Lua scripts.

**Comment by kmike** [comment]
Fixed by #246 - thanks @pawelmhm!

**Comment by eng1neer** [comment]
Is there a way to actually modify response headers? Can you guys suggest a workaround for that?

**Comment by kmike** [comment]
@eng1neer I don't know an easy way, but you can do it in a proxy, e.g. with haproxy. 

Implementing it in Splash doesn't look straightforward (it can still be doable though).

**Comment by eng1neer** [comment]
@kmike Thanks, I will try going with Squid
