### ISSUE TITLE
add splash:set_result_status_code() method

### ISSUE THREAD

**Issue by pawelmhm** [scrapinghub/splash#235]
one use case for this would be in handling lua errors. 

As discussed in https://github.com/scrapinghub/splash/issues/161 lua scripts can encounter errors which are outside of user control and mapping from error to HTTP status code returned by splash is not obvious. Valid lua script can fail because website is not responding, or js is timing out or something else happens. If we would add set_result_status_code() method to splash, users could signal error conditions to splash client, for example they could write code like this

```lua
function main(splash)
    ok, reason = splash:go("http://www.example.com")
    if reason == "http500" then
        splash:set_result_status_code(503)
        splash:set_result_header("Retry-After", 10)
        return error
    else
        return splash:png()
    end
end
```

**Comment by kmike** [comment]
My only reservation is about how this feature will work for Splash SaaS offerings. When Splash is behind a load balancer, load balancer can make decisions based on HTTP status codes, and here users will become able to modify status codes directly. I don't fully understand the consequences. Maybe it is not an issue, just something to keep in mind. Other than that, +1 to add this feature.

**Comment by pawelmhm** [comment]
> When Splash is behind a load balancer, load balancer can make decisions based on HTTP status codes, and here users will become able to modify status codes directly. I don't fully understand the consequences. 

That's a good point. Perhaps @dangra could help us out here? If we allow users to set 5** status codes in splash, can this cause trouble for load balancers?

**Comment by dangra** [comment]
I think it is something to keep in mind and mention it on docs. I can't find a way to force a retry based on response status code for HAProxy,. For nginx is possible using [proxy_next_upstream](http://nginx.org/en/docs/http/ngx_http_proxy_module.html#proxy_next_upstream) directive but no status code is enabled by default.

**Comment by Youwotma** [comment]
Awesome, I needed this function just today!
