### ISSUE TITLE
Trying to render a page on localhost leads to rendering page errors

### ISSUE THREAD

**Issue by mappelgren** [scrapinghub/splash#237]
Hi,
I am building a scraper and wanted to create a test environment on my local machine before I deployed it. However, when I attempt to, say, render my homepage at localhost using render.html I am faced with a 502 Bad Gateway error. I have a feeling it may have to do with me trying to request my localhost from the localhost, but if that is the case I do not know how to solve it/ if I can solve it.

Any help would be much appreciated, thank you.

**Comment by kmike** [comment]
Hi @mappelgren,

Are you using Docker? It looks similar to https://github.com/scrapinghub/splash/issues/234. The problem is that for Splash inside Docker container localhost is not your localhost.

**Comment by mappelgren** [comment]
Yes, you are right, this seems to be what I'm looking for. Thanks!
