### ISSUE TITLE
Does Splash handle javascript set cookies?

### ISSUE THREAD

**Issue by mappelgren** [scrapinghub/splash#238]
I'm interested in building a scraper that goes through a site and finds what cookies are being set both 1st party and 3rd party. Scrapy's built in cookie middleware only deals with cookies set in http headers (set-cookies). I'm interested in cookies set through other methods, for example javascript. Therefore I wonder, how does Splash/scrapyjs handle cookies set through other means than http headers? Does it set javascript cookies or handle them in any way? Or are they just ignored?

**Comment by Youwotma** [comment]
I just checked and they don't get saved or reported in the har file, so pretty much ignored.

**Comment by mappelgren** [comment]
Ok, thanks! Thats too bad, do you think it would be possible to modify something to make them at least acknowledge that they are being created?

**Comment by Youwotma** [comment]
As a workarround you could [inject a script](https://splash.readthedocs.org/en/latest/api.html#execute-javascript) to read the contents of document.cookie.
I don't know what endpoint you are using, but for example you could save it as an attribute of the body element with this script.
```
document.body.setAttribute("data-cookie", document.cookie);
```

**Comment by mappelgren** [comment]
Ok, so document.cookie would contain the cookies but they wouldn't be set or forwarded with requests. That makes sense. Thanks a lot for your help!

**Comment by kmike** [comment]
Thanks for the discussion! See also: https://github.com/scrapinghub/splash/issues/135. We need to fix it somehow.

**Comment by lucaswxp** [comment]
Hey guys.

For me, document.cookie appears to be always empty, try this request, for instance:
```sh
curl -i -X POST -H 'content-type: application/json' -d '{"js_source": "document.body.setAttribute(\"data-cookie\", document.cookie);", "wait": 3, "url": "http://www.americanas.com.br"}'  http://localhost:8050/render.html
```
Then `body[data-cookie]` will be empty.

But if I do a raw curl request, I get the cookies set back:
```sh
curl -I http://www.americanas.com.br
> ...
Set-Cookie: MobileOptOut=1; path=/; domain=americanas.com.br
Set-Cookie: b2wChannel=ACOM; path=/; domain=americanas.com.br
Set-Cookie: akaau=1438897818~id=b874481c11a6576d5e992cfba8510912; path=/
```

Any guidance in how do I get all cookies from the response within splash?

**Comment by herlon214** [comment]
:+1:

**Comment by Youwotma** [comment]
@lucaswxp splash network cookies and javascript cookies are completely disconnected, network cookies won't appear in `document.cookie` and cookies set using javascript won't be sent to the server, or persisted in any way.

To get network cookies, use `render.har` or `render.json` with `har=1`or the `/execute` endpoint returning `splash:har()` as part of the response. HAR is a format that contains information about the network requests including cookies.

To get javascript cookies, see my comment in this bug from Jun 10

**Comment by Youwotma** [comment]
Another problem with javascript cookies at the moment is that they are shared between simultaneous slots/tabs, for example if you load at the same time this two pages, from the same domain, with a wait time of a couple seconds:
```
<script type="text/javascript" charset="utf-8">
    setInterval(function(){
        document.cookie = "test=foobar";
    }, 500);
</script>
```
And 
```
<pre id="log"> </pre>
<script type="text/javascript" charset="utf-8">
function log(s) {
    document.querySelector('#log').firstChild.nodeValue += '\n' + s;
}
setInterval(function() {
    log("cookie: " + document.cookie);
}, 1500);
</script>
```
The second page will be able to read the cookie from the first.

**Comment by kmike** [comment]
@Youwotma do you think it is OK to close this ticket?

**Comment by Youwotma** [comment]
Yes, since you opened #318 to track the cookie sharing problem

**Comment by kmike** [comment]
@Youwotma #338 solves it, right? Is it OK to close this ticket?

**Comment by Youwotma** [comment]
Yes :)
