### ISSUE TITLE
How install Splash on Centos without Docker?

### ISSUE THREAD

**Issue by fanjianing** [scrapinghub/splash#240]

**Comment by kmike** [comment]
Hi,

I don't have exact instructions for CentOS. To get Splash 1.6 running without Docker on any OS you need to install the following packages:

* Python 2.7;
* Qt 4 (not too outdated);
* PyQt 4 (not too outdated);
* lua 5.2 with dev headers;
* tools required to build Python packages with C/C++ extensions - a compiler, Python dev headers, etc.

Then you need to install Python packages from [here](https://github.com/scrapinghub/splash/blob/master/requirements.txt); re2 and testing packages can be skipped.

**Comment by foreverbeyoung** [comment]
I installed splash in centos without docker, but there is something that doesn't start up. Can you specifically change it?  The following is the error：
[16962:16962:0105/132751.730130:ERROR:zygote_host_impl_linux.cc(90)] Running as root without --no-sandbox is not supported. See https://crbug.com/638180
