### ISSUE TITLE
Har Content

### ISSUE THREAD

**Issue by AlexIzydorczyk** [scrapinghub/splash#248]
Hi,

I'm trying to get acquainted with the repo to understand what Splash is doing under the hood. One useful feature that I often use is the har_file. It would be nice to be able to see the content of responses in the Har file. I notice that in the `reply2har` method in `splash/har/qt.py` has a `include_content` parameter that defaults to false. 

It also appears that in `splash/network_manager.py`, when a request is made, the har is updated:

`
            if har_entry is not None:
                har_entry["response"].update(har_qt.reply2har(reply))
`

The include_content parameter is left out, defaulting to False. Would recording the Har content be as simple as modifying that line?

Thanks
Alex

**Comment by kmike** [comment]
Yes, it is that simple. Currently it is disabled because if you enable it, network manager will keep an extra copy of all downloaded data even if user won't call `splash:har()` in the end.

**Comment by AlexIzydorczyk** [comment]
Thanks!

**Comment by AlexIzydorczyk** [comment]
@kmike 

Actually, I may have spoken too soon - it appears that all the replies are coming out entry (Size is 0 and there text field is "").

It seems to me like something might be reading the bytes from the reply before the HAR reader gets to it? Any ideas/pointers as to where I could look for a workaround?

**Comment by kmike** [comment]
Thanks for checking it. I think it happens because `reply.readAll()` moves read pointer to the end, so it can be called only once, and it may be already called by a rendering engine. Maybe calling `reply.seek(0)` before `reply.readAll()` will fix it.

**Comment by AlexIzydorczyk** [comment]
Thanks, I'll try adding ```reply.seek(0)```.

For now, I've solved the immediate problem by recording pages to a cache and reading back from that cache. 

Let me try ```reply.seek(0)``` - that would be a much cleaner+easier solution.

**Comment by AlexIzydorczyk** [comment]
It turns out that ```reply.seek(0)``` does not work because reply content is a sequential device. And according to this sequential devices can only be read once.

>Sequential devices don't support seeking to arbitrary positions. The data must be read in one pass. The >functions pos() and size() don't work for sequential devices. QTcpSocket and QProcess are examples >of sequential devices.

http://doc.qt.io/qt-4.8/qiodevice.html

The solution is to cache everything and then read it back from the cache when building the HAR file. The relevant question was asked here: http://stackoverflow.com/questions/7136962/why-the-qnetworkreply-readall-returns-zero-bytes

I have the basic functionality working but am running into a road block if the site uses Pragma: no-cache or Cache-control to prevent the browser from caching, it seems that the qt browser respects that.

Based on that Stackoverflow answer and Qt docs, it seems that the saveToDisk() flag has to be overwritten somehow. I'm trying to figure out how to do this, if anyone has any pointers that would be tremendously helpful.

**Comment by kmike** [comment]
This will be possible in upcoming Splash 2.2: there is now [splash.response_enabled](http://splash.readthedocs.io/en/latest/scripting-ref.html#splash-response-body-enabled) flag, [request:enable_response_body](http://splash.readthedocs.io/en/latest/scripting-request-object.html#splash-request-enable-response-body) method and [response_body](http://splash.readthedocs.io/en/latest/api.html#arg-response-body) HTTP argument.
