### ISSUE TITLE
Render.html vs splash:go & relative URLs

### ISSUE THREAD

**Issue by AlexIzydorczyk** [scrapinghub/splash#249]
Apologies for filing so many issues - another quick question...

I'm noticing different behavior between the `render.html` and the `execute` end points when using `splash:go` and rendering the html. 

This appears to be problematic when there is Javascript executing on a page immediately after loading, making ajax calls (using POST). 

The execute endpoint does not seem to make the calls at all (I'm logging all outgoing requests), even despite "waiting". 

The render.html endpoint makes the calls (can be observed in developer tools), but because the calls are made using relative urls, the calls 404.

My solution was to write a lua script that identifies outgoing requests that are incorrectly being routed to my server IP and replace that IP with the proper base url. Unfortunately, this will not work because the execute endpoint doesn't "see" those calls at all - as if they were never made. 

For instance:

`/render.html?wait=0.5&images=1&expand=1&url=https://www.google.com`

Renders the google homepage - note that with Chrome Developer Tools open, you can see that many requests result in 404. The request url is [my server IP]/relative/resource

I tried to fix the problem using a simple lua script to find and replace my IP with the correct baseurl but this script does not appear to capture the requests:

```
function main(splash)
    local urls = {}
    splash:on_request(function(request)
        urls[#urls+1] = request.url
    end)
    assert(splash:go(splash.args.url))
    return urls
end
```

Note that the Ajax request is a POST. I've seen some discussion about POSTs not being implemented here, in the context of AJAX requests here in #239 . Is this what is causing the the POSTs not being sent in /execute?

If so, could anyone point me to what would need to be done to implement the POST method? I'm having a bit of trouble finding there the .get method in network_manager  but would be happy to see if I could contribute.

**Comment by AlexIzydorczyk** [comment]
This is a bit convoluted but I guess the crux of it is where are POST requests getting filtered out?

When I run the /render.html endpoint - see

```
2015-07-01 23:04:32.586319 [HTTPChannel,0,10.0.47.152]
2015-07-01 23:04:32.599839 [HTTPChannel,1,10.0.47.152]
...
```

That just seems like the javascript is running on the page when it's loaded and hitting the Splash server (as the usual request logs are made by [network] ). 

Is the issue that Splash can't handle POST requests or that the Javascript on the page making those POST requests does not run until Splash is done rendering the page?

**Comment by kmike** [comment]
> For instance:
> /render.html?wait=0.5&images=1&expand=1&url=https://www.google.com
> Renders the google homepage - note that with Chrome Developer Tools open, you can see that many requests result in 404. The request url is [my server IP]/relative/resource

Did you render a HTML using splash and then opened it in a browser? I think it works as expected, just a regular browser behaviour. If you want to see HTML file in a browser you can add a custom `<base>` tag to the result - this will make all relative URLs to use another base URL. When you open HTML in a browser it is not Splash which is doing HTTP requests to related resources (it already did that), it is your browser which is doing that.

Splash should handle AJAX POST request fine.

**Comment by AlexIzydorczyk** [comment]
@kmike , You're right. This was my mistake.

It turns out Splash actually does make those calls as you say. The challenge comes in attempting to read the content of those calls (#248)
