### ISSUE TITLE
Splash not dealing well with url fragments

### ISSUE THREAD

**Issue by Venereo** [scrapinghub/splash#250]
Urls that use fragments as javascript parameters are not being correctly parsed i.e: http://www.example.com#/?pl=80&page=2

**Comment by kmike** [comment]
Could you please provide an example? What request do you send to Splash?

**Comment by cr8ivecodesmith** [comment]
@Venereo If you're using Scrapy for your spider, I think its more to do with Scrapy's implementation of the Request class. I got around this by implementing my own Request class that doesn't attempt to clean or encode the url string passed to it.

```python
class RawRequest(Request):
    """Do not apply any encoding or safe string checks on the url.

    """
    def _set_url(self, url):
        self._url = str(url)
```

**Comment by kmike** [comment]
@cr8ivecodesmith nice catch, we should fix it in scrapy-splash/scrapyjs.

**Comment by matiskay** [comment]
I got the same problem and I found that [`escape_ajax`](https://github.com/scrapy/scrapy/blob/master/scrapy/http/request/__init__.py#L54) function in Request class is changing the `#` to `_escaped_fragment_`.

```python
from scrapy.utils.url import escape_ajax
url = 'https://www.google.com/about/careers/search#!t=jo&jid=166355001&'
print escape_ajax(url)
# result: 'https://www.google.com/about/careers/search?_escaped_fragment_=t%3Djo%26jid%3D166355001%26'
```

scrapy version: 1.0.5
python version: 2.7.10

**Comment by cr8ivecodesmith** [comment]
Have you tried creating your own request class to avoid the URL cleanup?

**Comment by matiskay** [comment]
@cr8ivecodesmith, I did that using your code,RawRequest. It works perfectly on my computer but it fails in Scapy Cloud. I think Scrapy Cloud cleanup the Requests.

**Comment by cr8ivecodesmith** [comment]
@matiskay, I have encountered the same behavior in Scrapy Cloud. The issue as I have observed had to do with [request serialization](http://doc.scrapy.org/en/latest/topics/jobs.html#request-serialization). This is because the `JOBDIR` setting is enabled for each job run in Scrapy Cloud. I read this somewhere but can't find the link anymore. You can confirm this by enabling it on your computer even with the RawRequest class being used.

I wasn't able to work around this as I have resolved to run that spider internally. Perhaps you could try setting JOBDIR to `None` in your spider's custom setting?

**Comment by kmike** [comment]
This should work properly in latest https://github.com/scrapy-plugins/scrapy-splash. Make sure to check the [changelog](https://github.com/scrapy-plugins/scrapy-splash/blob/master/CHANGES.rst) before upgrading; v0.3 was not backwards compatible with old scrapyjs.

Thanks for the heads up!

**Comment by icebear181818** [comment]
hello, i am new to scrapy, i need to crawl the data from [https://www.google.com/partners/#a_search;bdgt=10000;lang=en;locn=United%20States;motv=0;wbst=http%253A%252F%252F](url)
i found that response in scrapy only catch the url before #, i tried several methods, but failed
i also tried the method what matiskay  mentioned, but still doesn't work, can i use splash to pass the whole url? thank you

**Comment by kmike** [comment]
Hey @icebear181818! The way to go is to use SplashRequest from scrapy-splash; it supports `#` in URLs.

**Comment by icebear181818** [comment]
thank you so much @kmike !!!!
i still confuse about the url matiskay mentioned, 
`from scrapy.utils.url import escape_ajax
url = 'https://www.google.com/about/careers/search#!t=jo&jid=166355001&'
print escape_ajax(url)
# result: 'https://www.google.com/about/careers/search?_escaped_fragment_=t%3Djo%26jid%3D166355001%26'`
i also tried to use **escape_ajax** to change my url, but doesnt work, could you please tell me what is the difference between mine and matiskay's? thank you !!!
