### ISSUE TITLE
question: splash needs to scroll down?

### ISSUE THREAD

**Issue by ohade** [scrapinghub/splash#252]
I tried to scrape my home page and it looks like (when i did the render.png option ) the scrape only gets the first part of the page,
could it be that i need to scroll down on the page?
The page is not dynamically loaded, like google images for example...

**Comment by immerrr** [comment]
You might be missing [render_all=1](http://splash.readthedocs.org/en/latest/api.html#arg-render-all) parameter in your request.

**Comment by ohade** [comment]
Didn't know this parameter. 
Do I need to use it also on render.Json option?

**Comment by immerrr** [comment]
[render.json documentation](http://splash.readthedocs.org/en/latest/api.html#render-json) (you should totally check it out, it's nice) says that it accepts all the parameters that render.png accepts, so yes, most likely you need the same for render.json.
