### ISSUE TITLE
question: how to disable stylesheet and image load?

### ISSUE THREAD

**Issue by ohade** [scrapinghub/splash#253]
Bottom line it looks like the size of the scraped page does not change when putting this next options and when not putting them (the options are: images:0 and filters:myblocker)

I am doing this next curl request:

curl -s -X POST -H 'content-type: application/json' -d "{\"filters\": \"myblocker\", \"timeout\": 3, \"wait\": 0.5, \"images\": 0, \"url\": \"${url}\", \"html\": 1,\"headers\":  {\"name\": \"User-Agent\", \"value\": \"Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:38.0) Gecko/20100101 Firefox38.0\"}}" http://${ip}:${port}/render.json

when the myblocker file looks like this:
-*.css^
-*$image,stylesheet

And the file is supplied like this:
docker run -d -p 8050:8050 --memory=1G --restart=always -v /home/ubuntu/filter/:/etc/splash/filters/ scrapinghub/splash:latest --maxrss 500

Thanks

**Comment by kmike** [comment]
How are you measuring scraped page size? In the example curl request you're getting a JSON with HTML of a page. Disabling images and CSS usually doesn't change HTML size - you'll likely get a different screenshot and a different set of resources to download, but the HTML usually stays the same (unless there is some JS code which takes e.g. calculated DOM element sizes in account - this should be rare).
I think you're returning only HTML contents from your render.json request

**Comment by ohade** [comment]
I am piping the content to file.
Why is the size of the file should not change? its holding less content...

Am i using the filter currently?
This is how i should define it?

**Comment by kmike** [comment]
I think you're using filters and images=1 option correctly.

Let's say the HTML is 

```
<html><body><img src='foo.jpg'/></body></html>
```

If you have images=1, Splash will fetch this HTML page, then it'll fetch foo.jpg file and render a result internally. Then you ask splash to return the result - render.json is used with html=1 option (and no e.g. png=1 or har=1). With just html=1 Splash will return you just the HTML source code, which is the same regardless of if you've loaded foo.jpg file or not. So Splash will download less data with images=0 (no need to fetch an image), but the HTML result returned to the client will be the same. The result would be different if you e.g. use render.json with png=1 option - screenshots will be different.

**Comment by kmike** [comment]
I'm not sure it is a bug.
