### ISSUE TITLE
splash:url() returns wrong value after pushState

### ISSUE THREAD

**Issue by Youwotma** [scrapinghub/splash#259]
I found a strange behavior when using pushState (either via runjs or a script in the page calling it) splash:url() (or BrowserTab.url) doesn't reflect the correct url after calling pushState. When changing the page's hash (either by javascript or by click event on a `<a href="#somehash"/>`) it shows the correct url again.

```
function main(splash)
  local url = "http://dev.scrapinghub.com/~david/";
  assert(splash:go(url))

  assert(splash:runjs("history.pushState({}, '', '/newstate')"))
  assert(splash:runjs("document.writeln(location.href + ' != " .. splash:url() .."')"))
  
  -- After changing the location hash, it shows the correct url again
  assert(splash:runjs("location.hash = '#test'"))
  assert(splash:runjs("document.writeln(location.href + ' == " .. splash:url() .."')"))
  return {
    html = splash:html(),
  }
end
```

Output
```
<html><head></head><body>
http://dev.scrapinghub.com/newstate != http://dev.scrapinghub.com/~david/
http://dev.scrapinghub.com/newstate#test == http://dev.scrapinghub.com/newstate#test
</body></html>
```
Note that in the first line the splash:url() result is not correct.

**Comment by kmike** [comment]
I think this has something to do with the old WebKit version in qt4. In https://github.com/scrapinghub/splash/tree/qt5 branch the output for your example is the following:

```
<html><head></head><body>
http://dev.scrapinghub.com/newstate != http://dev.scrapinghub.com/newstate
http://dev.scrapinghub.com/newstate#test == http://dev.scrapinghub.com/newstate#test
</body></html>
```

**Comment by Youwotma** [comment]
Thanks! for the moment using evaljs('location.href') as a workaround, looking forward to the qt5 version!

**Comment by kmike** [comment]
@Youwotma FYI: there is `scrapinghub/splash:tmp-qt5` Docker image available with qt5-based Splash; it is built from https://github.com/scrapinghub/splash/pull/288.

**Comment by kmike** [comment]
I'm closing it because splash master now uses Qt5.
