### ISSUE TITLE
Attribute Error

### ISSUE THREAD

**Issue by agramesh** [scrapinghub/splash#282]
while running portia i received error as 

  File "C:\Python27\lib\site-packages\twisted\application\app.py", line 451, in
createOrGetApplication
    ser.setServiceParent(application)
AttributeError: Site instance has no attribute 'setServiceParent'

how could it resolve

**Comment by kmike** [comment]
Hi @agramesh,

This doesn't look like a Splash issue. Could you please open an issue in https://github.com/scrapinghub/portia bug tracker instead?
