### ISSUE TITLE
Create a set of reference/example scripts

### ISSUE THREAD

**Issue by kmike** [scrapinghub/splash#286]
@pablohoffman's ideas (which I agree with):

1. Create a folder with example scripts for common tasks and move many example scripts from the docs there;
2. include these scripts in docs;
3. show these examples in Splash UI.

Another idea is to create a list of Jupyter notebooks; they render nicely in github.

**Comment by pawelmhm** [comment]
we have bunch of Lua scripts in docs already, for starters we could just copy paste them from docs to example folder. If we store scripts in two places (docs and /examples folder) they can get out of sync, someone will update in one place but forget about other, is it ok or should we keep them in sync somehow?

**Comment by kmike** [comment]
Yeah, I think we should put 'canonical' version to 'examples' folder and include them in Sphinx docs. Neither duplicating nor removing examples from docs look good to me.
