### ISSUE TITLE
make retrying requests in go() easier

### ISSUE THREAD

**Issue by pawelmhm** [scrapinghub/splash#305]
Currently when response to splash:go() is 500 assert(splash:go()) raises exception, and if Lua script does not handle this exception client gets 400. 

Maybe we could add some way to automatically retry some typical error codes? I imagine some optional parameter to go() that would force go() to retry on error, something similar to Scrapy behavior - Scrapy just retries typical HTTP error codes in retry middleware so user doesn't have to worry about it.

**Comment by Youwotma** [comment]
This can be trivially implemented in lua and should be implemented in the user script IMO

**Comment by kmike** [comment]
I agree with @Youwotma. It can be also better to retry requests to Splash instead of retrying requests inside Splash. The main reason I prefer not to have built-in retries in splash:go is that browsers don't do retries when you enter a URL to the address bar.

**Comment by pawelmhm** [comment]
ok if you say so, no problem :)

**Comment by Youwotma** [comment]
This is a good candidate for a code snippet for #286
