### ISSUE TITLE
splash doesn't stop request processing when client disconnects

### ISSUE THREAD

**Issue by kmike** [scrapinghub/splash#306]

**Comment by Youwotma** [comment]
Sometimes when I kill a splash request the next request fails immediately, I don't remember what error did it get or under what conditions it happens. I suspect some state might be kept somewhere and carried over to the next request.

**Comment by kmike** [comment]
@Youwotma are you using splash directly? Can it be an issue with a load balancer?

**Comment by Youwotma** [comment]
I'm running it directly but with a  pretty long running lua script that and I kill the spider if I see something wrong without waiting for it to finish.

**Comment by kmike** [comment]
@Youwotma your error looks different; if you can find an example it'd be good to open a new ticket.
