### ISSUE TITLE
question: Is there a way to get the network traffic while the page is loaded?

### ISSUE THREAD

**Issue by ohade** [scrapinghub/splash#309]
The current running parameters i used, only gives me the page ones it was rendered.

(
curl -s -X POST -H 'content-type: application/json' -d "{\"render_all\": 1, \"timeout\": ${timeout}, \"wait\": ${wait}, \"images\": 0, \"url\": \"${url}\", \"html\": 1, http://${ip}:${port}/render.json
)

My problem is that there are a lot of javascript that the page contain that i am interested in that in the final version of the page are removed.

Is there a way to get the network traffic while the page is loaded? like in chrome "network" tab for example?

**Comment by kmike** [comment]
Hi @ohade,

Could you please clarify what do you want to capture? Do you want contents of all received resources, snapshots of HTML body as time goes, information about all requests (duration, URL, method, headers) like in chrome "network" tab?

Some links:

* http://splash.readthedocs.org/en/stable/api.html#arg-har
* http://splash.readthedocs.org/en/stable/scripting-ref.html#splash-har
* http://splash.readthedocs.org/en/stable/scripting-ref.html#splash-on-request
* http://splash.readthedocs.org/en/stable/scripting-ref.html#splash-on-response-headers
* http://splash.readthedocs.org/en/latest/scripting-ref.html#splash-on-response (new in upcoming Splash 1.8)
* http://splash.readthedocs.org/en/latest/scripting-ref.html#splash-call-later (new in upcoming Splash 1.8)
* https://github.com/scrapinghub/splash/issues/230

**Comment by ohade** [comment]
Hi @kmike, thanks for the quick response.
Currently i am interested in the js that triggered request, for example, looking at this page when its being loaded gave me js names like:
Coordinator.js, GlobalUtils.js and others ( it also told me, what line in the page initiated this call and houw long it took, but i am less interested in that ).
I just want the resources names. Is it posible?

**Comment by kmike** [comment]
Yes, just pass 'har=1' option to render.json. 

By the way, try going to http://<your-splash-address>:8050/ - it will show an UI where you can enter an URL to render. After submitting it'll show a screenshot and a chart similar to "network" tab in browsers; for the chart it uses either splash:har() method (if Lua is enabled) or 'har=1' option for render.json (if Lua is disabled).

**Comment by kmike** [comment]
ah, if you need to check which JS file initiated which request HAR won't help you

**Comment by kmike** [comment]
in this case you can override XMLHttpRequest.prototype.send and add custom logic there, something similar to

```js
    // Monkey patch the XHR.send() method so that we can track when
    // XHRs start and finish.
    function patchXhrSend() {
        if(_xhrSendIsPatched) {
            return;
        }

        oldXhrSend = XMLHttpRequest.prototype.send;
 
        XMLHttpRequest.prototype.send = function(body) {
            var self = this;
            var oldOnLoad;

            // put custom logic here

            window.dispatchEvent(new Event(_xhrInterceptedEvent));

            oldOnLoad = this.onload;

            this.onload = function() {
                // put custom logic here

                window.dispatchEvent(new Event(_xhrFinishedEvent));

                if (oldOnLoad) {
                    oldOnLoad.call(self);
                }
            };

            oldOnError = this.onerror;

            this.onerror = function() {
                // put custom logic here

                window.dispatchEvent(new Event(_xhrFinishedEvent));

                if (oldOnError) {
                    oldOnError.call(self);
                }
            };

            prototypeSplash.oldXhrSend.call(this, body);
        };

        _xhrSendIsPatched = true;
    }

```

(this code is likely broken, but you can get the idea).

To get stack traces (i.e. line numbers of caller code) you can use https://github.com/stacktracejs/stack-generator library.

To load stack-generator library and custom XHR interception code use http://splash.readthedocs.org/en/stable/scripting-ref.html#splash-autoload.

**Comment by ohade** [comment]
I will take a look at what you mentioned, 

> Yes, just pass 'har=1' option to render.json.
> 
> By the way, try going to http://:8050/ - it will show an UI where you can enter an URL to render. After 
> submitting it'll show a screenshot and a chart similar to "network" tab in browsers; for the chart it uses 
> either splash:har() method (if Lua is enabled) or 'har=1' option for render.json (if Lua is disabled).

I dont need to chart the js to the specific request, just to get the name of the js.

I must admit that i dont feel to comfterball fideling with the source code of the splash. 
I love the work that has been done with the docker framework and the provided API.

**Comment by kmike** [comment]
> I dont need to chart the js to the specific request, just to get the name of the js.

Initially I thought you need the name of a requested JS file, not of a file which initiated XHR request. You can get the former using splash:har(), but not the latter.

**Comment by kmike** [comment]
> I must admit that i dont feel to comfterball fideling with the source code of the splash.

All options mentioned don't require one to touch Splash source code; by `override XMLHttpRequest.prototype.send` I meant you can monkey-patch JS object by using a custom JS script sent to Splash HTTP API.

> I love the work that has been done with the docker framework and the provided API.

Thank you, that's great!

**Comment by ohade** [comment]
<img width="596" alt="screen shot 2015-09-29 at 7 23 04 pm" src="https://cloud.githubusercontent.com/assets/13435149/10172576/b95ca270-66e8-11e5-938f-f721141d7ff0.png">

**Comment by ohade** [comment]
I looked at 
> By the way, try going to http://:8050/

and the har=1
It looks exactly what i needed! thanks!

**Comment by kargaranamir** [comment]
@ohade 
Hi,
I need the same things as you. 
I want to have js loaded links for checking them that they are third party tracker or not?
What is the best work for this?

**Comment by ohade** [comment]
@kargaranamir don't have any real way to do that, 
Checkout ghostly, it's a chrome extension that has its own db that detects this, but I couldn't find a way to get it from it. so I can automate.

**Comment by JavierRuano** [comment]
https://splash.readthedocs.io/en/stable/scripting-ref.html#splash-har

**Comment by lmk07** [comment]
![20200813_233133](https://user-images.githubusercontent.com/66107540/90171063-8c901900-ddbe-11ea-8434-8b5b64e25c1e.png)

I need to get the column, titled "name" , status, type, size, time using javascript. Anyone have idea about get those. Thanks in advance.
