### ISSUE TITLE
Is is possible to take a screen shot with splash?

### ISSUE THREAD

**Issue by iwxfer** [scrapinghub/splash#310]
I would like to take a screen shot to a webste. Is it possible with this piece of awesome code?

**Comment by kmike** [comment]
Hey @iwxfer,

Yes, sure - it started as a screenshoting server. Check [render.png](http://splash.readthedocs.org/en/stable/api.html#render-png), [render.jpeg](http://splash.readthedocs.org/en/stable/api.html#render-jpeg) or [render.json](http://splash.readthedocs.org/en/stable/api.html#render-json) endpoints, or [Splash Scripts](http://splash.readthedocs.org/en/stable/scripting-tutorial.html#scripting-tutorial) + splash:png() or splash:jpeg() methods if you need something more custom.
