### ISSUE TITLE
How can I send cookies?

### ISSUE THREAD

**Issue by iwxfer** [scrapinghub/splash#312]
I would like to add special cookies to my request, I already added in the call to the server but it seems it just work for the splash server and seems that splash doesn't send the request with the cookies:

```
curl  -b "NOD=oSffF#DS"  "http://localhost:8050/render.png?url=https://www.asd.com" > fer.png
```

**Comment by kmike** [comment]
If you use render.png then [headers](http://splash.readthedocs.org/en/latest/api.html#arg-headers) argument may help. For Splash Scripts you can use [splash:add_cookie()](http://splash.readthedocs.org/en/latest/scripting-ref.html#splash-add-cookie).
