### ISSUE TITLE
http basic authentication

### ISSUE THREAD

**Issue by njordr** [scrapinghub/splash#334]
Hi.

I cannot find a way to handle htttp basic auth with splash. Can you help me?

Regards,
Giovanni

**Comment by kmike** [comment]
Hey Giovanni,

I think the way to go is to use a proxy in front of Splash - it is a good idea even if you don't need HTTP Basic Auth. See http://splash.readthedocs.org/en/stable/faq.html#splash-instance-is-overloaded and https://github.com/TeamHG-Memex/aquarium

**Comment by njordr** [comment]
my fault, but how can I use http auth with a proxy?

**Comment by kmike** [comment]
Sorry, it seems I didn't understand your question. Do you want to limit access to Splash using HTTP Basic Auth or do you have a web site to crawl which uses HTTP Basic Auth?

**Comment by njordr** [comment]
I have a site to crawl which uses HTTP Basic Auth :)

But thanks for aquarius, great tool!

**Comment by kmike** [comment]
There is no direct support for HTTP Basic Auth, but as from client point of view it is just sending a HTTP header you can use [headers](http://splash.readthedocs.org/en/stable/api.html#arg-headers) argument, 'headers' argument of [splash:go](http://splash.readthedocs.org/en/stable/scripting-ref.html#splash-go) or [splash:set_custom_headers](http://splash.readthedocs.org/en/stable/scripting-ref.html#splash-set-custom-headers) method.

**Comment by njordr** [comment]
Thanks, I'll try

**Comment by njordr** [comment]
Mike, I use scrapyjs, but it accept headers parameter only for POST calls. Is there a way to always pass headers?

**Comment by kmike** [comment]
@njordr could you please give an example? `headers` must be passed with a `application/json` POST request to Splash (and this is what scrapyjs should do internally), but it doesn't mean request Splash will be sending to a remote web site is POST - it is GET by default

**Comment by kmike** [comment]
HTTP Basic Auth looks like a common case, I think adding built-in helpers for it is a good idea.

**Comment by njordr** [comment]
This call
yield scrapy.Request(url, self.parse, headers=headers, meta={
                'splash': {
                    #'endpoint': 'render.html',
                    'args': {
                        'html': 1,
                        #'png': 1,
                        'har': 1,
                        'wait': 1,
                        #'width': 1024,
                        'render_all': 1,
                        'headers': json.dumps(headers)
                    },

                },
                'base_url_id': base_url_id,
                'base_url': base_url,
                'base_scheme': base_scheme,
                'url_to_parse': url
            })

gives me 
DEBUG: {"Host": "www.ftserussell.com", "Authorization": "Basic RlRTRS1SdXNzZWxsOkY3NTMtUnU1NTNsbA=="} (debug log for headers variable)
Retrying <POST http://127.0.0.1:8050/render.json> (failed 1 times): 400 Bad Request (error log)

**Comment by njordr** [comment]
I don't have to dump the variable: if I pass it as is, the auth works.

Thanks

**Comment by kmike** [comment]
:+1:
