### ISSUE TITLE
Accessing supplementary request/response objects

### ISSUE THREAD

**Issue by Deggor** [scrapinghub/splash#337]
Is it possible to access all of the data and metadata for additional requests/responses downloaded as part of a Splash request?  To be clear, if I grab a webpage (say github.com), many additional requests are made as part of that fetch (such as background images and extra CSS/JS files), with these images and texts coming back as additional responses.  The requests and responses made for these supplementary items is what I'm after.

Currently, as a work-around, I can use the HAR results to get most of the Request/Response metadata, such as headers.  However, there doesn't seem to be any method of actually retrieving the core data returned for these responses.

*Edit: This is a question, however I cannot assign the Question label to this issue.  My apologies.*

**Comment by kmike** [comment]
Hi @Deggor,

No, unfortunately this is not possible yet. There is some info in [gitter](https://gitter.im/scrapinghub/splash) chat logs; it is kind of tricky to implement. @AlexIzydorczyk had a hack-ish implementation in his branch.

A good point about labels, they can be assigned only by repo owners. We should change the README, sorry for the confusion.

**Comment by Deggor** [comment]
So, from preliminary review, it looks like proxy/wrapper is needed for the `QNetworkReply` to hold the data usually discarded after being consumed by the `QWebPage`.  The repo link has been down since before August 21.  For you and @AlexIzydorczyk, I found an archive link to the discussed repo on [archive.org](https://web.archive.org/web/20130603121859/http://gitorious.org/qtwebkit/performance/blobs/master/host-tools/mirror/main.cpp).  Looks like I've got a lot of review, research, and busy weekends ahead.  Thanks for the reply, @kmike!

**Comment by kmike** [comment]
Yeah, it looks like it, we need a QNetworkReply wrapper. Maybe we can steal something from https://github.com/lorien/wkit/blob/master/wkit/reply.py.

**Comment by kmike** [comment]
This will be possible in upcoming Splash 2.2: there is now [splash.response_enabled](http://splash.readthedocs.io/en/latest/scripting-ref.html#splash-response-body-enabled) flag, [request:enable_response_body](http://splash.readthedocs.io/en/latest/scripting-request-object.html#splash-request-enable-response-body) method and [response_body](http://splash.readthedocs.io/en/latest/api.html#arg-response-body) HTTP argument.
