### ISSUE TITLE
[Doc] Sample code for `splash:wait` seems incorrect

### ISSUE THREAD

**Issue by starrify** [scrapinghub/splash#340]
I don't think this piece of sample code for `splash:wait` would work as expected:

```lua
    function wait_restarting_on_redirects(splash, time, max_redirects)
        local redirects_remaining = max_redirects
        while redirects_remaining do
            local ok, reason = self:wait(time)
            if reason ~= 'redirect' then
                return ok, reason
            end
            redirects_remaining = redirects_remaining - 1
        end
        error("Too many redirects")
    end
```

Source: https://github.com/scrapinghub/splash/commit/71dcdfe6666b9e4720e6098da74aad6c3163f12b#diff-0e110f37aea02fc3b33f5c2e676526b9R87

To be specific, this line:

    while redirects_remaining do

shall be:

    while redirects_remaining > 0 do

Reason: In `lua` the only false boolean values are `false` and `nil`. All other values including `0` and `''` would be regarded as true.

**Comment by kmike** [comment]
Fixed by https://github.com/scrapinghub/splash/pull/341
