### ISSUE TITLE
Include or inject external js file into page context

### ISSUE THREAD

**Issue by awakmu** [scrapinghub/splash#342]
Hi,

Can I inject or include external JS library into page context, using splash?

Regards,
Awakmu

**Comment by Youwotma** [comment]
Hi @awakmu 
Yes you can, the way you do it depends on how are you using splash:
Check out this documentation articles:
For the `/render.*` endpoints, check out [Executing custom Javascript code within page context](http://splash.readthedocs.org/en/latest/api.html#executing-custom-javascript-code-within-page-context).
For the `/execute` endpoint, check out
[splash:evaljs()](http://splash.readthedocs.org/en/latest/scripting-ref.html#splash-evaljs) and [splash:runjs()](http://splash.readthedocs.org/en/latest/scripting-ref.html#splash-runjs)
