### ISSUE TITLE
evaljs with jquery causes Splash to crash

### ISSUE THREAD

**Issue by pawelmhm** [scrapinghub/splash#343]
I have following innocently looking Lua script using evaljs:

```lua
function main(splash)
    splash:go("http://www.ica.se/handla/ica-nara-ovrells-id_01739/")
    splash:set_viewport_full()
    splash:wait(1)
    splash:evaljs("$('#search').val('cola');")
    splash:evaljs("e = $.Event('keypress'); e.which = 13; $('#search').trigger(e)")
    splash:wait(1)
    return splash:jpeg()
end
```

this crashes Splash every time I run it. I found warning in docs about eval js

> Don’t use splash:evaljs when the result is not needed - it is inefficient and could lead to problems; use splash:runjs instead. For example, the following innocent-looking code (using jQuery) may fail A gotcha is that to allow chaining jQuery $ function returns a huge object, splash:evaljs tries to serialize it and convert to Lua. It is a waste of resources, and it could trigger internal protection measures; splash:runjs doesn’t have this problem.

it's nice we warn users about evaljs but I think we should do something about it, it seems bad that evaljs can actually crash your splash server. What internal protection measure do we have now? Is there a way to improve those protection measures to avoid problem like this?

**Comment by kmike** [comment]
There is protection against converting deep Python objects to Lua (https://github.com/scrapinghub/splash/blob/master/splash/qtutils.py#L190). Previously (in qt4?) it was enough to make Splash raise an error on evaljs instead of crashing.
