### ISSUE TITLE
Shall splash support HTTP status 308 now?

### ISSUE THREAD

**Issue by starrify** [scrapinghub/splash#351]
I've just tested with both the image scrapinghub/splash on docker.io and also the latest commit in the repository, and it's confirmed that HTTP status 308 has not yet been supported by splash.

The newest RFC defining HTTP status 308 is [RFC7538](https://tools.ietf.org/html/rfc7538) which is yet not an Internet standard (it's a proposed standard now).  
However, at this very moment status 308 has been already supported by many products (e.g. Google Chrome 48.0.2564.22 dev and curl 7.45.0). You can test it with http://httpstat.us/308

Shall splash support it, too?

**Comment by kmike** [comment]
Yeah, that'd be nice. We may depend on Qt to fully support it, I'm not sure, but some cases may be fixed in Splash.

**Comment by lucywang000** [comment]
Looks like we could handle it in our pyqt code, here is a c++ example: https://stackoverflow.com/questions/46100802/qnetworkaccessmanager-doesnt-handle-http-status-code-308

**Comment by lucywang000** [comment]
Seems qt has already fixed it in https://bugreports.qt.io/browse/QTBUG-63075. 

Splash 3.3.1 doesn't handle HTTP 308:

![3 3 1-308-not-ok](https://user-images.githubusercontent.com/30067222/65574479-32b51380-dfa0-11e9-87df-a9e1cfc0ea3b.png)


but 3.4b1 could handle it:

![3 4b1-308-ok](https://user-images.githubusercontent.com/30067222/65574503-3f396c00-dfa0-11e9-8720-2b7bb0b3e382.png)

**Comment by kmike** [comment]
Thanks @lucywang000 for checking it! I'm closing it, because it is fixed in master.
