### ISSUE TITLE
splash-jupyter not work

### ISSUE THREAD

**Issue by genius001** [scrapinghub/splash#361]
## My issues

UPDATE: 2016/01/15
     I have test from on linode and Vmware use Ubuntu 14.04.3 LTS. both failed :(

Today I installed Ubuntu 14.04.3 LTS inside VMware, then installed splash and splash-jupyter according to the steps I listed below.

However, after all the installation, I still failed to use splash-jupyter.

The problem is:
I saw through this [video of splash-jupyter](https://vimeo.com/129244053) after start splash-jupyter,
When start IPython notebook in browser and create a new  Splash notebook using "New" button, and typing the splash:go('http://www.example.com'), it will automatically pop up a new web window for inspection.

But when I perform splash:go('http://www.example.com'), the browser title showing the status:'(Busy)Untitled1'. and no result at all. and there is no new window pop up for inspection.

## Install splash follow by the step
     1. New Ubuntu 14.04.3 LTS at linode.com.
     2. $ apt-get update && apt-get upgrade
     3. $ git clone https://github.com/scrapinghub/splash/ 
     4. $ cd ~/splash/dockerfiles/splash/
     5. $ ./provision.sh  prepare_install  install_msfonts  install_builddeps  install_deps  install_extra_fonts  install_pyqt5 install_python_deps
     6. $ pip3 install -r requirements.txt
     7. $ python3 -m splash.server

End (success): I can successfully using splash.server so far.

## Install splash-jupyter follow by the step
     1. $ pip3 install 'ipython[notebook] >= 4.0.0, < 5.0'
     2. $ python3 -m splash.kernel install
     3. $ ipython3 notebook --no-browser --port=8888 --ip=*

End(failed): I cannot get response from splash:go('http://www.example.com') and no "Live Webkit window with web inspector".

NOTE :  I manually change 'python' to 'python3' in file of [kernels/splash/kernel.json](https://github.com/scrapinghub/splash/blob/master/splash/kernel/kernels/splash/kernel.json) . 

# The figure is a demonstration

![6f03cc26-b7e2-11e5-94f3-a43b416887f7](https://cloud.githubusercontent.com/assets/5621825/12250475/17f69686-b902-11e5-8c31-2983e29c9b5f.png)

What's my wrong? 
How to solve it? @kmike @Youwotma @pawelmhm

Thank you very much.

**Comment by pawelmhm** [comment]
is it just jupyter down for you? can you start splash and it listens ok on http://localhost:8050?

**Comment by genius001** [comment]
dear @pawelmhm 

I installed jupyter use this command: $ pip3 install 'ipython[notebook] >= 4.0.0, < 5.0'.
http://localhost:8050? work well. 

All the thing working well except splash-jupyter.
Can you give me a Installation instructions about splash-jupyter?
I always failed to install it according [:ref:'kernel.rst'](https://github.com/scrapinghub/splash/blob/master/docs/kernel.rst)


Another problem,  Will be must use desktop ubuntu if I want to use feature "Live Webkit window with web inspector"?

I would really appreciate any guidance here.
Thank you.

**Comment by kmike** [comment]
Hey @genius001, I've tried to follow the steps again. It seems I made a few assumptions when writing these docs:

1. You're using a Python 3 virtualenv. That's why the command is `python`, not `python3`.
2. Splash is installed in this virtualenv.

Note you can run `python3 -m splash.server` from source checkout without installing splash, but Splash Notebook will fail in this case - it shows the following warning:

> WARNING:root:kernel fbd60658-44a4-4332-9e17-d51b20821b05 restarted
/Users/kmike/envs/py3-splash/bin/python: Error while finding spec for 'splash.kernel' (<class 'ImportError'>: No module named 'splash')

Could you try installing Splash to your current environment (`pip install -e .` from source checkout)?

**Comment by kmike** [comment]
When installed, Splash-Jupyter works for me. Is there some output in a terminal where you've started the notebook? Unfortunately Splash logs are discarded when you use Splash-Jupyter, but it is possible to get them stored to a file by uncomenting the following lines: https://github.com/scrapinghub/splash/blob/master/splash/kernel/kernel.py#L43 - if you still have problems could you please try doing that and showing what's in the log?

**Comment by genius001** [comment]
Hey @kmike 

Thank you for your reply.

I've tried to follow you advice.  I've use pyenv/virtualenv as the virtual environment.
Splash-Jupyter also failed in this time.

I uncommit the following lines:
(https://github.com/scrapinghub/splash/blob/master/splash/kernel/kernel.py#L43),

The output log in kernel.log is:
> 2016-01-22 01:13:21.932138 [-]   File "/home/xiaoming/.pyenv/versions/py3-> splash/lib/python3.4/site-packages/IPython/external/qt_loaders.py", line 296, in load_qt
> 2016-01-22 01:13:21.932275 [-]     api_options))
> 2016-01-22 01:13:21.932621 [-] ImportError:
> 2016-01-22 01:13:21.932802 [-]     Could not load requested Qt binding. Please ensure that
> 2016-01-22 01:13:21.932946 [-]     PyQt4 >= 4.7, PyQt5 or PySide >= 1.0.3 is available,
> 2016-01-22 01:13:21.933635 [-]     and only one is imported per session.
> 2016-01-22 01:13:21.933803 [-]
> 2016-01-22 01:13:21.933947 [-]     Currently-imported Qt library:   'pyqt5'
> 2016-01-22 01:13:21.934089 [-]     PyQt4 installed:                 False
> 2016-01-22 01:13:21.934415 [-]     PyQt5 installed:                 False
> 2016-01-22 01:13:21.934625 [-]     PySide >= 1.0.3 installed:       False
> 2016-01-22 01:13:21.934824 [-]     Tried to load:                   ['pyqt5']

Seems this is an bug of ipython, see this(https://github.com/ipython/ipython/issues/8411).
But I don't know how to fix it with Splash-Jupyter.
I think Splash-Jupyter will be installed successfully if I solve this problem.

The other problem was I cannot install packet libgl1-mesa-dev-lts-utopic on ubuntu 14.04.03. 
The error was:
> The following packages have unmet dependencies:
>  libgl1-mesa-dev-lts-utopic : Depends: mesa-common-dev-lts-utopic (= 10.3.2-> > 0ubuntu1~trusty2) but it is not going to be installed
                              Depends: libgl1-mesa-glx-lts-utopic (= 10.3.2-0ubuntu1~trusty2) but it is > not going to be installed
> E: Unable to correct problems, you have held broken packages.

So I use 'libgl1-mesa-dev libglu1-mesa-dev mesa-common-dev' instead of 'libgl1-mesa-dev-lts-utopic'. I don't know whether appropriate.

**Comment by kmike** [comment]
Hey @genius001,

Thanks for debugging it. I'm not sure why is IPython trying to import PyQt5 - it should be used by Qt console, but we're using web notebook. Is this error fatal, i.e. IPython doesn't even load?

I'm looking into `libgl1-mesa-glx-lts-utopic` issue now because it broke Travis build. It happened today - a build from 2 days old was passing, so likely some software update caused the issue.

**Comment by kmike** [comment]
@genius001 yes, using `libgl1-mesa-dev libglu1-mesa-dev mesa-common-dev` is fine. I've added the same dependencies to provision script.

**Comment by genius001** [comment]
@kmike 
> Thanks for debugging it. I'm not sure why is IPython trying to import PyQt5 - it should be used > by Qt console, but we're using web notebook. Is this error fatal, i.e. IPython doesn't even load?

IPython can be load and start. The problem is:
1. Splash Scripts functions not work, i.e splash:go splash:http_get splash:http_post.
2. No Webkit window popup. 

In this case, a few days ago, I used tcpdump tool monitor the tcp data:
There was not send request to the destination at all when using web notebook run script function, i.e splash:go splash:http_get spash:http_post.

I do not know the cause of the error problem.
I was downloaded the ubuntu 64-bit image from [http://www.ubuntu.com/download/desktop](http://www.ubuntu.com/download/desktop)
And installed it on VMware® Workstation 12 Pro

I think this error would be reproduced using the latest ubuntu 64-bit if my installation is not wrong.

# The figure is a demonstration
![ubuntu14 04-2016-01-22-20-24-11](https://cloud.githubusercontent.com/assets/5621825/12510723/f0263a10-c146-11e5-839f-126ca345ada9.png)

Is there anything wrong by viewing this figure?

**Comment by genius001** [comment]
Hey @kmike 

Splash-Jupyter scripts functions now work(i.e splash:go splash:http_get).
But no webkit browser window. and there are some error.
I think these error occured due to my improper installation.
I installed Splash/Splash-Jupyter follow this (https://github.com/genius001/splash/blob/patch-1/docs/install-manual.txt)

The figure is a demonstration of my Splash:
![ubuntu14 04 splash server-2016-01-26-10-54-06](https://cloud.githubusercontent.com/assets/5621825/12581478/cff4aac8-c471-11e5-9134-2bdbf783b130.png)
![ubuntu14 04 splash server-2016-01-26-16-07-25](https://cloud.githubusercontent.com/assets/5621825/12581481/d1109656-c471-11e5-8937-96325fb251c3.png)
