### ISSUE TITLE
Splash can't load page

### ISSUE THREAD

**Issue by bfabri** [scrapinghub/splash#362]
I've been trying to get html page using the url http://tracker.ad5track.com/tracker/click?acc=93a167918e12d652fd9145cd4ddc4ce9&i=54d90be6dd7ab23e2aa27410&o=55a6b91e9c3238c7d13da4b9&redirect_url=http%3A%2F%2Fwww.americanas.com.br%2Fproduto%2F9141033%2Fsmartphone-lg-leon-tv-h326-desbloqueado-azul-preto%3Fopn%3DYYNKZU. 

However, splash aways returns 

```
<html><head></head><body></body></html> 
```

I can't figure out whats happening. My guess is that redirect is causing this problem.

**Comment by kmike** [comment]
Hey @bfabri - sorry, I can't reproduce it - for me this URL returns 403 after a redirect both in Splash and in a browser. Could you please post an example - how are you using splash to render this URL?
