### ISSUE TITLE
Splash won't load scripts with absolute paths

### ISSUE THREAD

**Issue by protechig** [scrapinghub/splash#363]
Hello,

I am having an issue loading scripts in splash that use absolute paths. For example:

`<script type="text/javascript" charset="utf-8" async="" data-requirecontext="_" data-requiremodule="/js/initialize.min.strip.js.gz?date=2016-01-11" src="/js/initialize.min.strip.js.gz?date=2016-01-11"></script>`

will not load, I just get a 404 error becasue it's trying to access the script at the localhost IP and not the original site's IP. 

I tried setting `baseurl` to the original site as well, but that didn't fix the issue.

Steps to replicate:

1. Launch Splash:
2. go to `/render.html?url=http://www.petcoach.com` or `/render.html?url=https://xyzyxyzy.xyz`

Any idea why this is happening or how I can fix it?

Thanks,
Zach

**Comment by protechig** [comment]
As an update, I created a daemonized docker container on a Digital Ocean droplet:

From what I can tell, splash is completely ignoring the `baseurl` parameter both using the HTTP API and Lua:

http://104.131.79.169:8050/render.html?url=http://www.petcoach.co&baseurl=http://www.petcoach.co

I would _really_ appreciate any guidance here @kmike :)

**Comment by Youwotma** [comment]
Hi @protechig :)

When you make a request to /render.html endpoint splash runs the JavaScript in the page and returns the HTML representation of the DOM after executing the JavaScript. If you try to open the result in your browser, your browser will try to fetch the resources from the wrong location and run JavaScript again in your browser.

If you want to inspect how the page looks inside of splash it's better to use the `render.png` endpoint, `render.html` will return processed HTML that is suitable for extracting data, but not for being loaded in a browser.

So what's happening here is that splash loads and executes the JavaScript file well, then returns the result to your browser that will try to run again (and fail).

Hope this makes sense! Maybe we should add a note to the documentation about trying to open `/render.html` in a browser.

**Comment by protechig** [comment]
Hello @Youwotma 

I completely understand what you're saying. I thought the exact same thing, which is why I tried it in Postman, so I can just view the direct response, but it isn't giving me rendered JavaScript. Also, when I do render.png, this is what I get:

http://104.131.79.169:8050/render.png?url=http://www.petcoach.com&baseurl=http://www.petcoach.co&height=800&width=1280&render_all=1&wait=5

It just renders a blank PNG. Why would this be happening?

**Comment by Youwotma** [comment]
Hi,

Seems like a problem with the page, it needs localStorage to work. If you enable local storage in splash by disabling private mode (`--disable-private-mode`) it should work (Note: I have only tested in splash master)

David

**Comment by protechig** [comment]
Hello @Youwotma It does indeed work on master when passed in through a Lua script. Do you know if it possible to do this on version 1.8? As I would like to use this in production - i'd rather not use a development version if I can avoid it.

Thank you so much for your help with this!
-Zach

**Comment by Youwotma** [comment]
Hi @protechig, in splash 1.8 you can try using a localStorage shim like I explain in https://github.com/scrapinghub/splash/issues/221#issuecomment-132908630 and any other shims you might need (you might need es5 shim too)
