### ISSUE TITLE
The latest version of the splash-jupyter seems has problem.

### ISSUE THREAD

**Issue by genius001** [scrapinghub/splash#364]
Ubuntu: 14.04.3 LTS
Splash: 1.8

Problem:
1. Splash-jupyter use "manual way" has installed, but not working. see [#361](https://github.com/scrapinghub/splash/issues/361)
2. the latest version of Splash-jupyter use docker build failed. see [splash-jupyter build from docker](https://hub.docker.com/r/scrapinghub/splash-jupyter/builds/)

Even if use "manual way" complete installation, The Splash-jupyter still not working.
see [#361](https://github.com/scrapinghub/splash/issues/361).

Any suggestion?  Thank you very much.

**Comment by kmike** [comment]
Thanks for the heads up, I'm checking the Docker issue now.
