### ISSUE TITLE
The latest docker image of Splash-Jupyter(master) seems has problem

### ISSUE THREAD

**Issue by genius001** [scrapinghub/splash#371]
I'm not sure.

Reference this(https://hub.docker.com/r/scrapinghub/splash-jupyter/builds/)
The latest image build status shows 'success', but can not work.
The program will be crash, and output the error info like this:
> Traceback (most recent call last):
>   File "/usr/lib/python2.7/runpy.py", line 162, in _run_module_as_main
>     "__main__", fname, loader, pkg_name)
>   File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
>     exec code in run_globals
>   File "/app/splash/kernel/__main__.py", line 14, in <module>
>     from .kernel import start, install
>   File "/app/splash/kernel/kernel.py", line 6, in <module>
>     import lupa
>  ImportError: No module named lupa

I'm not sure, would some body check it?
Thank you very much.

**Comment by kmike** [comment]
Ouch, that's bad - it looks like splash-jupyter docker image never worked after the switch to Python 3. I think I've fixed it in https://github.com/scrapinghub/splash/commit/8c883b5babd76eb7cd83304e4be1aa59a9ddacdd, but can't check that because Sourceforge downloads are down, and so it is not possible to build our docker images.

**Comment by genius001** [comment]
Hey @kmike 

Until now, I have not installed Splash-Jupyter successfully.
I do not know where the problem.
I use clean and fresh ubuntu(14.04.03 64bit ).
I want to provide you the complete steps of I install Splash and Splash-Jupyter.
Can you help me to check about it Where I mistake?

Thank you.

**Comment by kmike** [comment]
Hey @genius001,

I finally managed to reproduce it, thanks for your helpful bug reports. Could you check it now (or maybe in a hour, to make sure Docker images are updated)?

**Comment by kmike** [comment]
The provision script should be fixed.

**Comment by genius001** [comment]
Hey @kmike 

I had check it, it is working now.
Though there is a little problem, it does not affect to use.

![ubuntu14 04-2016-01-28-08-20-24](https://cloud.githubusercontent.com/assets/5621825/12633590/ef31a520-c5ad-11e5-862c-e972f5b4a7e2.png)
