### ISSUE TITLE
error when install splash manual way with ubuntu

### ISSUE THREAD

**Issue by YCchou** [scrapinghub/splash#372]
my command is ` sudo ./provision.sh  install_pyqt5`

and error is 
```
Usage: python configure.py [opts] [name=value] [name+=value]

configure.py: error: '/opt/qt55/bin/qmake' is not an executable
Command failed (exitcode: 2), exiting...
```

any ideas? Thanks

**Comment by YCchou** [comment]
install system deps and problem sloved

sorry to bother

**Comment by genius001** [comment]
Hey @YCchou 

Did you installed Splash/Splash-Jupyter success?

**Comment by genius001** [comment]
@YCchou 

晕，哈哈，刚刚要和你探讨一下，github就挂了。
你使用virtualenv安装Splash吗？
另外 Splash-Jupyter 这个工具很强大，可是我一直安装出现问题。
你看看这个视频，就知道了。https://vimeo.com/129249475

**Comment by YCchou** [comment]
你可以把你的错误代码贴出来，不知道你是什么系统，我用ubuntu 和 os x都成功安装了  ubuntu 手动安装要麻烦一些  不过splash提供了安装脚本

jupyter看起来很炫，可惜不会lua 。。

@genius001

**Comment by genius001** [comment]
我也手动安装成功了 Splash，但是没有安装成功Splash-Jupyter。
我把错误信息发在这里了(https://github.com/scrapinghub/splash/issues/361)。

Jupyter不需要懂多少lua, 只需要按照这个弄就可以。(http://splash.readthedocs.org/en/stable/scripting-ref.html)

**Comment by YCchou** [comment]
没什么头绪，没能帮到你，sorry
@genius001

**Comment by genius001** [comment]
没关系。

@YCchou
