### ISSUE TITLE
crawl new page which produced by javascript with scrapyjs

### ISSUE THREAD

**Issue by YCchou** [scrapinghub/splash#374]
my problem is http://stackoverflow.com/questions/35052999/using-scrapyjs-crawl-onclick-pages-by-splash

could someone help me figure out this?

thanks!

**Comment by genius001** [comment]
我看了你的代码，我认为 Splash 和 你的代码都没有问题。
 render.html 返回的你所访问的网页。
你使用 Splash 调用js click() 估计也执行了。只不过它不从render.html返回url罢了。

至于如何取得 click()后的url，我没有去想。。。Splash应该可以做到。


@YCchou

**Comment by YCchou** [comment]
method click didn't work, i guess 
cause i wrote `document.title='hello world'` behind it but title didn't change

@genius001

**Comment by genius001** [comment]
朋友，问题解决了吗？

后来我想了想，你的代码不能获取window.localtion的url。
因为render.html这个api的作用是获得html源码。
js_source这个参数的作用是执行js代码。它只是模拟执行click()方法，所以不能获取到url。

还有个api是execute(http://splash.readthedocs.org/en/stable/api.html#execute), 我使用这个可以获得url。

比如：

splash:go("http://www.your-domain.com/a.html")
splash:html()
splash:runjs('document.getElementsByTagName("span")[0].click()')
splash:wait(2)
splash:evaljs("document.URL")


@YCchou

**Comment by YCchou** [comment]
没解决呢，头疼ing。

你说的我测试一下，多谢啦！  有机会可以多交流关于scrapy的内容。

@genius001

**Comment by genius001** [comment]
不好意思呀。我没有用过scrapy。
这几天一直装不上Splash-Jupyter。
如果能完整的安装上Splash-Jupyter，可以极大的方便调试。

另外，你在ubuntu上手动安装Splash使用virtualenv插件了吗？
我一开始安装的时候，没有使用virtualenv插件，后来觉得还是用它比较合理。
但是就是一直不能完整的安装好Splash-Jupyter。

这是我自己的安装步骤。(https://github.com/genius001/splash/blob/patch-1/docs/install-manual.txt)我使用的是全新的ubuntu安装的。但是一直有问题。

@YCchou

**Comment by YCchou** [comment]
splash 应该是用python3写的  既然是python3  就不需要用virtualenv吧  python3自带了 venv

我建议你不适用virtualenv试一下能否正常安装，再看看python3的venv可否正常工作。

我有空帮你试一下： ）

**Comment by genius001** [comment]
好的，我自己在测试一下venv。

另外你可以使用 http://your-ip:8050/ 来调试你的代码啊。

**Comment by YCchou** [comment]
嗯，才学会的：）

@genius001

**Comment by genius001** [comment]
慢慢你就感觉到Splash-Jupyter是个神器。
你成功安装Splash-Jupyter，告诉我一声啊。我捣腾好长时间了，一直没用装好。
谢谢了

@YCchou

**Comment by YCchou** [comment]
客气啦，我晚些时候试试手动安装jupyter
@genius001

**Comment by genius001** [comment]
朋友，安装Splash-Jupyter了吗？按照说明的安装的话，只有两三步。

我安装Splash-Jupyter，倒是能用，但是弹不出内置浏览器。
如果安装正确的话，在浏览器进行开发的时候，会弹出另外一个内置浏览器让调试用。

 
@YCchou

**Comment by YCchou** [comment]
我pull 不下来 docker 镜像，我这里是os x   docker 安装的。

docker 镜像被墙了

晚些才能找一台ubuntu的电脑试试，我只有一台阿里云的ubuntu主机 没有图形界面。。。

@genius001

**Comment by YCchou** [comment]
@genius001 

能否开启splash 的时候支持远程主机访问，你知道有这个功能和参数吗？

**Comment by genius001** [comment]
1. 使用docker的方法，则没法使用 “内置浏览器” 功能。

2. 你指的访问是什么意思？是在自己的电脑上调用远程的Splash吗？
只需执行: python -m splash.server
默认端口就是8050，http://your-ip:8050，就可以使用Splash的HTTP API了
不需要加什么参数吧。

@YCchou

**Comment by YCchou** [comment]
我现在试一下，在阿里云上安装一下。

@genius001

**Comment by genius001** [comment]
忘记个问题，
它这个“内置浏览器”调用的是你安装的PyQt5所生成的"浏览器"。
所有如果想使用 "内置浏览器" 的话，只能在安装了Splash的机器本地调用。
远程调用的话，肯定没法使用“内置浏览器”。
所有最好使用虚拟机安装桌面版本的ubuntu测试。

哈哈，忘记跟你说了。

@YCchou

**Comment by YCchou** [comment]
额，我说8888端口没办法访问，只有8050的页面可以  不过那个只有splash的

我主要接触的是scrapy爬虫，可能帮不到你了，sorry。

另外看了jupyter的视频，是模拟浏览器操作吗？  你是拿来做什么具体应用呢？

@genius001

**Comment by pawelmhm** [comment]
sorry but is there a way to speak english so that other users could benefit or help too :wink:

**Comment by genius001** [comment]
splash开启的是8050端口。
splash-jupyter开启的是8888端口。前提你的安装了splash-jupyter。
执行 ipython notebook --port=888 --ip=*  就可以在你的电脑使用notebook了。

我也弄爬虫，不过没有使用scrapy。就是自己写点简单的框架爬虫。

另外朋友，要不然把这个话题设为close吧。不然老外看见烦。 哈哈

@YCchou

**Comment by YCchou** [comment]
my fault, cause my english is very poor

will speak english here: )

@pawelmhm

**Comment by genius001** [comment]
朋友，我的邮箱是 code4code@gmail.com

搞定后，邮箱联系啊。邮箱交流吧。

@YCchou

**Comment by Q-SJ** [comment]
你的问题解决了吗，我也遇到了相似的问题，我需要获取按钮点击后的新页面，在运行之后
`local url = splash.args.url
            assert(splash:go(url))
            assert(splash:runjs("gotoPage(2)"))
            splash:wait(1)
            local txt = splash:evaljs("document.body.innerHTML")
            return txt`
这样拿到的txt还是原来的页面，要怎么办呢？

**Comment by genius001** [comment]
splash 正在 develop splash:mouse_click功能，到时候就简单了。

**Comment by Q-SJ** [comment]
好吧，那就先这样了。多谢多谢(o^^o)
