### ISSUE TITLE
add splash:scroll() method 

### ISSUE THREAD

**Issue by pawelmhm** [scrapinghub/splash#379]
QT web page has nice [scrolling functions](http://doc.qt.io/qt-5/qwebframe.html#scroll) they could be easily used in Splash via Lua.

**Comment by kmike** [comment]
what are advantages of these functions over `scroll = splash:jsfunc('window.scroll')`?

**Comment by pawelmhm** [comment]
good question. splash:scroll could be easier to use and more intuitive but you're right that this functionality is already available in Splash via splash:jsfunc(), so probably we can live with that
