### ISSUE TITLE
Flash objects are not displayed in Splash render

### ISSUE THREAD

**Issue by andresp99999** [scrapinghub/splash#38]
Try the following URL:

http://splash.scrapinghub.com:8050/render.png?wait=5&url=http://copyboost.com/ad-examples/good-flash-ad-examples/

The flash objects are not displayed, if you go to the URL directly you can see them: http://copyboost.com/ad-examples/good-flash-ad-examples/

We may want to add a setting to turn on/off flash support on Splash requests.

**Comment by shaylevi2** [comment]
Anything new?

**Comment by kmike** [comment]
@shaylevi2: not really. @andresp99999 had an implementation in a branch, but it is for ancient Splash version.

**Comment by kmike** [comment]
[splash.plugins_enabled](http://splash.readthedocs.io/en/latest/scripting-ref.html#splash-plugins-enabled) flag will be available in Splash 2.2; it allows to take screenshot of Flash content.
