### ISSUE TITLE
add splash:select() method

### ISSUE THREAD

**Issue by pawelmhm** [scrapinghub/splash#380]
qt web frame has nice selector interface, it could be used to select items in html page source from Lua script, web frame select method takes css selector as argument and returns web QWebElement: http://doc.qt.io/qt-5/qwebframe.html#findFirstElement this could be good alternative to running javascript scripts within Splash

**Comment by mike1808** [comment]
hi @pawelmhm 
I want to implement this functionality but I see the main problem here. What methods should the returned element have? 
Let assume we got our element ```element = splash:select('.container')``` What's next? What we'd be able to do with it? In #213 you've suggested to call `#png` method on it. What other methods do you think will be good to have?

**Comment by pawelmhm** [comment]
hey @mike1808 this issue has become part of Google Summer of Code proposal http://gsoc2016.scrapinghub.com/ideas/#splash-ideas the idea is to have helpers similar to the ones provided by Scrapy, Selenium, PhantomJS/CasperJS, I think the call for applications is still open there. 

>  I assume that it should have some basic utils methods like click, scrollTo, getHtml, etc.

yes I was thinking about something like this, click(), hover(), scroll() would be all very useful things to have IMO.

Implementation could either use QT API calls or it could rely on JavaScript executed in QT. Second option may be better as it doesn't tie us to any specific QT api (we may change engine implementation #349 so api calls could change too). 

Currently there is a way to define your own helpers in javascript and convert them to lua callable via splash jsfunc, so those helpers could perhaps work in some similar way.

**Comment by genius001** [comment]
This link was broken

[http://doc.qt.io/qt-5/qwebframe.html#findFirstElement](url)

**Comment by mike1808** [comment]
@genius001 QWebFrame was removed from Qt5, the working link is [QWebFrame::findFirstElement](http://doc.qt.io/qt-4.8/qwebframe.html#findFirstElement)

**Comment by genius001** [comment]
@mike1808 

Have you developing functionality splash:select()?

I also need a feature similar splash:select() .
Referer https://github.com/scrapinghub/splash/issues/433

**Comment by mike1808** [comment]
@genius001 I've only started to work on it.

**Comment by genius001** [comment]
Excellent. @mike1808 

I will try to implement some functionality e.g. splash:mouse_move splash:move_click splash:move_hover.

**Comment by kmike** [comment]
Fixed in #490, merged in #531.
