### ISSUE TITLE
Splash click elements can not return the correct URL source

### ISSUE THREAD

**Issue by xiaowenjie6434** [scrapinghub/splash#382]
This is code （scrapyjs）：

 # -*-coding:UTF-8-*- 
import json
import scrapy
from scrapy.linkextractors import LinkExtractor
from pachong.items import PachongItem
from scrapy.loader.processors import MapCompose, Join
from scrapy.loader import ItemLoader

class DmozSpider(scrapy.Spider):
    name = "dmoz3"
    allowed_domains = ["dmoz.org"]
    start_urls = ['http://www.qq.com/']
    

    def parse(self, response):
	script = """
        function main(splash)
            splash:autoload("http://code.jquery.com/jquery-2.2.0.min.js")
            assert(splash:go('http://www.baidu.com/'))
	    splash:runjs("$('a:first').click()")
            splash:wait(1.5)
	    return splash:html()
        end
        """
        yield scrapy.Request('http://www.baidu.com', self.parse_link, meta={
            'splash': {
                'args': {'lua_source': script},
                'endpoint': 'execute',
            }
        },dont_filter=True)
    def parse_link(self, response):
        l = ItemLoader(item=PachongItem(), response=response)  
        l.add_value('body',response.body)
        return l.load_item()

In the implementation of the scrapy crawl dmoz3 -o test.xml , is still the www.baidu.com home source, click on the first a element is not executed, or I use the method is wrong?

Is there a case for the splash to implement the click elements?

**Comment by xiaowenjie6434** [comment]
For example, using innerText, I can get to the data

**Comment by Youwotma** [comment]
Hi @xiaowenjie6434,

The jQuery click() method won't actually perform the default action of a click, to do that you can use this snippet:
```
function click_element(element){
    var clientRect = element.getClientRects()[0];
    var clientX = clientRect.left + clientRect.width / 2;
    var clientY = clientRect.top + clientRect.height / 2;
    var ev = document.createEvent("MouseEvent");
    ev.initMouseEvent('click', true, true, window, 0,
                      clientX, clientY, clientX, clientY,
                      false, false, false, false, 0, null);
    element.dispatchEvent(ev);
}
```

Note that the first link in `baidu.com` home page goes to `baidu.com` home page too, to check if it works you will need to use a different selector:
```
click_element(document.querySelector('a[href*="hao"]'));
```

David

**Comment by xiaowenjie6434** [comment]
run this code is error 400

**Comment by Youwotma** [comment]
Hi @xiaowenjie6434 

Run what code? do you have the complete lua script that's causing you problems?
