### ISSUE TITLE
[Question] - why not use PhantomJS as the headless browser?

### ISSUE THREAD

**Issue by RealHacker** [scrapinghub/splash#384]
It looks splash uses Qt's webview to render the web page and execute js. I am wondering if you have considered using phantomjs for that task, and if so, why not choose it?

**Comment by kmike** [comment]
Hey @RealHacker,

PhantomJS also uses Qt's webview to render pages (it seems they forked it though, so they have some fixes which are not upstream, but don't have some fixes which are upstream); it is much easier to integrate qt webview directly into event loop than to run phantomjs in your own event loop.

**Comment by sardok** [comment]
Phantomjs is self-contained application which uses [Qt](https://github.com/ariya/phantomjs/tree/master/src/qt) as well and does not expose an API to be used by another application for rendering.
