### ISSUE TITLE
Seems setup.py miss a little code.

### ISSUE THREAD

**Issue by genius001** [scrapinghub/splash#390]
There will be failed to run splash-jupyter when perform "jupyter notebook --no-browser --port=8888 --ip=*"

The error info displayed:
no found treat.lua or json.lua.

If I added line "lua_modules/libs/*.lua" to the file setup.py, and reinstalled splash, the problem will gone. 

So I thought it maybe a little mistake in setup.py.

**Comment by Youwotma** [comment]
@genius001 Thanks for catching that!
