### ISSUE TITLE
Installing splash breaks at re2/stringpiece.h not found error

### ISSUE THREAD

**Issue by shafaq** [scrapinghub/splash#393]
I am installing splash on ubuntu the manual way.

My command is `sudo -H pip3 install -r requirements.txt`
The installation breaks at 
```

x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -g -fstack-protector --param=ssp-buffer-size=4 -Wformat -Werror=format-security -D_FORTIFY_SOURCE=2 -fPIC -I/usr/include/python3.4m -c src/re2.cpp -o build/temp.linux-x86_64-3.4/src/re2.o
    cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++ [enabled by default]
    src/re2.cpp:249:29: fatal error: re2/stringpiece.h: No such file or directory
     #include "re2/stringpiece.h"
                                 ^
    compilation terminated.
    error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
    
    ----------------------------------------
Command "/usr/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-edezpnwa/re2/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-7uq54h74-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-build-edezpnwa/re2


```

Any ideas?

**Comment by kmike** [comment]
Hey @shafaq,

pyre2 is a Splash dependency (via adblockparser); it requires re2 C++ library (https://github.com/google/re2). There are some other dependencies (like qt 5.5.1), so just `sudo -H pip3 install -r requirements.txt` is not enough. Check [provision.sh](https://github.com/scrapinghub/splash/blob/master/dockerfiles/splash/provision.sh) script - this is how Splash is installed in a clean Ubuntu 14.04 for our Docker image.

**Comment by ashlesh688** [comment]
I tried to re-run the provision.sh file as "sh provision.sh prepare_install" but it is ending as an error 

"provision.sh: 35: provision.sh: [[: not found". What should I do ? Please help

**Comment by kmike** [comment]
@ashlesh688 could you try it with bash instead of sh?

**Comment by ashlesh688** [comment]
Hi Mikhall,
Thanks for the advice now it is working but when i run the "install_deps" I am facing with this error "E: Unable to locate package libre2-dev"
can you please share your thoughts on this.
Thanks,Ashlesh. 

    On Monday, 27 March 2017 8:27 PM, Mikhail Korobov <notifications@github.com> wrote:
 

 @ashlesh688 could you try it with bash instead of sh?—

**Comment by ixeagle** [comment]
just run 
sudo apt install  libre2-dev
