### ISSUE TITLE
Splash timeout on all requests. 

### ISSUE THREAD

**Issue by shafaq** [scrapinghub/splash#394]
I have set up docker to work with splash. Docker starts up fine but even the simple pages like google.com time out. Follows the splash terminal output for splash startup. 

```
docker run -p 8050:8050 scrapinghub/splash

2016-02-26 03:39:07+0000 [-] Log opened.
2016-02-26 03:39:07.903064 [-] Splash version: 2.0.1
2016-02-26 03:39:07.903849 [-] Qt 5.5.1, PyQt 5.5.1, WebKit 538.1, sip 4.17, Twisted 15.5.0, Lua 5.2
2016-02-26 03:39:07.903997 [-] Python 3.4.3 (default, Oct 14 2015, 20:28:29) [GCC 4.8.4]
2016-02-26 03:39:07.904119 [-] Open files limit: 524288
2016-02-26 03:39:07.904248 [-] Open files limit increased from 524288 to 1048576
2016-02-26 03:39:08.112195 [-] Xvfb is started: ['Xvfb', ':1047', '-screen', '0', '1024x768x24']
2016-02-26 03:39:08.216409 [-] proxy profiles support is enabled, proxy profiles path: /etc/splash/proxy-profiles
2016-02-26 03:39:08.364839 [-] verbosity=1
2016-02-26 03:39:08.365024 [-] slots=50
2016-02-26 03:39:08.365640 [-] Web UI: enabled, Lua: enabled (sandbox: enabled)
2016-02-26 03:39:08.368755 [-] Site starting on 8050
2016-02-26 03:39:08.369102 [-] Starting factory <twisted.web.server.Site object at 0x7fb0ee1c4860>

```
Can you please help me with this.

**Comment by pawelmhm** [comment]
> Docker starts up fine but even the simple pages like google.com time out

how are you requesting those simple pages? Logs you posted dont contain any trace of requests being made to Splash, they just show Splash is started. If you posted your logs in full it means that requests you make dont reach Splash. Can you ping localhost:8050 and get demo page? When requests are timing out what error are you getting? Are they timing out with 504 status code or you dont get any status code?

**Comment by shafaq** [comment]
hey Pawl,
Thanks. 
I started docker with this command:
`docker run -p 5023:5023 -p 8050:8050 -p 8051:8051 scrapinghub/splash`
telnet "ping" output is: 
```
telnet localhost 5023
Trying 127.0.0.1...
Connected to localhost.
Escape character is '^]'.
Connection closed by foreign host.
```
nmap command trace:

```
nmap -p 8050 localhost

Starting Nmap 7.00 ( https://nmap.org ) at 2016-02-26 21:50 PKT
Nmap scan report for localhost (127.0.0.1)
Host is up (0.00013s latency).
PORT     STATE SERVICE
8050/tcp open  unknown

Nmap done: 1 IP address (1 host up) scanned in 0.04 seconds
```

Now I write in address line Firefox (44.0.2): `localhost:8050`
I write in text-field provided next to **"Render" Button.** `"http://google.com"`(its already there btw) and press the button. 

I am attaching compete logs of what the splash process outputs. If you look at the logs there is a problem that `/etc/machine-id` is not found. Well it is a problem in Ubuntu. I "patched" it, Can this be the problem? 
Anyways after processing it gives `Error 504`
```

HTTP Error 504 (Gateway Time-out)
Type: GlobalTimeoutError

Timeout exceeded rendering page

{
    "info": {
        "timeout": 60
    },
    "description": "Timeout exceeded rendering page",
    "error": 504,
    "type": "GlobalTimeoutError"
}
```
Thanks again. :) 
[splash.txt](https://github.com/scrapinghub/splash/files/148625/splash.txt)
![spashscreen](https://cloud.githubusercontent.com/assets/1555830/13359319/622df734-dcd5-11e5-8eb8-2235eb7f0230.png)

**Comment by pawelmhm** [comment]
thanks for the detailed report. Is this happening for all splash endpoints or just execute? (when you press render on startpage it makes request to localhost:8050/execute). 

can you try following url? 

http://localhost:8050/render.json?url=http://httpbin.org

 this makes request to render.json. is it responding with 504 too?

**Comment by shafaq** [comment]
Yes it responds with 504 too
`{"description": "Timeout exceeded rendering page", "error": 504, "type": "GlobalTimeoutError", "info": {"timeout": 30}}`
attached are the logs 
[splash-json.txt](https://github.com/scrapinghub/splash/files/148704/splash-json.txt)

Thanks a lot.

**Comment by shafaq** [comment]
Ok now this works fine. The only thing I have changed is my internet connection. Now I have a faster internet and it does not timeout. 
The machine-id error is still there so it was not the case.

**Comment by AhmedRafikDjerah** [comment]
docker run -p 8050:8050 scrapinghub/splash --max-timeout 3600

**Comment by mgcuesta** [comment]
Hello Ahmed.

I am retrieving the same mistake all the time
Some scripts is working fine because it runs in less than 30 seconds
Other script is always failing because it is slower. For this, each time that I execute it retrieves "GlobalTimeoutError"

The server is deploy inside "docker container" with the following parameters:

  docker run -p 8050: 8050 --proxy-profiles-path / etc / splash / proxy-profiles --max-timeout 240 --filters-path / etc / splash / filters --js-profiles-path / etc / splash / Js-profiles --lua-sandbox-allowed-modules "populare; utils; popularetarj" -lua-package-path /etc/splash/lua_modules/?.lua --slots 500 -v 2

I feel that the configuration of "-max-timeout" is not working but I do not understand why. Whatever help is welcome.

Thank you in advance

Details:

{
  "timestamp": 1491407822,
  "user-agent": null,
  "client_ip": "192.168.69.136",
  "method": "POST",
  "_id": 140363517724656,
  "path": "/execute",
  "load": [
    0.09,
    0.04,
    0.05
  ],
  **"status_code": 504,
  "error": {
    "error": 504,
    "info": {
      "timeout": 240
    },
    "type": "GlobalTimeoutError",
    "description": "Timeout exceeded rendering page"**
  },
  "active": 0,
  "maxrss": 1953936,
  "qsize": 0,
  "args": {
    "wait": "0.5",
    "uid": 140363517724656,
    "expand": "1",
    "lua_source": "local mymodule = require('popularetarj') function main(splash) splash.images_enabled = false splash.response_body_enabled = true args = {} args['user']='XXXX'  args['pass']='XXXX'  args['contract']='XXXX'  args['fromDate']='05/03/2017'  args['toDate']='05/04/2017' return mymodule.execute(splash, args) end",
    "images": "1",
    **"timeout": "240.0",**
    "url": "http://google.com"
  },
  "fds": 28,
  **"rendertime": 30.02491569519043**
}

**Comment by FreeTymeKiyan** [comment]
@mgcuesta --max-timeout is only an upper bound of the timeout you can set per request. I didn't find a global config to set timeout for all requests though. If you want longer timeout you'll have to set them in each SplashRequest.

**Comment by gotounix** [comment]
@FreeTymeKiyan How to set for each SplashRequest?
