### ISSUE TITLE
add utility to keep track of objects in memory

### ISSUE THREAD

**Issue by pawelmhm** [scrapinghub/splash#406]
Scrapy has [nice trackref module](https://github.com/scrapy/scrapy/blob/master/scrapy/utils/trackref.py) using [weakref module](https://docs.python.org/2/library/weakref.html), that allows you to track all items remaining in memory for too long. 

Perhaps we could add something like this to Splash to figure out if/where it leaks memory?

**Comment by immerrr** [comment]
FWIW, Py3.4+ has https://docs.python.org/3/library/tracemalloc.html for proactive memory allocation investigations.

**Comment by kmike** [comment]
@pawelmhm in Splash there is https://github.com/scrapinghub/splash/blob/7b90eefa0d007e57e667cf4b1e1cd16ce45ff549/splash/utils.py#L81; it is used in _debug endpoint to show all alive objects of certain type.

**Comment by kmike** [comment]
I don't know how tracemalloc is implemented, but I'm not sure all these tools help with checking how QT allocates memory; likely they only check what's allocated by Python itself.

**Comment by immerrr** [comment]
> The tracemalloc module is a debug tool to trace memory blocks allocated by Python.

yes, they only trace python allocations.

**Comment by pawelmhm** [comment]
ok thanks @immerrr and @kmike so we already track memory allocations and there is no need to add something new here
