### ISSUE TITLE
HTML download is incorrect in Splash HTTP UI

### ISSUE THREAD

**Issue by kmike** [scrapinghub/splash#412]
1. Render this URL http://forums.pdfforge.org/categories/help using default script in Splash UI;
2. Click 'download' button near 'html'.

For me it returns a 4K document, while it should be 60K+. HTML code in the textarea is correct.

Firefox 44.0.2, OS X.

**Comment by genius001** [comment]
I have test it, seems render no problem for me.

![screen shot 2016-03-11 at 07 15 46](https://cloud.githubusercontent.com/assets/5621825/13687907/4205e960-e759-11e5-8e73-27515a563ea9.png)

Version 48.0.2564.116 (64-bit), OS X.

**Comment by genius001** [comment]
I have test it, seems render no problem for me.

![screen shot 2016-03-11 at 07 15 46](https://cloud.githubusercontent.com/assets/5621825/13687907/4205e960-e759-11e5-8e73-27515a563ea9.png)

Chrome Version 48.0.2564.116 (64-bit), OS X.

**Comment by kmike** [comment]
It also render fine for me, but if I click 'download' link and save the result then the resulting file is truncated.

**Comment by genius001** [comment]
Yes, When I click 'download', it saved as 'forums.pdfforge.org.txt'

![screen shot 2016-03-11 at 07 44 24](https://cloud.githubusercontent.com/assets/5621825/13688487/4098f85c-e75d-11e5-8e62-60c441a50e84.png)

**Comment by kmike** [comment]
Aha, it also works for me in Chrome; it looks like the error is specific to Firefox.

**Comment by Youwotma** [comment]
Seems like different browser (and different versions of the same browser) have different limits on the maximum length of a data url ([source](https://stackoverflow.com/questions/695151/data-protocol-url-size-limitations)). I'll try to find a workaround for this.
