### ISSUE TITLE
How can I get the response data but not rendered?

### ISSUE THREAD

**Issue by genius001** [scrapinghub/splash#414]
I think sometimes get the raw data will be convenient than the data rendered by js.

**Comment by kmike** [comment]
Hi @genius001,

There is a ticket about getting raw response bodies: https://github.com/scrapinghub/splash/issues/337
If making an additional request is OK, or you don't need to render a page at all then there are splash:http_get and splash:http_post.

**Comment by genius001** [comment]
Thanks @kmike
