### ISSUE TITLE
Web Scraping Helpers GSOC 2016

### ISSUE THREAD

**Issue by RishabGoel** [scrapinghub/splash#418]
This is something, I always wanted. To combine the functionality of selenium with scrapy with a easy to use interface, to make the crawling process a lot easier. I have emailed as well in detail. Please reply asap, so that I can start making the project.

**Comment by kmike** [comment]
Hey @RishabGoel!

I've sent you a reply, sorry for the delay! 

For web scraping helpers project a description of a library you want to build and initial implementation of a couple of helpers would be a good start. Please open an issue / pull request in Github, or just submit your proposal. Check also tickets with 'scripting' tag: https://github.com/scrapinghub/splash/issues?q=is%3Aissue+is%3Aopen+label%3Ascripting - it'd be perfect to try fixing some of them.

If you prefer, for communication we can also use Splash gitter chat - see https://gitter.im/scrapinghub/splash.

**Comment by redapple** [comment]
@RishabGoel , will you be submitting your proposal to GSoC website?
I can't see your proposal yet in https://summerofcode.withgoogle.com
If you still want to participate, you only have until this Friday 25 March 19:00 UTC to do so.

**Comment by RishabGoel** [comment]
Yes, I had exams going on. I am done with the tutorials. I will be making a
proposal by tomorrow. Can I fix patches till 26 th. It would be of great
help. I will post the proposal by tomorrow.
Regards.

**Comment by kmike** [comment]
@RishabGoel If I'm not mistaken, we'll be evaluating student proposals in April; you're more than welcome to keep working on your application (e.g. submit patches) after March 25th.

**Comment by RishabGoel** [comment]
Ok sure, I will submit the proposal around this time tomorrow. Is there a
template that I need to adhere to or the one on gsoc site is fine?

**Comment by redapple** [comment]
@RishabGoel , http://gsoc2016.scrapinghub.com/guidelines/ are the ones to follow yes.
Looking forward to reading your proposal!
