### ISSUE TITLE
Add ability to changes user agent like changing proxies. 

### ISSUE THREAD

**Issue by dustinthughes** [scrapinghub/splash#42]
Add setting in *.ini for user agents.

[useragents]
chrome:'Mozilla/5.0 (Windows NT 6.2; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/30.0.1599.17 Safari/537.36'
firefox:'Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:25.0) Gecko/20100101 Firefox/25.0'

http://localhost:8050/render.html?url=http://mywebsite.com/page-with-javascript.html&proxy=mywebsite&UA=chrome

Example on changes user agent on QNetworkAccessManager:

QNetworkAccessManager* mgr = new QNetworkAccessManager();
....
QNetworkRequest req;
req.setUrl(QUrl("enter url") );
req.setRawHeader( "User-Agent" , "Mozilla Firefox" );
mgr->get(req);

The addition will have to be two part addition by adding way to parse the config .INI file and the setting the raw header for QT.

**Comment by kmike** [comment]
This is now possible using one of these functions:
* [splash:on_request](http://splash.readthedocs.org/en/latest/scripting-ref.html#splash-on-request) 
* [splash:set_custom_headers](http://splash.readthedocs.org/en/latest/scripting-ref.html#splash-set-custom-headers)
* [splash:set_user_agent](http://splash.readthedocs.org/en/latest/scripting-ref.html#splash-set-user-agent)

I think adding support for .ini files is unnecessary.
