### ISSUE TITLE
use splash with curl the coding is ok,but requests is error?

### ISSUE THREAD

**Issue by wusy1209** [scrapinghub/splash#421]
Hi, everyone !
When i use requests to download a page,the coding is error：

```
res = requests.get('http://127.0.0.1:8050/render.html', params={'url': 'http://www.qichacha.com/firm_JS_15d5e3cbf3f484215f9293a9b3489905.shtml'}, timeout=10)
t = res.text
print res.headers
```

But when i use curl,the coding is ok：
`curl 'http://localhost:8050/render.html?url=http://www.qichacha.com/firm_FJ_9eb0be8a839dc95eb8f5588fef1a855b.shtml'`

What is the reason?

**Comment by Youwotma** [comment]
Hi @wusy1209 

For me it gave a timeout error, and it worked when I set the timeout to a larger value (30)
```
In [6]: requests.get('http://127.0.0.1:8050/render.html', params={'url': 'http://www.qichacha.com/firm_JS_15d5e3cbf3f484215f9293a9b3489905.shtml'}, timeout=30)
Out[6]: <Response [200]>
```
Let us know if you still have problems

**Comment by wusy1209** [comment]
@Youwotma ,yes, the page can downloaded,but when I print it, the page is error encoding:
 ```
res = requests.get('http://127.0.0.1:8050/render.html', params={'url': 'http://www.qichacha.com/firm_JS_15d5e3cbf3f484215f9293a9b3489905.shtml'}, timeout=30)
print res.text #it is error encoding
```
then, I use `chardet `detect` res.content`，the result is `None`

**Comment by wusy1209** [comment]
hi, @Youwotma ,today i test it in another computer ,the encoding is ok, but i find another problem.this page we can just download a partial of content. you see:
![qq 20160319111238](https://cloud.githubusercontent.com/assets/16160170/13896350/85c1ad72-edc3-11e5-900b-3e682c736083.png)

**Comment by genius001** [comment]
@wusy1209 

1, 使用res.text的时候，requests会自动探测encoding type的，有的时候探测不对，所以返回的数据是乱码。你可以使用res.encoding查看当前的编码是什么编码，然后你自己试试GB5编码。

2, render.html 返回的是渲染后的html源码，而且有的浏览器下载有限制。
参考这个：https://github.com/scrapinghub/splash/issues/412
```
render.html
Return the HTML of the javascript-rendered page.
```

**Comment by wusy1209** [comment]
好的，我试试，多谢了 @genius001
