### ISSUE TITLE
same page, render.html is ok,but execute is error encoding

### ISSUE THREAD

**Issue by wusy1209** [scrapinghub/splash#423]
Test one(execute):
```
script = ''' 
function main(splash)
    splash:on_request(function(request)
        request:set_proxy{host="111.2.131.233", port=80}
        --request:set_header("Accept-Language", "zh-CN,zh;q=0.8")
        request:set_header("Accept-Encoding", "gzip,deflate")
        --request:set_header("Accept-Encoding", "*")
        --request:set_header("Accept", "text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8")
        --request:set_header("User-Agent", "Mozilla/5.0 (X11; CrOS i686 2268.111.0) AppleWebKit/536.11 (KHTML, like Gecko) Chrome/20.0.1132.57 Safari/536.11")
        --request:set_header("Connection", "keep-alive")
        --request:set_header("Cache-Control", "max-age=0")
    end)
    --splash:go("http://10.0.8.213:8000/sample/splash/")
    splash:go("http://www.qichacha.com/firm_JS_15d5e3cbf3f484215f9293a9b3489905.shtml")
    splash:wait(3)
    --splash:runjs("document.getElementById('iframe1').innerHTML= frames[0].document.body.innerHTML")
    --splash:runjs("var iis = document.getElementsByTagName('iframe');for(var i = 0;i < iis.length; i++){iis[i].innerHTML=frames[i].document.body.innerHTML}")
    return splash:html()
end
'''
res = requests.get('http://127.0.0.1:8050/execute', params={
    'lua_source': script}, timeout=10)
t = res.text
print t
```

Result One:
�s��k��="" �����|am��f�gu~���v�rn�v7�j����m������Ϊ��k����v���q��l}fj�^j�nu�czҙ�="" �_<ңn9�����!jk"��y�<�g�!&ʉ"�ẗ���j�!���g���g������q�f��="" ������9�ەˌp�g�����Ư="" n�_��.���\#gi��!��7z�!�66���__lc����x�iiu�i}��¹��]$j`�x���q�@��[���|1v��7�g�ig�h+͌��p'6���в�o��r0�[��t��|m�u�n��n����u�q="">��5.f\xqaF�;#g��.w�xfx�l�O�oM$.�L|�/y���?�5W��?@�m�
                                                                                                                                   Te&amp;���cQ/��ƽ��؛�_�r�.̮�ݾa�M�X
                                                                                                                                                                                ��m�~-� F/w�Q 
FB�`g�p�xM�k��C[rdp�o��E��~�-z$���=�{��af���D���.�r{�&gt;��
                                                                                       t���F�=
w���ُ��
/f 
  �se���8c.|o�&amp;Z�9.1��0x
8Em���:�"�x.�͊�̵b�?��:�{#h|�)Q���굟	@���c��S8QW$��˖w�����6��k����r�R�};
                                                                                                               ���n-6֦������!~E;?�����p�w�,��QO�{r
                                                                                                                                                                    �º�v*����?�
                                                                                                                                                                                       ��㼉�s;���]�U�?Q���2@r��&amp;O�.�g캯W��x���[w���e 
                                                                  �؞;��{C�U�D���@yx�	�t�M����Q�&gt;�I��
{���Noh^��'��9��틄����
                                   �~�W�iO�?���{�G�E��JN���`
)Qga
    �U�cC�����E�.k�O�~��V����|��'����=�P
                                                               e�V&amp;eDWLg��������;��b������u�&lt;~�t��:��OL�=y�����??�?���'R��/J�2�CK`_�p�"�F[[=B��h���&gt;�:ڹ�4g8��;IJR���`ˊ�!�nw                                                                                                                                             ��:�[P�H�"��*\����N������v�^.G.�H���Ñ����[LD�����.���Q�B��6����=.g`�o&gt;U�uV��?�Nsr�ASr��g)&amp;q�:{j�a�.AV
�5zF����9Z�6��x��̐��-ڸ|���aG��[�Q@l��B���^}ܘ�6�HI7m�+��W���]m,o!/G]}�^�V�Yߛ�S�7��{����pS���ʲVE���f�a;�oj7���|�
                                                                                                                                                                   i�����e�Fx��0!|+���]r��Ny.�x���c�Ћx��_��F�Cx����G���{��#���w��g9q�w�k�ⷅz��
]8����x9s�E%�����4�%���e,#p�#MX�&gt;HIp��K��¯�2.4�z��@��sM��i�3ʅ������!��&lt;���h���&amp;?GO"��砲����_仼+��r�p�</0x�nwp></m��\�ᶠ7�q9����_����]w 
                    �֍></i��}������xl<�k�2pq�></body></html>

Test two(render.html):
```
res = requests.get('http://127.0.0.1:8050/render.html', params={'url': 'http://www.qichacha.com/firm_JS_15d5e3cbf3f484215f9293a9b3489905.shtml',
    'proxy': 'http://111.2.131.233:80'}, headers={'Accept-Encoding': 'gzip,deflate'}, timeout=10)
t = res.text
print t
```

Result Two:
![test2](https://cloud.githubusercontent.com/assets/16160170/13913337/b48689d4-ef80-11e5-869d-ef4f5327f227.png)

In the test one, when i set `request:set_header("Accept-Encoding", "*")`,the result is right.

What is the reason?

**Comment by mbriliauskas** [comment]
Did you workaround the issue with splash?
