### ISSUE TITLE
'user-agent' incorrect from browser_tab.py

### ISSUE THREAD

**Issue by genius001** [scrapinghub/splash#425]
Should be use 'User-Agent' instead of 'user-agent'?

[https://github.com/scrapinghub/splash/blob/master/splash/browser_tab.py#L915](url)

**Comment by kmike** [comment]
Header names are case-insensitive, so 'user-agent' shouldn't cause problems. But I agree 'User-Agent' spelling is better.

**Comment by genius001** [comment]
Aha, yes, this is not an error. just a bit noisy. 
The headers are not same. 

When I setting:  splash:set_user_agent("Mozilla/5.0"),  
splash:go header is             'User-Agent':"Mozilla/5.0"
splash:http_get header is    'user-agent':"Mozilla/5.0"

**Comment by kmike** [comment]
Yeah, I agree - would you mind sending a PR?

**Comment by genius001** [comment]
Ok, I am happy to do that, and I have send the PR.
