### ISSUE TITLE
Best way to get the page .png AND the original images from the page?

### ISSUE THREAD

**Issue by topiaruss** [scrapinghub/splash#429]
I already use Splash via the scrapy-plugin. Love it! Thanks! I get the png of the page, and the rendered html. All works nicely.  

Now I want to get the original images that the proxy already pulled when it built the png, but I don't want to go back to the target server. 

Has anyone done that? I imagine I'll create _another_ cacheing proxy upstream of the Splash proxy. Splash will get all its images and pages via the cacheing proxy, then I'll process the rendered html from the json data['html'], pull out the image urls, and issue a fresh GET that goes _via the cacheing_ proxy where the images will still be cached.

I have a feeling I might be working harder than necessary. Any comments?

**Comment by topiaruss** [comment]
Perhaps dfriestedt's answer to the below SO question is the answer to second stage image GET:
  http://stackoverflow.com/questions/26661282/scrapy-enable-proxy-on-imagespipeline-only

What I don't know is how to set splash to use the new cacheing proxy.

**Comment by pawelmhm** [comment]
your approach with caching proxy seems ok, alternative approach that _should_ be possible according to our documentation is using Lua script to fetch bodies of image responses, keep them in Lua table as binary capsule and return with base64 encoding together with screenshot. 

However I see this unfortunately does not work as advertised so we'll probably need to fix that. Here is sample script that _should work_ but currently does not :/

```Lua
treat = require("treat")

function main(splash)
    -- table that will keep all images downloaded by Splash
    local images = {}
    local i = 0
    splash:on_response(function (response) 
        i = i + 1
        content_type = response.headers["content-type"]
        -- check content type if it's image add image to something that will be returned
        if content_type ~= nil and string.find(content_type, "image") then
            -- response.body should be binary capsule, TODO figure out why it fails now and how to handle this
            images[i] = response.body
            --   body as string is None, why?
            body_as_string = treat.as_string(response.body)
            print("body is \n\n\n\n")
            print(body_as_string)
            print("***************")
            --- output in logs is
            --- body is nil
        end
    end)

    splash:go(splash.args.url)
    -- this shows that we get images
    -- for key, value in pairs(images) do print(key, value) end
    local screenshot = splash:png()
    -- but returning result fails for some reason...
    return {
        images=images,
        screenshot=screenshot
    }
end
```

When I run above in Splash I get 500 Error with traceback:

```
2016-03-27 21:42:17.721342 [-] Unhandled Error
	Traceback (most recent call last):
	  File "/home/pawel/.local/lib/python2.7/site-packages/twisted/internet/defer.py", line 501, in _startRunCallbacks
	    self._runCallbacks()
	  File "/home/pawel/.local/lib/python2.7/site-packages/twisted/internet/defer.py", line 588, in _runCallbacks
	    current.result = callback(current.result, *args, **kw)
	  File "/home/pawel/.local/lib/python2.7/site-packages/twisted/internet/defer.py", line 393, in callback
	    self._startRunCallbacks(result)
	  File "/home/pawel/.local/lib/python2.7/site-packages/twisted/internet/defer.py", line 501, in _startRunCallbacks
	    self._runCallbacks()
	--- <exception caught here> ---
	  File "/home/pawel/.local/lib/python2.7/site-packages/twisted/internet/defer.py", line 588, in _runCallbacks
	    current.result = callback(current.result, *args, **kw)
	  File "/home/pawel/scrapinghub/splash/splash/resources.py", line 156, in _write_output
	    return self._write_output(data, request, content_type)
	  File "/home/pawel/scrapinghub/splash/splash/resources.py", line 147, in _write_output
	    data = json.dumps(data, cls=SplashJSONEncoder)
	  File "/usr/lib/python2.7/json/__init__.py", line 250, in dumps
	    sort_keys=sort_keys, **kw).encode(obj)
	  File "/usr/lib/python2.7/json/encoder.py", line 207, in encode
	    chunks = self.iterencode(o, _one_shot=True)
	  File "/usr/lib/python2.7/json/encoder.py", line 270, in iterencode
	    return _iterencode(o, 0)
	  File "/home/pawel/scrapinghub/splash/splash/utils.py", line 40, in default
	    return o.as_b64()
	  File "/home/pawel/scrapinghub/splash/splash/utils.py", line 30, in as_b64
	    return base64.b64encode(self.data).decode('utf-8')
	  File "/usr/lib/python2.7/base64.py", line 53, in b64encode
	    encoded = binascii.b2a_base64(s)[:-1]
	exceptions.TypeError: must be string or buffer, not None
```

**Comment by topiaruss** [comment]
Thanks Pawel. I really appreciate your attention to this. I'm going to think about this more tomorrow. It's likely that I'll have some comments at that point. 
Best wishes!

**Comment by kmike** [comment]
Splash supports returning bodies of responses to related resources since v2.2 - see [splash.response_body_enabled](http://splash.readthedocs.io/en/stable/scripting-ref.html#splash-response-body-enabled), [request:enable_response_body](http://splash.readthedocs.io/en/stable/scripting-request-object.html#splash-request-enable-response-body) and [response_body](http://splash.readthedocs.io/en/stable/api.html#arg-response-body) HTTP argument.
