### ISSUE TITLE
splash:mouse_click on link with attribute: "target"="_blank"

### ISSUE THREAD

**Issue by genius001** [scrapinghub/splash#437]
splash:mouse_click not working if a tag <a> with "target"="_blank",
Even if use splash:runjs("element.removeAttribute("target")") before click it.
Could anyone give me some idea or workaround?
Thank you.

**Comment by kmike** [comment]
Hey @genius001 - how did you solve that?

**Comment by genius001** [comment]
Hey @kmike 

I solved some case, not all.

On file: qwebpage.py, I add some:

```
    def acceptNavigationRequest(self, webFrame, networkRequest, navigationType):
        if self.navigation_locked:
            return False

        if(navigationType == QWebPage.NavigationTypeLinkClicked):
            if(webFrame == self.mainFrame()):
                self.mainFrame().load(networkRequest.url())
            else:
                # TODO desire to create new frame or window load future url?
                # currently using mainFrame temporary
                self.mainFrame().load(networkRequest.url())

            return False
```

**Comment by genius001** [comment]
I have re-implement some code, adds a splash:mouse_move  (random move) functionality. but cannot work. https://github.com/scrapinghub/splash/compare/master...genius001:master

At the same time, I noticed @pawelmhm have started this feature.

**Comment by pawelmhm** [comment]
> At the same time, I noticed @pawelmhm have started this feature.

no worries about me, if your code works fine I'll be happy to use it

**Comment by genius001** [comment]
Hah @pawelmhm 

My code is also not fired in some cases.
My idea flow is:
```
splash:go("http://somepage.com")
splash:wait(0.5)
local get_elem_rect = splash:jsfunc([[
  function (selector){
    var elem = document.querySelector("selector");
    var rect = elem .getBoundingClientRect();
    return [rect.left, rect.top, rect.right, rect.bottom];
  }    
]])

local rect = get_elem_rect ("selector")
local r = {rect[1],rect[2],rect[3],rect[4]}
local x, y = splash:mouse_move{region=r}  -- move randomly and return the last mouse cursor position
splash:mouse_click(x, y)
splash:wait(1)
return splash:png()
```

So, splash:mouse_move and splash:mouse_click just do one thing and keep simple, selecting element using splash:jsfunc.

Any suggestion will welcome :)

**Comment by pawelmhm** [comment]
@genius001 why do you want to move randomly? 

I think it would be better to allow users to specify coordinates for movement, hover over some specific element.

Same for click(), it would be better to click() on something, on some element.

**Comment by genius001** [comment]
@pawelmhm  yes, You are right, move randomly just fit for me, but most case should be better to allow users to specify coordinates.
