### ISSUE TITLE
Add splash:send_keys method

### ISSUE THREAD

**Issue by eskerda** [scrapinghub/splash#439]
It's not unusual that some websites have javascript generated forms, using knockout for example. Filling up the generated inputs and clicking the submit won't work, since the binding with the form did not go through the proper process and thus the form fails at submitting after missing validation.

Even if this was possible with javascript, it would really ease usage having something native that sends key events.

**Comment by pawelmhm** [comment]
send key events would probably be a matter of generating [QKeyEvent class](http://doc.qt.io/qt-5/qkeyevent.html) and doing `QApplication.post_event(web_page, event)` call somewhere in browser tab?

**Comment by eskerda** [comment]
As it looks on casperjs they do:

1. get element for selector, check if element allows text input and click element
2. send keys
3. send blur event in case element allowed text input

https://github.com/n1k0/casperjs/blob/3435639ce1ff290a35b4c6362dd8099ca6484709/modules/casper.js#L1616

**Comment by eskerda** [comment]
https://github.com/scrapinghub/splash/pull/447

**Comment by kmike** [comment]
Fixed by https://github.com/scrapinghub/splash/pull/447, thanks @eskerda!
