### ISSUE TITLE
How to request the same site many times parallelly?

### ISSUE THREAD

**Issue by genius001** [scrapinghub/splash#440]
I am using  gevent+splash for concurrent request,
But seems cannot work fine?

**Comment by pawelmhm** [comment]
how are you using it? can you share your code?

**Comment by genius001** [comment]
@pawelmhm 

I'm sorry, I thought I had misunderstood splash about parallel.

My purpose is request a url for many times.
for example, I want request sites 'example.com' for 100 times.
but, in my code actually for 2,3 times only.

```
#-*- coding: utf-8 -*-

import requests

import gevent
from gevent import monkey; monkey.patch_all()
from gevent.pool import Pool


def worker(url):
    base_url = "http://localhost:8050/execute?"
    lua_source = "function main(splash) splash:go('%s') return splash:html() end" % (url)

    params = {"lua_source":lua_source}

    res = requests.get(base_url, params=params, headers={"content-type": "application/json"})

    print res.content

if __name__ == "__main__":

    pool = Pool(100)
    url = 'http://www.example.com'

    for i in range(30):
        pool.spawn(worker, url)

    pool.join()
```

I think splash will no longer request if one of them has loaded finished.

But in some case, it is have to request the same sites for many times individually.

Is there any workaround?

**Comment by genius001** [comment]
After careful consideration, I think no need do that. Aha
