### ISSUE TITLE
Hello, splash filter can not work on this case?

### ISSUE THREAD

**Issue by genius001** [scrapinghub/splash#441]
I want block a url. 
like this: http://t12.baidu.com/it/u=1853176499,2178064445&fm=76

I put following rule in easylist.txt, but now work.

||t12.baidu.com^

how to solved it? thank you:)

**Comment by kmike** [comment]
@genius001 how have you solved it?

**Comment by genius001** [comment]
I'm sorry, I forgot explain it.
splash filters work fine.

I just restart splash.sever --filters-path=/path/to/filters/
Does must reload it to take effect?

**Comment by kmike** [comment]
Thanks for explanation!

Yes, large filters (e.g. easylist) load very slowly - it take seconds, so they are loaded only once, at startup.
