### ISSUE TITLE
How to cache file with squid through another proxy?

### ISSUE THREAD

**Issue by genius001** [scrapinghub/splash#443]
Most of time, I set different proxy ip fetch sites using request:set_proxy.
But, there is a lot of static file. e.g. js/css. I want cache these files instead of block them.

The idea simply like below:
APP ---> splash ---> squid ---> ProxyServer ---> WebServer

Does squid can accomplish my problem? how to set it?

Thank you.

**Comment by Youwotma** [comment]
Hi @genius001 
Yes, squid can accomplish what you want, check here: http://wiki.squid-cache.org/Features/CacheHierarchy#How_do_I_configure_Squid_forward_all_requests_to_another_proxy.3F

**Comment by genius001** [comment]
Thanks @Youwotma 

I will check it.
