### ISSUE TITLE
splash:set_content not rendering ajax loaded sites

### ISSUE THREAD

**Issue by rbs392** [scrapinghub/splash#450]
Angularjs based sites are not rendering using set_content
Ex: 
function main(splash)
  assert(splash.set_content{data, baseurl="https://www.madewithangular.com"})
  return splash.html()
end

**Comment by kmike** [comment]
Hi @rbs392,

Does it work just with `splash:go`?

The problem could be with localStorage: AngularJS websites often use localStorage; Splash uses Private Mode by default, and localStorage is not available in WebKit when Private Mode is enabled. Could it be the problem? There are some [docs](http://splash.readthedocs.org/en/stable/faq.html#how-do-i-disable-private-mode) on how to disable Private Mode in Splash.

**Comment by kmike** [comment]
Also, I think a delay is needed to render this website, something like `splash:wait(5.0)`.

**Comment by rbs392** [comment]
Thanks @kmike
