### ISSUE TITLE
Can splash release memory automatically?

### ISSUE THREAD

**Issue by genius001** [scrapinghub/splash#455]
Splash will consume the memory every moment,
so I have to restart the splash instance manually everyday.

Is there a method or tool can release the memory automatically?

All suggestions are welcome and appreciated.

**Comment by Youwotma** [comment]
hi,

There is the `/_gc` endpoint that will run garbage collection https://splash.readthedocs.io/en/stable/api.html#gc

Python will run it's garbage collection automatically from time to time, but not sure if webkit memory caches are purged automatically.

**Comment by genius001** [comment]
thanks @Youwotma 

this is what I wanted.

**Comment by wusy1209** [comment]
@genius001  ，你能释放内存吗？   我splash也占了大量内存，即使请求都完成了也不释放。

**Comment by genius001** [comment]
@wusy1209 ，只能释放python自己的。
好像不能释放webkit所占用的。
我的也是占了大量内存。
_gc只能释放那么一点。

我懒得问老外了。哈哈。

**Comment by wusy1209** [comment]
好吧

**Comment by MichaelFeng87** [comment]
后来怎么搞定的呀？

**Comment by alexKeleon** [comment]
这个问题有进展么
