### ISSUE TITLE
Looking forward to access response.body directly.

### ISSUE THREAD

**Issue by genius001** [scrapinghub/splash#457]
Splash is simple and smart easy to use. a little disappointed is that it cannot access response.body. so I have to use hack-like method to get it. this let the code ugly and code flow  complex.

It is possible add feature for access response.body directly if pyqt's peek() working on pyqt5?
Looking forward it :)

**Comment by pawelmhm** [comment]
@genius001 are you asking about accessing response.body in on_response callback? There are couple of issues for that #337 and here #431

>  pyqt's peek() working on pyqt5?

can you add some links to this qt method you talk about? perhaps you can implement some code yourself. PR-s are very welcome here.

**Comment by genius001** [comment]
Hi @pawelmhm 

HAR can get most of the metadata, but cannot get the response.body
When I fetch a website, I want get the additional data. for example js data or frame's content or images.

The qnetworkreply class inherent from qiodevice. it have some methods for read bytes from reply: seek(), peek(), readAll(). seems using peek() can read reply bytes, like get a copy reply. But I'm not sure.

discuss [here](https://github.com/scrapinghub/splash/pull/452)
document [peek()](http://doc.qt.io/qt-5/qiodevice.html#peek)

**Comment by genius001** [comment]
https://github.com/scrapinghub/splash/pull/454 works for me.
current, I can use splash:har() to get all extra resource.
It's very convenient to fetch something.
