### ISSUE TITLE
Deep copy of HAR files

### ISSUE THREAD

**Issue by shaylevi2** [scrapinghub/splash#461]
What is the purpose of this deep-copy? why can't we just return the entry?

https://github.com/scrapinghub/splash/blob/master/splash/har_builder.py#L54

**Comment by kmike** [comment]
Hey @shaylevi2,

The purpose is to return a 'frozen' copy of the current entry - otherwise it can be updated in future. It is easier to reason about a code if you know the data is immutable.

**Comment by kmike** [comment]
Entry is no longer deep-copied.
