### ISSUE TITLE
Splash cookie could not be sent to the server, but use the scrapy. Request is normal

### ISSUE THREAD

**Issue by xiaowenjie21** [scrapinghub/splash#462]
`def start_requests(self):
       
        url='http://www.locoyposter.com/site/login.html'
        script="""
               function main(splash)
                
                
                splash:add_cookie{'PHPSESSID','ck9v2cg79i190t45nd1inrtgp1'}
                   splash:add_cookie{'Example_auth','23b92f65be3533dab8f8f2e185a729c979805621s%3A62%3A%228bb7L4lZND90NKlAIy7T3OPQSDP3%2BaKLBpHdlLIljufjFCOP93hOrQ86frQZAA%22%3B'}
                assert(splash:go{
                splash.args.url,
                headers=splash.args.headers,
                http_method=splash.args.http_method,
                body=splash.args.body,
                })
                assert(splash:wait(0.5))
                local entries = splash:history()
                local last_response = entries[#entries].response
                return {
                url = splash:url(),
                headers = last_response.headers,
                http_status = last_response.status,
                cookies=splash:get_cookies(),
                html = splash:html(),
                }
                          
              end
              """            
        
        yield SplashRequest(url,self.parse_next,args={'lua_source':script,'url':url},endpoint='execute')
    
    def parse_next(self,response):
        print response.body`

This code is used to http://www.locoyposter.com landing site, I print the source code is not logged in, but I use
scrapy. Request, and put cookies inside, but returns the correct login source code

seetings.py has 
COOKIE_DEBUG=True
COOKIE_ENABLE=True
SPLASH_COOKIES_DEBUG=True

This is what causes it???I cannot understand

**Comment by Youwotma** [comment]
Hi,

The correct syntax for adding cookies is
```
splash:add_cookie{"PHPSESSID', "ck9v2cg79i190t45nd1inrtgp1", "/", domain="http://www.locoyposter.com"}
```
For more info: https://splash.readthedocs.io/en/stable/scripting-ref.html#splash-add-cookie

Regards,
David
