### ISSUE TITLE
missing cython requirement

### ISSUE THREAD

**Issue by leorocher** [scrapinghub/splash#473]
After upgrading from Splash 2.0.3 to Splash 2.1 I was no longer able to access the **/execute** endpoint.

Changing this line in the requirements.txt file solved the isssue:

from:

```
lupa >= 1.3
```

to:

```
cython==0.24 
lupa==1.3 --install-option="--with-cython"
```

**Comment by kmike** [comment]
What error are you getting without `--with-cython` option? lupa is installed without Cython on Travis CI, and tests pass. If installation doesn't work for you it may worths to report it to https://github.com/scoder/lupa/issues.

**Comment by leorocher** [comment]
I only had a 404 error when trying to acces the /execute endpoint. I did not try to run the tests.

**Comment by kmike** [comment]
I mean are there errors in log when you run `pip install 'lupa>=1.3'` without --with-cython option? If /execute is not available it means lupa is not installed.

**Comment by sandeepsingh** [comment]
Hi, 
Getting this error while using 'execute' endpoint, i have installed lupa and restarted the splash, still the error persists kindly help me on this.
 
curl 'http://127.0.0.1:8050/execute?lua_source=function+main%28splash%29%0D%0A++return+%27hello%27%0D%0Aend'

<html>
  <head><title>404 - No Such Resource</title></head>
  <body>
    <h1>No Such Resource</h1>
    <p>No such child resource.</p>
  </body>
</html>

**Comment by kmike** [comment]
Hey @sandeepsingh! This error means Lua support is not available: either lua or lupa are installed incorrectly. Do you have Lua 5.2 installed? Could you please paste

a) Splash startup log;
b) `pip install -I lupa==1.3` install log
