### ISSUE TITLE
Splash returned the html before js modifying the DOM

### ISSUE THREAD

**Issue by gamelife1314** [scrapinghub/splash#480]
I want to parse a web page which is generated by JavaScript with splash. But I get the html which was't modified, I don't know how to fix the problem. Please give me some advices. My request codes as follows:
```py
# coding:utf-8
import requests

request = requests.get('http://127.0.0.1:8050/execute', params={
    'lua_source': '''
    function main(splash)
        splash.js_enabled = true
        splash.images_enabled = false
        splash:autoload("http://apps.bdimg.com/libs/jquery/2.1.4/jquery.min.js")
        splash:add_cookie("pt2gguin", "o1185694600")
        splash:add_cookie("ptcz", "5bdc312c663e0769444cde733a62c3c7a964862931d81a9b643c89e51ed14afc")
        splash:add_cookie("pgv_pv", "8405527552")
        splash:add_cookie("RK", "pvHDHjqmQO")
        splash:set_custom_headers({
            ["Referer"] = "http://weixin.sogou.com/weixin?type=1&query=%E5%90%8C%E9%81%93%E5%A4%A7%E5%8F%94&ie=utf8&_sug_=n&_sug_type_=1&w=01015002&oq=&ri=42&sourceid=sugg&sut=0&sst0=1468289064259&lkt=0%2C0%2C0&p=40040108",
            ["User-Agent"] = "Mozilla/5.0 (Windows NT 10.0; WOW64; rv:47.0) Gecko/20100101 Firefox/47.0",
            ["Host"] = "mp.weixin.qq.com"
        })
        assert(splash:go("http://mp.weixin.qq.com/s?timestamp=1468291744&src=3&ver=1&signature=3UsjqHGBmLiVWBnyY6lG*ydqXQ2B8nTwYd6*2Sv6yiYRopAtzE8Q5*YwmYBg4tUdXlHiyHmOJ50jG7vopb48AiBYb*hfiT-4iDfsj0qPE609eZFi6W722JYcCHXBtjpzoM8phGI*2-t1Ak*vsFskBLn78CEt0rPZWJjBgW0-vco="))
        assert(splash:wait(0.5))
        splash:evaljs("var h = $(document).height()-$(window).height();$(document).scrollTop(h);")
        assert(splash:wait(0.5))
        return splash:html()
    end
    '''
})

print request.status_code
print request.text
```
## **I find splash did't send ajax request, Does it actually like this?**

requests = {}
        splash:on_request(function(request)
            table.insert(requests, request.info)
        end)`
`

**The page in the program maybe expire when you will visit**
 please visit [http://weixin.sogou.com/weixin?type=1&query=woshitongdao](url)
and then click the first item. that page that is I want to my parse

Please forgive my bad english!

**Comment by prisoneroffreedom** [comment]
Having similar issues. Any update on this?

**Comment by kmike** [comment]
@prisoneroffreedom it depends on a website and on Splash version used. Common reasons: 

* a request is triggered by some user action, e.g. by scrolling;
* wait time is too small;
* website uses some features which are not supported by Splash rendering engine (currently `scrapinghub/splash:master` Docker image has a much more recent WebKit than `scrapinghub/splash`);
* there was an error while rendering, e.g. caused by private mode enabled in Splash by default

**Comment by Gallaecio** [comment]
Those and other reasons are covered at https://splash.readthedocs.io/en/stable/faq.html#website-is-not-rendered-correctly
