### ISSUE TITLE
Load responsive images on Splash

### ISSUE THREAD

**Issue by dongchirua** [scrapinghub/splash#483]
Hi, I try to load a page supporting responsive image like http://www.bbc.com.
I have gone around then I used the script below. The script was supposed to get image after scrolling down.
Is there anyone here has met this issue?

```
function main(splash)
  local url = splash.args.url
  assert(splash:go(url))
  assert(splash:wait(5))
  local scroll_to = splash:jsfunc("window.scrollTo")
  scroll_to(10, 300)
  assert(splash:wait(10))
  return {
    html = splash:html(),
    png = splash:png(),
    har = splash:har(),
  }
end
```

**Comment by Gallaecio** [comment]
Did you manage to solve your issue?
