### ISSUE TITLE
[scripting] make private methods of exposed objects in Lua to be not bounded to the particular instance

### ISSUE THREAD

**Issue by mike1808** [scrapinghub/splash#488]
Currently, private methods in Lua are bounded to the last wrapped exposed object. Some solution was given in #484 but their private methods are accessible from scripts.

**Comment by mike1808** [comment]
@immerrr

**Comment by immerrr** [comment]
thanks, i'll try to look into this in a few days

**Comment by kmike** [comment]
I think this is already fixed.
