### ISSUE TITLE
provision.sh install_deps qt551 404 error

### ISSUE THREAD

**Issue by pbsbacellar** [scrapinghub/splash#489]
Hi, I am trying to install without Docker using provision.sh on Ubuntu 16.04.
I am having trouble installing qt551 from install_deps(). I receive 404 error:

> W: The repository 'http://ppa.launchpad.net/beineri/opt-qt551-trusty/ubuntu xenial Release' does not have a Release file.
> E: Failed to fetch http://ppa.launchpad.net/beineri/opt-qt551-trusty/ubuntu/dists/xenial/main/binary-amd64/Packages  404  Not Found

Do you guys know how to fix this?
Does splash support Ubuntu 16 Xenial? 

`install_deps () {
    # Install package dependencies.
    apt-add-repository -y ppa:beineri/opt-qt551-trusty && \
    apt-get update -q && \
    apt-get install -y --no-install-recommends \
        netbase \
        ca-certificates \
        xvfb \
        pkg-config \
        python3 \
        qt55base \
        qt55webkit \
        qt55svg \
        libre2 \
        libicu52 \
        liblua5.2-0 \
        zlib1g
}`

**Comment by kmike** [comment]
I haven't triedit with Ubuntu 16; provision script is for Ubuntu 14. But it looks like if you replace beineri's ppa with official Ubuntu 16 Qt packages it will work.

**Comment by yssoe** [comment]
on Ubuntu 16.04 Qt is 5.6 and when starting up  we get this error.
ImportError: No module named 'PyQt5.QtWebKit'

An explenation is that QtWebKit got deprecated upstream in Qt 5.5 and removed in 5.6.

**Comment by kmike** [comment]
@yssoe are you sure Ubuntu 16.04 uses QT 5.6? http://packages.ubuntu.com/xenial/qt5-default shows qt 5.5.1.

**Comment by yssoe** [comment]
@kmike You're right. I'm wrong. Sorry, I rest my case.

**Comment by kmike** [comment]
Splash Docker image (and provision.sh script) migrated to Ubuntu 16.04; this should be solved now.
