### ISSUE TITLE
tests fail with Twisted 16.3.0

### ISSUE THREAD

**Issue by kmike** [scrapinghub/splash#497]
test_client_disconnects.py tests fail for me with Twisted 16.3.0, but pass with Twisted 16.2.0 and 16.1.x. 

Currently Docker image uses Twisted 16.1.1, so it doesn't affect dockerized Splash (yet).

**Comment by ablepharus** [comment]
https://twistedmatrix.com/trac/ticket/8692 has been fixed july  [1](https://github.com/twisted/twisted/pull/833) and should be available in twisted-17.9.

**Comment by kmike** [comment]
Awesome, thanks for bringing this up @ablepharus! I wan under impression issue is "wontfix" and was not watching it.
