### ISSUE TITLE
Can't add cookie

### ISSUE THREAD

**Issue by tungpun** [scrapinghub/splash#500]
Using Splash v2.1 through the browser.
Here is my script:
```
function main(splash)
    splash:add_cookie("foo", "bar")
    assert(splash:go(splash.args.url))
    return splash:html()
end
```

Then, I use `netcat` to sniff HTTP request on the target host:
```
Connection from [172.16.110.1] port 8888 [tcp/*] accepted (family 2, sport 54730)
GET / HTTP/1.1
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8
User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/538.1 (KHTML, like Gecko) splash Safari/538.1
Connection: Keep-Alive
Accept-Encoding: gzip, deflate
Accept-Language: en,*
Host: 172.16.110.129:8888
```

I think that Cookie section `Cookie: foo=bar` should be displayed on the HTTP request.
But it doesn't.

I will kindly appreciate any help from you.

**Comment by tungpun** [comment]
Solved

**Comment by novoxudonoser** [comment]
I have same issue on 2.3 from docker. How you solved it ?

**Comment by tungpun** [comment]
@novoxudonoser you should include the path and hostname into cookie as well.
for example:
`splash:add_cookie("name", "bar", "/", "example.com")`
