### ISSUE TITLE
Splash can't get the correct results 

### ISSUE THREAD

**Issue by rossfan** [scrapinghub/splash#503]
I installed Splash using the way of "linux+docker" according to official instructions. I opened http://xxx.xxx.xxx.xxx:8050/ and input url http://www.mouser.cn/Search/Refine.aspx?Keyword=1156 without changing any other parameters. But I couldn't get the normal results just like Chome or  Firefox did.
Does any guys know how?

**Comment by farhan0581** [comment]
same issue here only difference was the url, which in my case was some https://someurl.com.

**Comment by kmike** [comment]
It worked for me the first time; the second time it showed a blank page because distil anti-bot protection was triggered. I'm not sure there is a Splash issue here.
