### ISSUE TITLE
how can i trigger .click() which is a event add by js "addEvent"

### ISSUE THREAD

**Issue by bigfuji** [scrapinghub/splash#504]
that HTML DOM has no click method and herf attr,its click method is add by js code like:
`addEvent( window, "load", function(){...
    addEvent( document.getElementById("btn"),
              "click",
              function(){....
`
how can i trigger this .click()?

**Comment by bigfuji** [comment]
that `addEvent(window, "load"...` seems did render in splash.

**Comment by kmike** [comment]
@bigfuji have you tried using http://splash.readthedocs.io/en/stable/scripting-ref.html#splash-mouse-click?

**Comment by bigfuji** [comment]
@kmike just tried,it didn't work.

**Comment by kmike** [comment]
Are you sure your js code (addEvent) works? The standard method is called [addEventListener](https://developer.mozilla.org/en/docs/Web/API/EventTarget/addEventListener).

**Comment by kmike** [comment]
I have no idea why isn't mouse_click working - are you clicking on a right coordinate? Can you try waiting after the click (as an example, or longer)?

**Comment by bigfuji** [comment]
yeah,it worked because there was some code before 'addEvent'
`var addEvent = function(elem, type, eventHandle) {
  if (elem == null || typeof(elem) == "undefined") return;
  if ( elem.addEventListener ) {
    elem.addEventListener( type, eventHandle, false );
  } else if ( elem.attachEvent ) {
    elem.attachEvent( "on" + type, eventHandle );
  } else {
    elem["on"+type]=eventHandle;
  }
};

addEvent( window, "load", function(){....`

**Comment by bigfuji** [comment]
i think i'm clicking on a right coordinate,and i waited for 2 seconds.
`    local get_dimensions = splash:jsfunc([[
        function () {
            var rect = document.getElementById('createaccountbtn').getBoundingClientRect();
            return {"x": rect.left, "y": rect.top}
        }
    ]])
    local dimensions = get_dimensions()
    splash:mouse_click(dimensions.x, dimensions.y)
    splash:wait(2)`

**Comment by bigfuji** [comment]
i think there is an script after Event"window.onload" and it didn't execute,that's why caused this problem.

**Comment by kmike** [comment]
> i think there is an script after Event"window.onload" and it didn't execute,that's why caused this problem.

If so, maybe adding splash:wait after splash:go can help? You can also try to detect a right time using JS code (e.g. listen to some event which fires when everything is ready); in this case [splash:wait_for_resume](http://splash.readthedocs.io/en/stable/scripting-ref.html#splash-wait-for-resume) may help to wait for a right amount of time; you can also write a loop and check if a page is ready periodically.

**Comment by bigfuji** [comment]
solved by add code:
`assert(splash:runjs("var event3 = new Event('load');window.dispatchEvent(event3);"))`
@kmike thanks for your replies.

**Comment by kmike** [comment]
I'm glad you have it working!
