### ISSUE TITLE
how to continue process the result of render? 

### ISSUE THREAD

**Issue by bigfuji** [scrapinghub/splash#506]
Is there a way to process the result of render?
Something like another request send to splash to execute?

**Comment by kmike** [comment]
Sorry, could you please clarify the question? You can send multiple requests to splash and process the results, what do you mean?

**Comment by bigfuji** [comment]
Sorry,didnt make myself clear.
I mean if i already get a result after execute a lua script,can i execute another lua script based on that result?
The situation is i need do something based on the first rendered webpage i get from splash in python to get a JavaScript code, then run it on the first render webpage to render second webpage.

**Comment by kmike** [comment]
> The situation is i need do something based on the first rendered webpage i get from splash in python to get a JavaScript code, then run it on the first render webpage to render second webpage.

No, this is not supported, i.e. you can't call to Python while the page is still loaded. If you need to keep page in memory then currently the way to go is to write the processing code in Lua or in JavaScript and execute it in a script itself.

**Comment by bigfuji** [comment]
OK,thanks for reply.
