### ISSUE TITLE
Splash stuck when maxrss  reached 

### ISSUE THREAD

**Issue by ohadedel** [scrapinghub/splash#510]
Hi, I have a recuring problem when using the splash that it has a problem shuting down when maxrss reached, i get this info from the log:

2016-10-10 03:45:29.307391 [-] maxrss exceeded 1000 MB, shutting down...
2016-10-10 03:45:29.309264 [twisted.web.server.Site] (TCP Port 8050 Closed)
2016-10-10 03:45:29.309517 [-] Stopping factory <twisted.web.server.Site object at 0x7fcfe98f2080>

It looks like the twisted is trying to shut down but it stuck, i have this issue reproduce over multiple containers, each one stops at the stopping factory after maxrss reached.

In the docker log i see this recurring message:
_**time="2016-10-10T06:06:34.038814802Z" level=info msg="Container d664989b12efef5474838185dd07c52c909d1e0469bdde327bd276e470c85061 failed to exit within 10 seconds of signal 15 - using the force"
time="2016-10-10T06:07:35.201101300Z" level=info msg="Container d664989b12efef5474838185dd07c52c909d1e0469bdde327bd276e470c85061 failed to exit within 10 seconds of signal 15 - using the force"
time="2016-10-10T06:08:35.604947815Z" level=info msg="Container...**_

also running "docker ps" gives me the fallowing status code for the dockers: "Restarting (0) 2 hours ago" Or "Restarting (137) 2 hours ago", in the one that has the message 137 i see right before the end this messages in the log:
**_QNetworkReplyImplPrivate::error: Internal problem, this method must only be called once.
QNetworkReplyImplPrivate::error: Internal problem, this method must only be called once.
QNetworkReplyImplPrivate::..._**

If there is any more information i can give please let me know, 
Any ideas?
Would it help to stop the docker myself and not use the maxrss?
Is there any work around to kill the dockers? force does not work on them... 
Thanks!

---------
**Update:**
I am cautiously optimistic, after two days of work without docker getting stuck i can say that what seemed to do the trick for me was to update a few of ubuntu components. i also threw to the mix update to the docker itself:
**_sudo apt-get install lxc wget bsdtar curl -y; sudo apt-get install linux-image-extra-$(uname -r) -y ; sudo modprobe aufs; curl -fsSL https://test.docker.com/ | sh"_**

**Comment by kmike** [comment]
Could it be the case docker itself is a problem? We had lot of problems with https://github.com/docker/docker/issues/5618

**Comment by ohadedel** [comment]
spoke to soon, still stuck, but from what i can see, it his a problem in the docker...
It looks like it has problem to un mount the folder the container uses, and so the restart fails.

Its very frustrating. i need t to work in production, but this kind of issues make me think that docker is not yet ready for that.
I see thread after thread of docker getting stuck. its really frustrating.

Can i run multi splash process out side of a docker? i think i will have to consider this soon.

**Comment by kmike** [comment]
@ohadedel yes, you can run multiple processes outside Docker; install steps for Ubuntu 14.04 are in https://github.com/scrapinghub/splash/blob/master/dockerfiles/splash/provision.sh file (it is also used in Docker container). To run multiple Splash instances on the same machine start them on different ports.

**Comment by bonifaciokid** [comment]
Even today, but I just change my USER_AGENT and it works, for now.
