### ISSUE TITLE
scrapy jupyter webkit not showing

### ISSUE THREAD

**Issue by Dauth** [scrapinghub/splash#511]
i am having the same issue as mentioned previously by @genius001  #361 and #376 whereby webkit is not showing up (installed using the manual way). Is there anway i can do to make this work?

 I have also tried the docker way but an error message displayed was shown below

No protocol specified
QXcbConnection: Could not connect to display unix:0

**Comment by acowpy** [comment]
I solved this by running

`xhost +local:docker`

to give docker the relevant permissions

**Comment by mcmino** [comment]
@acowpy this solution worked for me too! Thanks :D

**Comment by Gallaecio** [comment]
It may be worth covering in the documentation.

**Comment by Gallaecio** [comment]
Fixed by #903
