### ISSUE TITLE
https seems not supported?

### ISSUE THREAD

**Issue by dearvinitsr** [scrapinghub/splash#516]
Is there any support for https link crawling with scrapyrt?
With Scrapy command, data can be exported easily but Scrapyrt api not returning data for https link.

**Comment by kmike** [comment]
Sorry, is this a right repository? Did you mean https://github.com/scrapinghub/scrapyrt?

**Comment by dearvinitsr** [comment]
Hi kmike,

Apology. Yes, my bad. It is Scrapyrt.
