### ISSUE TITLE
Cache doesn't save full HAR, visible on second request on single page with 200 status code

### ISSUE THREAD

**Issue by gabrii** [scrapinghub/splash#519]
How to reproduce:
- Install splash==2.2.1
- Run "python -m splash.server"
- Visit http://localhost:8050/info?wait=0.5&images=1&expand=1&timeout=60.0&url=https%3A%2F%2Fraw.githubusercontent.com%2Fscrapinghub%2Fsplash%2Fmaster%2FLICENSE&lua_source=
- Note the HAR entry.
- Refresh page.
- Note there's no HAR entry.

Any setting or patch to disable the cache?

**Comment by kmike** [comment]
Hey @gabrii,

There is a PR to allow disabling cache (see https://github.com/scrapinghub/splash/issues/203 and https://github.com/scrapinghub/splash/pull/339), but it has some problems, so it is not merged. I don't have plans to pick it up soon; contributions ar welcome!

**Comment by gabrii** [comment]
Thanks for referencing the issues, I ended up patching a private fork with #339 for the moment.

**Comment by nramirezuy** [comment]
@gabrii Your fork isn't working for me, are you still using it?

**Comment by Gallaecio** [comment]
Closing in favor of https://github.com/scrapinghub/splash/issues/203
