### ISSUE TITLE
Are some sites not possible to scrap with splash

### ISSUE THREAD

**Issue by jeremyquinton** [scrapinghub/splash#520]
Hi. I use splash to scrap most javascript sites but I have one in particular that I cant seem to scrap. Im not sure if its splash or if the site has done something clever. The url in question is https://www.makro.co.za/liquor/bottles-LDA/pg1 

Out of interest if you load that page in a standard browser it changes the url but it doesn't seem to do a 301 redirect except it does some "magic" which changes the url. Using the render.png endpoint I get back an image which says loading for the website. I've set wait,resource_timeout and timeout to the highest possible values with no luck? 

Any suggestions on something else I can try. Screenshot attached. Dont seem to have the option to select question as the label for this issue. 
![screen shot 2016-11-02 at 09 39 38](https://cloud.githubusercontent.com/assets/1847770/19920330/cd56e29e-a0e0-11e6-9b55-4f16fbf80cb0.png)

**Comment by kmike** [comment]
It looks like this is the same issue as https://github.com/scrapinghub/splash/issues/221 - to render the website you need to disable Private Mode. 

```lua
function main(splash)
  local url = splash.args.url
  splash.private_mode_enabled = true
  assert(splash:go(url))
  assert(splash:wait(5))
  return {
    html = splash:html(),
    png = splash:png(),
    har = splash:har(),
  }
end
```

See http://splash.readthedocs.io/en/stable/faq.html#how-do-i-disable-private-mode.

**Comment by jeremyquinton** [comment]
@kmike thanks very much for the reply I genuinely appreciate it. Disabling private mode fixes the issue for me.
