### ISSUE TITLE
splash jupyter doesn't work after the first cell

### ISSUE THREAD

**Issue by hmnjeon** [scrapinghub/splash#525]
After running the first cell with
'''
splash:go("http://quotes.toscrape.com")
splash:wait(0.5)
'''
running anything in the second cell returns
TypeError("can't send non-None value to a just-started generator",).
I am not familiar with IPython, so I'm not sure I'm using it right. Am I using this wrong? Then, what should I do after that? The document doesn't say much about after installing splash-jupyter (e.g. you should define main function, or there is splash object already available, etc.).

**Comment by hmnjeon** [comment]
I can't seem to change the label to question. Please understand that I've tried :)

**Comment by hmnjeon** [comment]
Oh by the way I've installed splash-jupyter with docker

**Comment by kmike** [comment]
Yeah, I can reproduce this issue. Looking at it now.

**Comment by kmike** [comment]
Updated splash-jupyter image should be available in ~a hour.
