### ISSUE TITLE
Incomplete document in splash and jupyter section

### ISSUE THREAD

**Issue by hmnjeon** [scrapinghub/splash#526]
I am trying to setup splash-jupyter with webkit view. But instruction for docker installed version lacks explanation about $DISPLAY and $XAUTHORITY environment variables and /tmp/.X11-unix:/tmp/.X11-unix volume mapping. I don't know what to set for those two variables.

**Comment by kmike** [comment]
As I understand it, these variables should be already set in Linux. But I haven't tried the instructions myself. //cc @Youwotma

**Comment by Youwotma** [comment]
Yeah, they are already set in my system, I have:
```
XAUTHORITY=<my home>/.Xauthority
DISPLAY=:0.0
```

**Comment by hmnjeon** [comment]
Is there any way I can run this on mac os x then? Installing XQuartz and setting those variables to what @Youwotma suggests would suffice?

And could you explain the meaning and purpose of those variables please?

**Comment by Youwotma** [comment]
Unlikely that you can run it in OSX, but if it works let us know
