### ISSUE TITLE
PDF Request results in 504

### ISSUE THREAD

**Issue by wpxgit** [scrapinghub/splash#542]
If I try to crawl a website with PDFs Splash returns a 504 for each PDF-Request - as example: http://www.umd.edu/iTunesU/pdfs/iTunes_U_User_Guide.pdf
XLS also:
http://www.sample-videos.com/xls/Sample-Spreadsheet-100-rows.xls

Is it possible that splash downloads files instead of sending an 504?
I can't filter these requests out because not every filename of those files contains pdf or xls.

Thanks!

**Comment by kmike** [comment]
Hey,

Unfortunately this feature is not currently implemented (see https://github.com/scrapinghub/splash/issues/91); I'm closing this ticket in favor of #91.

As a workaround you may filter out requests based on their Content-Type header - check the second example in [splash:on_response_header](http://splash.readthedocs.io/en/stable/scripting-ref.html#splash-on-response-headers) docs.

**Comment by wpxgit** [comment]
Hey,

thanks for the feedback - haven't seen #91 

I've tried your workaround but it seems that splash doesn't have a response header for that file because it hasn't loaded it - if i try that code with the pdf mentioned above i still get a 504 Error :(
```
function main(splash)
    splash:on_response_headers(function(response)
        local content_type = response.headers["Content-Type"]
        if content_type == "application/pdf" then
            response.abort()
        end
    end)
    assert(splash:go(splash.args.url))
    return splash:png()
end
```

Can you give me any other hint how i can workaround that issue? Thanks!
