### ISSUE TITLE
Why splash can not download the whole page from this website? SOS!

### ISSUE THREAD

**Issue by icebear181818** [scrapinghub/splash#543]
Hey @kmike, i am sorry to bother you again, but i am running a tough project, which is really  beyond my capabilities. I need to crawl from [https://www.google.com/partners/#a_search;bdgt=10000;lang=en;locn=United%20States;motv=0;wbst=http%253A%252F%252F](url)

And it is a infinite scrolling page, when i used splash to pass the url with "#" to the parse function, it worked very well(pic 2), but for the response.body(pic 3), i found that it missed the most important content, which i need to crawl. so i rendered the page in splash by hand, sometimes i can see the entire page was downloaded(pic 1), sometimes it downloaded just the top and the bottom( i dont have the screen shot for it). I really can not find the reason, is it because it is a infinite scrolling page? or something wrong with my code?(pic 2 is the spider.py and pic 4 for the setting.py)? or it is a bug for splash? thank you so much for your help!!!!!!!!!!!
![1](https://cloud.githubusercontent.com/assets/20172214/20947951/4e78d134-bbc6-11e6-83a4-78e7721d000f.png)
![2](https://cloud.githubusercontent.com/assets/20172214/20947952/4f5afd34-bbc6-11e6-85b5-ff50a2f94167.png)
![3](https://cloud.githubusercontent.com/assets/20172214/20947954/523e23fa-bbc6-11e6-98c3-ad9167ddbcd1.png)
![4](https://cloud.githubusercontent.com/assets/20172214/20947955/53feaf84-bbc6-11e6-9e65-9ccea6ed33c2.png)

**Comment by wpxgit** [comment]
I reccomend you to use the splash webui before trying to render a page with scrapy. It better to debug - you then know if the scrapy plugin makes problems or it depends on flash...
Have you tried a higher wait value - if i try to catch the page with 0.5 i got no result - if i incrase it to 3 i got the full page...

**Comment by icebear181818** [comment]
@wpxgit thank you so much for your help!! i tried what you told me, i changed the wait value to 5, but it still doenst work, i really dont know why...since you can catch the entire page, it means something wrong with my code... could you please give me some hint?

**Comment by wpxgit** [comment]
Can you show me the lua script which is above right in the script button?

**Comment by icebear181818** [comment]
i think you are talking about this one, right?
![1](https://cloud.githubusercontent.com/assets/20172214/21024133/3d9b72d6-bd38-11e6-9435-0a74e6c7552a.png)
thank you so much Minions:P

**Comment by wpxgit** [comment]
And now change the splash:wait setting to 5 (or higher) instead of 0.5
This seems to happen because the anchor part of the url results in a sort of javascript rediect.

I've added some code which checks if there is an redirect and extends the wait time (got it from http://splash.readthedocs.io/en/stable/scripting-ref.html?highlight=redirect#splash-wait)

Try that Lua Script:
`function main(splash)
  local url = splash.args.url
  assert(splash:go(url))
  
  time = 0.5
  max_redirects = 10
    local redirects_remaining = max_redirects
    while redirects_remaining > 0 do
        local ok, reason = splash:wait{time=time, cancel_on_redirect=true}
        redirects_remaining = redirects_remaining - 1
    end

  
  return {
    html = splash:html(),
    png = splash:png(),
    har = splash:har(),
  }
end`

**Comment by icebear181818** [comment]
thank you Minions, and i tried what you said. it works!!!!!!wow!!!!!!!!!!finally!!!!!!!!
and i found that, if  you set the wait value too large, it will raise an "504 getaway time-out" error.
![1](https://cloud.githubusercontent.com/assets/20172214/21071710/1f3cb8c8-be5e-11e6-99eb-214623cd4ef3.png)
and i think time=2.5 is a perfect time for my project. 
Now i can continue my project, to solve the infinite scrolling page problem. 
![image](https://cloud.githubusercontent.com/assets/20172214/21071722/5316b22a-be5e-11e6-84d4-0d783ea67c4c.png)
i referred some code from github, and wrote the lua script myself. i am totally new to java, so the rendering result is not perfect. anyway ,i find a way to solve this problem
thank you soooooooooooooooooooo much again  :P

**Comment by kmike** [comment]
Thanks @wpxgit for the help!
