### ISSUE TITLE
QXcbIntegration: Cannot create platform offscreen surface, neither GLX nor EGL are enabled

### ISSUE THREAD

**Issue by kmike** [scrapinghub/splash#548]
Migrated from https://github.com/scrapy-plugins/scrapy-splash/issues/94:

Hi all:

When i crawled this page "http://www.mouser.cn/Electronic-Components",
Docker logs show errors below:
```
  QXcbIntegration: Cannot create platform offscreen surface, neither GLX nor EGL are enabled
  QXcbIntegration: Cannot create platform OpenGL context, neither GLX nor EGL are enabled
  QXcbIntegration: Cannot create platform offscreen surface, neither GLX nor EGL are enabled
  QXcbIntegration: Cannot create platform OpenGL context, neither GLX nor EGL are enabled
```
The website thinks javascript is not running and redirect to "http://www.mouser.cn//distil_r_captcha.html".
Anyone help?

PS:Other pages is ok, no 'QXcbIntegration' error shown.

**Comment by RHSman** [comment]
+1 for me
