### ISSUE TITLE
Splash can't load the site

### ISSUE THREAD

**Issue by Pavel001** [scrapinghub/splash#551]
Splash can't load the site
That page www.zomato.com fails to load in splash

**Comment by kmike** [comment]
It returns HTTP 403 error for me (Access Denied), it looks more like a protection measure, not a Splash bug.

**Comment by slotix** [comment]
I've tried to open the mentioned site several times from 3 default Scrapinghub/Splash container instances located at localhost, Digital Ocean and AWD EC2 Container accordingly.

Results:

> http://127.0.0.1:8050  - 200  everything is ok 
> Digital Ocean  - HTTP Error 504 (Gateway Time-out)
> AWS EC2 Container - 403 forbidden

User-Agent headers change has no effect.

Another site https://heureka.sk shows the following results:

> http://127.0.0.1:8050  - 200  everything is ok 
> Digital Ocean  - 200
> AWS EC2 Container - 403 forbidden

Why Splash acts differently for various  hosting providers?

**Comment by slotix** [comment]
I've found the reason of 403 response for the second site  https://heureka.sk 
They don't allow requests from US IP addresses. Splash  eu-central-1 based instance returned 200 status code.
