### ISSUE TITLE
ES version supported by Splash Javascript Engine

### ISSUE THREAD

**Issue by fbuchinger** [scrapinghub/splash#554]
What is the ECMAScript version supported by Splash? I assumed it was ES 6 (just like in Chrome), but then:
```
{
    "type": "ScriptError",
    "info": {
        "type": "JS_ERROR",
        "js_error": "TypeError: undefined is not a function (evaluating 'Object.assign({},{})')",
        "source": "[string \"function main(splash)\r...\"]",
        "error": "error during JS function call: \"TypeError: undefined is not a function (evaluating 'Object.assign({},{})')\"",
        "message": "[string \"function main(splash)\r...\"]:14: error during JS function call: \"TypeError: undefined is not a function (evaluating 'Object.assign({},{})')\"",
        "js_error_type": "TypeError",
        "js_error_message": "undefined is not a function (evaluating 'Object.assign({},{})')",
        "line_number": 14
    },
    "error": 400,
    "description": "Error happened while executing Lua script"
}
```
Array.forEach also doesn't seem to be supported. It would be really valuable if the capabilities of the integrated JS Engine were better documented.

**Comment by fbuchinger** [comment]
Ran [Kangax' ES5 and ES6 Compatibility Tables](http://kangax.github.io/es5-compat-table) in a Splash container and found out that Splash 2.3 supports 95% of the ES5 features, but only 4% of the ES6 features. Thus, no `Object.assign()`, Array.forEach should be supported, though.

**Comment by kmike** [comment]
@fbuchinger currently Splash uses WebKit provided by Qt 5.5.1; this webkit is quite old (2013 if I recall it correctly). I'm going to try to update the engine for the next release (see also https://github.com/scrapinghub/splash/issues/541), but there is no timeframe for that.

**Comment by fbuchinger** [comment]
Thank you, @kmike! Glad to see this splash update coming, meanwhile I will work around the issue.
