### ISSUE TITLE
Can't add cookie

### ISSUE THREAD

**Issue by novoxudonoser** [scrapinghub/splash#555]
I have same issue as [here](https://github.com/scrapinghub/splash/issues/500). I use Splash v2.3 from docker.

The code:
```
function main(splash)
    splash:add_cookie("foo", "bar")
    assert(splash:go(splash.args.url))
    return splash:html()
end
```

The request:

```
Connection from [172.16.110.1] port 8888 [tcp/*] accepted (family 2, sport 54730)
GET / HTTP/1.1
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8
User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/538.1 (KHTML, like Gecko) splash Safari/538.1
Connection: Keep-Alive
Accept-Encoding: gzip, deflate
Accept-Language: en,*
Host: 172.16.110.129:8888
```

I expect The `Coockie` header with `foo=bar` in request

**Comment by novoxudonoser** [comment]
It is working, the cookies are ok, they are not displaing in web interface.

**Comment by kmike** [comment]
@novoxudonoser thanks for checking that! If cookies are not in the UI then this is a bug; I'm opening another ticket for that: https://github.com/scrapinghub/splash/issues/556
