### ISSUE TITLE
select not working

### ISSUE THREAD

**Issue by novoxudonoser** [scrapinghub/splash#557]
My code:

```
function main(splash)
  assert(splash:go("http://google.com"))
  assert(splash:wait(0.5))
  return {
    a = splash:select("div"), 
    html = splash:html(),
    png = splash:png(),
    har = splash:har(),
  }
end
```

I get:
```
HTTP Error 400 (Bad Request)

Type: ScriptError -> LUA_ERROR

Error happened while executing Lua script

Lua error: [string "function main(splash)
..."]:5: attempt to call method 'select' (a nil value)
```

I used splash 2.3,2.2, master. Am I doing something wrong?

**Comment by kmike** [comment]
`attempt to call method 'select' (a nil value)` this should happen with Splash 2.2, but not in Spash 2.3 - the feature is new in Splash 2.3. Could you please check that the docker image is up to date?

**Comment by novoxudonoser** [comment]
I use scrapinghub/splash:latest it should be 2.3, and it has 2.3 in web interface.

**Comment by kmike** [comment]
For me Splash 2.3 returns the following error:

```
{
    "description": "Error happened while executing Lua script",
    "error": 400,
    "type": "ScriptError",
    "info": {
        "type": "BAD_MAIN_ERROR",
        "message": "'main' returned bad result. Lua function objects are not allowed."
    }
}
```

-- this happens because splash:select() returns a Lua object, and there is no default way to serialize it to JSON. You may want to return e.g. `splash:select("div").node.outerHTML` instead. 

Hm, maybe .node.outerHTML is a good default for serializing splash:select results, and we should add it to Splash.

**Comment by kmike** [comment]
@novoxudonoser have you got it working? Can I close the ticket?

**Comment by EswarL** [comment]
@kmike I came across a similar scenario and  this "splash:select("div").node.outerHTML" works !

Thanks

**Comment by kmike** [comment]
Closing it in favor of https://github.com/scrapinghub/splash/issues/564.
