### ISSUE TITLE
Rest call while processing page in splash?

### ISSUE THREAD

**Issue by novoxudonoser** [scrapinghub/splash#558]
Is there any way to make rest api call from lua script?

**Comment by kmike** [comment]
There are [splash:http_get](http://splash.readthedocs.io/en/stable/scripting-ref.html#splash-http-get) and [splash:http_post](http://splash.readthedocs.io/en/stable/scripting-ref.html#splash-http-post) methods. Other methods are not directly supported right now, but one can also do an API call from JavaScript. 

You may also find json module useful (http://splash.readthedocs.io/en/stable/scripting-libs.html#json).
