### ISSUE TITLE
Exposing headers between splash and destination on request.* endpoints

### ISSUE THREAD

**Issue by wflanagan** [scrapinghub/splash#562]
In the case of a proxied connection (and maybe not as well), there are headers that are often required for items such as Rate Limits, acceptability for iFraming, etc, legal compliance, etc.  

Through the request.* url paths, I do not see any way to reach these (particularly the request.json method).  

Am I missing something? Is this difficult to do?

**Comment by kmike** [comment]
Hey @wflanagan,

Do you want to access headers set by a proxy, or to set headers for the proxy?

In case of /render.json you can access response headers by setting ['har'](http://splash.readthedocs.io/en/stable/api.html#arg-har) argument to 1. It will provide 'har' key in the result, with response data in http://www.softwareishard.com/blog/har-12-spec/ format; it includes all response headers.

For setting headers there is [`headers`](http://splash.readthedocs.io/en/stable/api.html#arg-headers) argument.

You can also do all of this in /execute endpoint; it provides a bit more flexibility - e.g. you can use splash:on_response_headers or splash:on_response to store response headers without returning all other data HAR contains.

**Comment by wflanagan** [comment]
I want the header RESPONSES between Splash and the final destination.  Not
the ones between my client and Splash.

Without these headers, you don’t know the content type that is returned to
you. For example, if you query through the render.json, you get a content
type of application/json, naturally, But, if you have a unique content type
that it’s actually retrieving, you have no way to know without poking the
content to see what it looks like (which is how I’m getting around this
now).

Yes, I’m sure if I wrote a Lua script and passed that.. I can do all sorts
of things. But, my application logic just needs the basic body and header
information… at some point, i’ll write some Lua scripts to further
optimize.  But, in terms of drop in.. this is what i’m looking for.

 I already set the outbound headers.

WF

**Comment by kmike** [comment]
> But, my application logic just needs the basic body and header information

har=1 should give this information for render.json endpoint. If you need bodies of all responses (not only headers and HTTP status codes) you can pass [response_body=1](http://splash.readthedocs.io/en/stable/api.html#arg-response-body) argument.

**Comment by wflanagan** [comment]
This is correct.. and this works. I'll close this ticket.
