### ISSUE TITLE
Cannot use splash:set_user_agent when using proxy.

### ISSUE THREAD

**Issue by philippe2803** [scrapinghub/splash#563]
Been struggling quite a bit today on the 'execute' endpoint. I have got a very simple Lua script which goes to a page, make a search, submit and reach the search page. 

The script works perfectly without proxy and also with proxy (the proxy is submitted with the proxy arg). However, when I try to add a User-Agent with splash:set_user_agent within the Lua script, I get the following error:

    {
	"type": "ScriptError",
	"error": 400,
	"description": "Error happened while executing Lua script",
	"info": {
		"source": "[string \"function main(splash)...\"]",
		"type": "LUA_ERROR",
		"error": "JsError({'js_error_type': 'TypeError', 'type': 'JS_ERROR', 'message': 'JS error: \"TypeError: undefined is not an object (evaluating \\'rect.left\\')\"', 'js_error': \"TypeError: undefined is not an object (evaluating 'rect.left')\", 'js_error_message': \"undefined is not an object (evaluating 'rect.left')\"},)",
		"message": "Lua error: [string \"function main(splash)...\"]:12: JsError({'js_error_type': 'TypeError', 'type': 'JS_ERROR', 'message': 'JS error: \"TypeError: undefined is not an object (evaluating \\'rect.left\\')\"', 'js_error': \"TypeError: undefined is not an object (evaluating 'rect.left')\", 'js_error_message': \"undefined is not an object (evaluating 'rect.left')\"},)",
		"line_number": 12
	}
}

The user-agent is also added as an argument and then used in Lua script with splash.args.user_agent. Surprisingly, if I do NOT submit a proxy, the script runs perfectly and the user-agent is passed normally.

I basically have to choose between using proxies OR changing the user-agent. That does seem really counter effective to me.

I also tried using the method splash:set_custom_headers and have exactly the same behavior.

**Comment by kmike** [comment]
What proxy are you using? Some proxies change User-Agent themselves.

**Comment by philippe2803** [comment]
I'm using dedicated proxies from buyproxies.org. I've already changed UAs with those IPs before (or so I thought). 

I went through Splash documentation, and it seems I could handle both user-agent and proxy within the Lua script, using a splash:on_request function. I'll try this and come back here with the results.

**Comment by Gallaecio** [comment]
Shall we assume it worked?
