### ISSUE TITLE
How to handle querystrings in the url?

### ISSUE THREAD

**Issue by amirj** [scrapinghub/splash#566]
I'm going to render a url which contains some querystring, for example the following url should render the second page '/PageNo-2':
https://www.digikala.com/Search#!/PageNo-2/
After rendering this page using the web interface, only the first page is shown (https://www.digikala.com/Search#!/)
Why?

**Comment by kmike** [comment]
I can't reproduce it, website redirects to https://www.digikala.com/Search?pageno=2 and shows a second page for me, both in Splash and in Firefox.
