### ISSUE TITLE
Docker installation on Mac part need to be updated

### ISSUE THREAD

**Issue by lawulu** [scrapinghub/splash#567]
https://github.com/scrapinghub/splash/blob/master/docs/install.rst

The default and recommended way to install docker on Mac is using 'Docker for Mac' rather than the Docker toolbox.

As mentioned in https://docs.docker.com/docker-for-mac/docker-toolbox/#/the-docker-toolbox-environment. Docker for Mac doesn't need to create the docker-machine.
> The Docker for Mac application does not use docker-machine to provision that VM; but rather creates and manages it directly.

The instructions on the doc is confused.
`➜  00 docker-machine create --driver virtualbox default                   
Running pre-create checks...
Error with pre-create check: "VBoxManage not found. Make sure VirtualBox is installed and VBoxManage is in the path"
➜  00 docker-machine create  default
Usage: docker-machine create [OPTIONS] [arg...]

Create a machine

Description:
   Run 'docker-machine create --driver name' to include the create flags for that driver in the help text.

Options:
   
   --driver, -d "none"											Driver to create machine with. [$MACHINE_DRIVER]
   --engine-install-url "https://get.docker.com"							Custom URL to use for engine installation [$MACHINE_DOCKER_INSTALL_URL]
   --engine-opt [--engine-opt option --engine-opt option]						Specify arbitrary flags to include with the created engine in the form flag=value
   --engine-insecure-registry [--engine-insecure-registry option --engine-insecure-registry option]	Specify insecure registries to allow with the created engine
   --engine-registry-mirror [--engine-registry-mirror option --engine-registry-mirror option]		Specify registry mirrors to use [$ENGINE_REGISTRY_MIRROR]
   --engine-label [--engine-label option --engine-label option]						Specify labels for the created engine
   --engine-storage-driver 										Specify a storage driver to use with the engine
   --engine-env [--engine-env option --engine-env option]						Specify environment variables to set in the engine
   --swarm												Configure Machine to join a Swarm cluster
   --swarm-image "swarm:latest"										Specify Docker image to use for Swarm [$MACHINE_SWARM_IMAGE]
   --swarm-master											Configure Machine to be a Swarm master
   --swarm-discovery 											Discovery service to use with Swarm
   --swarm-strategy "spread"										Define a default scheduling strategy for Swarm
   --swarm-opt [--swarm-opt option --swarm-opt option]							Define arbitrary flags for Swarm master
   --swarm-join-opt [--swarm-join-opt option --swarm-join-opt option]					Define arbitrary flags for Swarm join
   --swarm-host "tcp://0.0.0.0:3376"									ip/socket to listen on for Swarm master
   --swarm-addr 											addr to advertise for Swarm (default: detect and use the machine IP)
   --swarm-experimental											Enable Swarm experimental features
   --tls-san [--tls-san option --tls-san option]`

**Comment by kmike** [comment]
Instructions are updated in https://github.com/scrapinghub/splash/pull/614.
