### ISSUE TITLE
400 on execute

### ISSUE THREAD

**Issue by qw34ty** [scrapinghub/splash#573]
Hi can anyone please advise on troubleshooting 400 ERROR on posting to /execute? Getting the following errors with POST to /execute, using latest stable version of splash.

`[scrapy_splash.middleware] Bad request to Splash: {u'info': {u'description': u'Argument is out of the allowed range', u'min': 0, u'max': 60.0, u'argument': u'timeout', u'value': 600.0, u'type': u'bad_argument'}, u'type': u'BadOption', u'description': u'Incorrect HTTP API arguments', u'error': 400}`

`status = 400, headers = {'Date': ['Thu, 02 Mar 2017 05:07:39 GMT'], 'Content-Type': ['application/json'], 'Server': ['nginx/1.10.1']}, body={"info": {"max": 60.0, "value": 600.0, "min": 0, "type": "bad_argument", "argument": "timeout", "description": "Argument is out of the allowed range"}, "type": "BadOption", "error": 400, "description": "Incorrect HTTP API arguments"}`

**Comment by redapple** [comment]
The error is explicit (in this case): 
```
{u'info': {u'argument': u'timeout',
           u'description': u'Argument is out of the allowed range',
           u'max': 60.0,
           u'min': 0,
           u'type': u'bad_argument',
           u'value': 600.0}}
```

You set `timeout` to 600 while the max is 60.

**Comment by qw34ty** [comment]
Hi there,, thanks for the feedback! Is there a way to increase timeout values for splash server?

**Comment by redapple** [comment]
Check http://splash.readthedocs.io/en/stable/faq.html#i-m-getting-lots-of-504-timeout-errors-please-help:

`$ docker run -it -p 8050:8050 scrapinghub/splash --max-timeout 3600`

**Comment by qw34ty** [comment]
Thanks,. yeah just saw that myself! Can please close this request.

**Comment by redapple** [comment]
It is closed already.
