### ISSUE TITLE
HTTP Error 504 (Gateway Time-out):Type: GlobalTimeoutError

### ISSUE THREAD

**Issue by rava-dosa** [scrapinghub/splash#576]
**Splash version 2.3.2**
**I'm behind college proxy . This might be one of the reason for this timeout as you have previously(issue 242) mentioned that "Splash" doesn't consider environment variables.I also tried to hardcore lua but nothing happened(it throws some error).**
```
{
    "type": "GlobalTimeoutError",
    "description": "Timeout exceeded rendering page",
    "error": 504,
    "info": {
        "timeout": 60
    }
}
``` 
**How I hardcored lua**
```
function main(splash)
  local url = splash.args.url
  request:set_proxy{
      host = "mydomain.crawlera.com(this was my college proxy ip)",
      port = 8010,
    }
  assert(splash:go(url))
  assert(splash:wait(0.5))
  return {
    html = splash:html(),
    png = splash:png(),
    har = splash:har(),
  }
end
```
**Error it threw**
```
{
    "type": "ScriptError",
    "description": "Error happened while executing Lua script",
    "error": 400,
    "info": {
        "line_number": 3,
        "type": "LUA_ERROR",
        "error": "attempt to index global 'request' (a nil value)",
        "source": "[string \"function main(splash)\r...\"]",
        "message": "Lua error: [string \"function main(splash)\r...\"]:3: attempt to index global 'request' (a nil value)"
    }
}
```
Now how to set my college proxy ? You have  definitely encountered this problem before ?

**Comment by kmike** [comment]
There is a problem in the script: as error message said, `request` variable is nil. It happens because you need to get this request object from somewhere. `request:set_proxy` should be called in `splash:on_request` callback, not in the main function. See http://splash.readthedocs.io/en/stable/scripting-ref.html#splash-on-request and http://splash.readthedocs.io/en/stable/scripting-request-object.html#request-object.

**Comment by rava-dosa** [comment]
@kmike Solved
```
function main(splash)
  splash:on_request(function(request)
    request:set_proxy{
        host = "10.3.100.207",
        port = 8080,
        username = splash.args.username,
        password = splash.args.password,
    }
end)
  local url = splash.args.url
  assert(splash:go(url))
  assert(splash:wait(0.5))
  return {
    html = splash:html(),
    png = splash:png(),
    har = splash:har(),
  }
end
```

**Comment by totruong1996** [comment]
i have a problem. can you help me {"error": 504, "description": "Timeout exceeded rendering page", "type": "GlobalTimeoutError", "info": {"timeout": 30}}
link http://localhost:8050/render.html?url=https://www.vntrip.vn/khach-san/ha-noi
