### ISSUE TITLE
element:mouse_click() doesn't work when element uses border-radius

### ISSUE THREAD

**Issue by stummjr** [scrapinghub/splash#577]
Consider this page: http://quotes.toscrape.com/js-onclick

I tried to follow the pagination button in the bottom of the page with this script, but it didn't work:

```
function main(splash)
  local url = splash.args.url
  assert(splash:go(url))
  splash:set_viewport_full()
  assert(splash:wait(0.5))
  splash:select("li.next > a"):mouse_click()
  splash:wait(0.5)
  return {
    html = splash:html(),
    png = splash:png(),
    har = splash:har(),
  }
end
```

The issue is that the pagination button has `border-radius` set and `mouse_click()` clicks on top left of the element, so the event is not being fired, as @kmike explained to me.

To fix that, I had to pass (x,y) coordinates to `mouse_click`:  `splash:select("li.next > a"):mouse_click(10, 10)`.

**Comment by i6666800** [comment]
One button and two buttons perform mouse_click respectively, only one click event will take effect
