### ISSUE TITLE
element:mouse_click() doesn't work when element is not in the page's visible area

### ISSUE THREAD

**Issue by stummjr** [scrapinghub/splash#578]
I tried executing this:

```splash:select("li.next > a"):mouse_click(10,10)```

But it didn't work because the element wasn't visible in the viewport. This [method's documentation](http://splash.readthedocs.io/en/stable/scripting-element-object.html#element-mouse-click) doesn't mention this constraint, though.

Is there any chance of changing the default behavior to scrolling down to the element when `mouse_click()` is called on it?

**Comment by kmike** [comment]
Fixed by #633.
