### ISSUE TITLE
Step by Step partial porting to Qt webengine#1:With reference to issue #349

### ISSUE THREAD

**Issue by rava-dosa** [scrapinghub/splash#579]
As I'm new to this project can you refer to a starting point , that how & where  can I start.
Like refer me some links to study . I have also studied but couldn't get a good overview.

[Porting to Qt web engine](https://wiki.qt.io/Porting_from_QtWebKit_to_QtWebEngine)

As I'm improving my familiarity with the code base if  you can refer to some files of this project where can I start It would help in speedtrack in solving this issue .  
@kmike

**Comment by rava-dosa** [comment]
@kmike I would like to ask that as per issue 349 you mentioned that "we shoudn't drop QtWebKit support, QtWebEngine should be an addition, not a replacement" . Like for this task to be implemented major problem is that inside the splash package Qt webkit is used . So we can't use it explicitly.
So to do** "If I'd be starting with this project I'd create a super-basic version of this new WebEngineBrowserTab"** this like how should I send PR & to which branch ? Inside the splash codebase , if you have any specific preference for name of directory in which I will add codes ?
As basic interface of qt webengine is in C++ hence for python wrapper Of It I've found one link & one issue .Issue first http://stackoverflow.com/questions/33108133/how-to-build-qt-webengine-for-pyqt5
https://github.com/rodrigogolive/WebEngineWrapper
Please comment

**Comment by kmike** [comment]
Hey @rava-dosa!

> So to do "If I'd be starting with this project I'd create a super-basic version of this new WebEngineBrowserTab" this like how should I send PR & to which branch ? Inside the splash codebase , if you have any specific preference for name of directory in which I will add codes ?

Please fork Splash, create a new branch in your repository and send a pull reuest against Splash master. I think there is no need to create new folders, but you may have to split `browser_tab.py` file into two or three files (e.g. for base browser tab, webkit-based browser tab and webengine-based browser tab).

> As basic interface of qt webengine is in C++ hence for python wrapper Of It I've found one link & one issue .Issue first http://stackoverflow.com/questions/33108133/how-to-build-qt-webengine-for-pyqt5

PyQt5 provides QtWebEngine bindings in recent versions, it shouldn't be a problem.

**Comment by rava-dosa** [comment]
@kmike I've been working to find out a way to have QTwebengine built on my pc but without success . I've been following this link [Trying QtWebengine](https://wiki.qt.io/How_to_Try_QtWebEngine).
```
(check) apoorva@apoorva-Dell-System-XPS-L502X:~/Desktop/gsoc/qtwebengine$ qmake -r
WARNING: /home/apoorva/Desktop/gsoc/qtwebengine/qtwebengine.pro:1: Unable to find file for inclusion qt_parts
/home/apoorva/Desktop/gsoc/qtwebengine/qtwebengine.pro:3: Unknown test function: isPlatformSupported

```
As it was warning I went further to make 

```
(check) apoorva@apoorva-Dell-System-XPS-L502X:~/Desktop/gsoc/qtwebengine$ make
g++ -m64 -Wl,-O1 -o qtwebengine     -L/usr/lib/x86_64-linux-gnu -lQtGui -lQtCore -lpthread 
/usr/bin/ld: /usr/lib/debug/usr/lib/x86_64-linux-gnu/crt1.o(.debug_info): relocation 0 has invalid symbol index 11
/usr/bin/ld: /usr/lib/debug/usr/lib/x86_64-linux-gnu/crt1.o(.debug_info): relocation 1 has invalid symbol index 12
/usr/bin/ld: /usr/lib/debug/usr/lib/x86_64-linux-gnu/crt1.o(.debug_info): relocation 2 has invalid symbol index 2
/usr/bin/ld: /usr/lib/debug/usr/lib/x86_64-linux-gnu/crt1.o(.debug_info): relocation 3 has invalid symbol index 2
/usr/bin/ld: /usr/lib/debug/usr/lib/x86_64-linux-gnu/crt1.o(.debug_info): relocation 4 has invalid symbol index 11
/usr/bin/ld: /usr/lib/debug/usr/lib/x86_64-linux-gnu/crt1.o(.debug_info): relocation 5 has invalid symbol index 13
/usr/bin/ld: /usr/lib/debug/usr/lib/x86_64-linux-gnu/crt1.o(.debug_info): relocation 6 has invalid symbol index 13
/usr/bin/ld: /usr/lib/debug/usr/lib/x86_64-linux-gnu/crt1.o(.debug_info): relocation 7 has invalid symbol index 13
/usr/bin/ld: /usr/lib/debug/usr/lib/x86_64-linux-gnu/crt1.o(.debug_info): relocation 8 has invalid symbol index 12
/usr/bin/ld: /usr/lib/debug/usr/lib/x86_64-linux-gnu/crt1.o(.debug_info): relocation 9 has invalid symbol index 13
/usr/bin/ld: /usr/lib/debug/usr/lib/x86_64-linux-gnu/crt1.o(.debug_info): relocation 10 has invalid symbol index 13
/usr/bin/ld: /usr/lib/debug/usr/lib/x86_64-linux-gnu/crt1.o(.debug_info): relocation 11 has invalid symbol index 13
/usr/bin/ld: /usr/lib/debug/usr/lib/x86_64-linux-gnu/crt1.o(.debug_info): relocation 12 has invalid symbol index 13
/usr/bin/ld: /usr/lib/debug/usr/lib/x86_64-linux-gnu/crt1.o(.debug_info): relocation 13 has invalid symbol index 13
/usr/bin/ld: /usr/lib/debug/usr/lib/x86_64-linux-gnu/crt1.o(.debug_info): relocation 14 has invalid symbol index 13
/usr/bin/ld: /usr/lib/debug/usr/lib/x86_64-linux-gnu/crt1.o(.debug_info): relocation 15 has invalid symbol index 13
/usr/bin/ld: /usr/lib/debug/usr/lib/x86_64-linux-gnu/crt1.o(.debug_info): relocation 16 has invalid symbol index 13
/usr/bin/ld: /usr/lib/debug/usr/lib/x86_64-linux-gnu/crt1.o(.debug_info): relocation 17 has invalid symbol index 13
/usr/bin/ld: /usr/lib/debug/usr/lib/x86_64-linux-gnu/crt1.o(.debug_info): relocation 18 has invalid symbol index 13
/usr/bin/ld: /usr/lib/debug/usr/lib/x86_64-linux-gnu/crt1.o(.debug_info): relocation 19 has invalid symbol index 21
/usr/bin/ld: /usr/lib/debug/usr/lib/x86_64-linux-gnu/crt1.o(.debug_line): relocation 0 has invalid symbol index 2
/usr/lib/gcc/x86_64-linux-gnu/4.8/../../../x86_64-linux-gnu/crt1.o: In function `_start':
(.text+0x20): undefined reference to `main'
collect2: error: ld returned 1 exit status
make: *** [qtwebengine] Error 1
```
Even though my environment is having Qt 5.5.1 & as per this link [QT 5.5](http://blog.qt.io/blog/2015/07/01/qt-5-5-released/) or this [New features in QT 5.5](https://wiki.qt.io/New_Features_in_Qt_5.5) my installed bindings should have qt webengine by defaults but when I'm using interpreter
then
```
>>> from PyQt5 import QtWebEngineWidgets
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: cannot import name 'QtWebEngineWidgets'
```
But this is working fine 
```
>>> from PyQt5 import QtWebKitWidgets
>>> 

```
Now how to deal with this problem ?
I have visited this links as well http://www.ics.com/blog/building-qtwebengine
But the cloning link was not working.

**Comment by rava-dosa** [comment]
@kmike @pawelmhm Have anyone faced this problem ? How to initialize my coding environment for QtWebengine in python virtual environment ?

**Comment by kmike** [comment]
@rava-dosa sorry, I don't know how to help; you need to figure out this yourselves. On my machine I just followed Qt 5.5.1 and PyQt 5.5.1 installation guides, and it worked out of the box.

**Comment by kmike** [comment]
But yeah, I'm not sure it works in a virtual environment, getting it running there could be more tricky.

**Comment by hbakhtiyor** [comment]
@rava-dosa any updates of your great works?

**Comment by kmike** [comment]
Closing it in favor of #614 for now.
