### ISSUE TITLE
python2.7.11 install splash failed

### ISSUE THREAD

**Issue by francisar** [scrapinghub/splash#580]
[root@V-10-177-138-14 /data/splash-2.3]# /usr/local/services/tjop_python/bin/python setup.py install
running install
running bdist_egg
running egg_info
creating splash.egg-info
writing requirements to splash.egg-info/requires.txt
writing splash.egg-info/PKG-INFO
writing top-level names to splash.egg-info/top_level.txt
writing dependency_links to splash.egg-info/dependency_links.txt
writing manifest file 'splash.egg-info/SOURCES.txt'
reading manifest file 'splash.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
warning: no files found matching '*.rst' under directory 'splash/lua_modules'
warning: no files found matching '*.txt' under directory 'splash/lua_modules'
warning: no files found matching '*.js' under directory 'splash/vendor/harviewer/webapp'
warning: no files found matching '*.html' under directory 'splash/vendor/harviewer/webapp'
warning: no files found matching '*.css' under directory 'splash/vendor/harviewer/webapp'
warning: no files found matching '*.gif' under directory 'splash/vendor/harviewer/webapp'
warning: no files found matching '*.png' under directory 'splash/vendor/harviewer/webapp'
warning: no files found matching '*.swf' under directory 'splash/vendor/harviewer/webapp'
warning: no files found matching '*.html' under directory 'splash/vendor/harviewer/webapp'
writing manifest file 'splash.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-x86_64/egg
running install_lib
running build_py
creating build
creating build/lib
creating build/lib/splash
copying splash/jsutils.py -> build/lib/splash
copying splash/argument_cache.py -> build/lib/splash
copying splash/defaults.py -> build/lib/splash
copying splash/pool.py -> build/lib/splash
copying splash/lua.py -> build/lib/splash
copying splash/exceptions.py -> build/lib/splash
copying splash/sentry.py -> build/lib/splash
copying splash/qtrender_image.py -> build/lib/splash
copying splash/request_middleware.py -> build/lib/splash
copying splash/xvfb.py -> build/lib/splash
copying splash/html_element.py -> build/lib/splash
copying splash/qtutils.py -> build/lib/splash
copying splash/proxy.py -> build/lib/splash
copying splash/qtrender_lua.py -> build/lib/splash
copying splash/har_builder.py -> build/lib/splash
copying splash/casperjs_utils.py -> build/lib/splash
copying splash/__init__.py -> build/lib/splash
copying splash/network_manager.py -> build/lib/splash
copying splash/render_options.py -> build/lib/splash
copying splash/resources.py -> build/lib/splash
copying splash/lua_runner.py -> build/lib/splash
copying splash/qtrender.py -> build/lib/splash
copying splash/conftest.py -> build/lib/splash
copying splash/utils.py -> build/lib/splash
copying splash/qwebpage.py -> build/lib/splash
copying splash/cookies.py -> build/lib/splash
copying splash/server.py -> build/lib/splash
copying splash/lua_runtime.py -> build/lib/splash
copying splash/browser_tab.py -> build/lib/splash
copying splash/response_middleware.py -> build/lib/splash
creating build/lib/splash/har
copying splash/har/__init__.py -> build/lib/splash/har
copying splash/har/schema.py -> build/lib/splash/har
copying splash/har/qt.py -> build/lib/splash/har
copying splash/har/utils.py -> build/lib/splash/har
copying splash/har/log.py -> build/lib/splash/har
creating build/lib/splash/kernel
copying splash/kernel/__main__.py -> build/lib/splash/kernel
copying splash/kernel/kernel.py -> build/lib/splash/kernel
copying splash/kernel/completer.py -> build/lib/splash/kernel
copying splash/kernel/__init__.py -> build/lib/splash/kernel
copying splash/kernel/lua_parser.py -> build/lib/splash/kernel
copying splash/kernel/errors.py -> build/lib/splash/kernel
copying splash/kernel/inspections.py -> build/lib/splash/kernel
copying splash/kernel/kernelbase.py -> build/lib/splash/kernel
creating build/lib/splash/ui
copying splash/ui/style.css -> build/lib/splash/ui
copying splash/ui/main.js -> build/lib/splash/ui
copying splash/ui/favicon.ico -> build/lib/splash/ui
creating build/lib/splash/examples
copying splash/examples/har.lua -> build/lib/splash/examples
copying splash/examples/block-css.lua -> build/lib/splash/examples
copying splash/examples/disable-images.lua -> build/lib/splash/examples
copying splash/examples/scroll.lua -> build/lib/splash/examples
copying splash/examples/wait-for-element.lua -> build/lib/splash/examples
copying splash/examples/run-js.lua -> build/lib/splash/examples
copying splash/examples/render-png.lua -> build/lib/splash/examples
copying splash/examples/element-screenshot.lua -> build/lib/splash/examples
copying splash/examples/with-timeout.lua -> build/lib/splash/examples
copying splash/examples/submit-search.lua -> build/lib/splash/examples
copying splash/examples/count-divs.lua -> build/lib/splash/examples
copying splash/examples/return-title.lua -> build/lib/splash/examples
copying splash/examples/phantomjs-follow.lua -> build/lib/splash/examples
copying splash/examples/preload-functions.lua -> build/lib/splash/examples
copying splash/examples/log-requests.lua -> build/lib/splash/examples
copying splash/examples/call-later.lua -> build/lib/splash/examples
copying splash/examples/multiple-pages.lua -> build/lib/splash/examples
copying splash/examples/preload-jquery.lua -> build/lib/splash/examples
creating build/lib/splash/lua_modules
copying splash/lua_modules/repr.lua -> build/lib/splash/lua_modules
copying splash/lua_modules/element.lua -> build/lib/splash/lua_modules
copying splash/lua_modules/response.lua -> build/lib/splash/lua_modules
copying splash/lua_modules/splash.lua -> build/lib/splash/lua_modules
copying splash/lua_modules/extras.lua -> build/lib/splash/lua_modules
copying splash/lua_modules/event.lua -> build/lib/splash/lua_modules
copying splash/lua_modules/completer.lua -> build/lib/splash/lua_modules
copying splash/lua_modules/wraputils.lua -> build/lib/splash/lua_modules
copying splash/lua_modules/sandbox.lua -> build/lib/splash/lua_modules
copying splash/lua_modules/request.lua -> build/lib/splash/lua_modules
creating build/lib/splash/lua_modules/libs
copying splash/lua_modules/libs/treat.lua -> build/lib/splash/lua_modules/libs
copying splash/lua_modules/libs/json.lua -> build/lib/splash/lua_modules/libs
copying splash/lua_modules/libs/base64.lua -> build/lib/splash/lua_modules/libs
creating build/lib/splash/lua_modules/vendor
copying splash/lua_modules/vendor/lexer.lua -> build/lib/splash/lua_modules/vendor
copying splash/lua_modules/vendor/inspect.lua -> build/lib/splash/lua_modules/vendor
creating build/lib/splash/kernel/inspections
copying splash/kernel/inspections/splash.json -> build/lib/splash/kernel/inspections
copying splash/kernel/inspections/splash-auto.json -> build/lib/splash/kernel/inspections
creating build/lib/splash/kernel/kernels
creating build/lib/splash/kernel/kernels/splash-py2
copying splash/kernel/kernels/splash-py2/kernel.json -> build/lib/splash/kernel/kernels/splash-py2
copying splash/kernel/kernels/splash-py2/logo-64x64.png -> build/lib/splash/kernel/kernels/splash-py2
copying splash/kernel/kernels/splash-py2/logo-32x32.png -> build/lib/splash/kernel/kernels/splash-py2
creating build/lib/splash/kernel/kernels/splash-py3
copying splash/kernel/kernels/splash-py3/kernel.json -> build/lib/splash/kernel/kernels/splash-py3
copying splash/kernel/kernels/splash-py3/logo-64x64.png -> build/lib/splash/kernel/kernels/splash-py3
copying splash/kernel/kernels/splash-py3/logo-32x32.png -> build/lib/splash/kernel/kernels/splash-py3
creating build/bdist.linux-x86_64
creating build/bdist.linux-x86_64/egg
creating build/bdist.linux-x86_64/egg/splash
copying build/lib/splash/jsutils.py -> build/bdist.linux-x86_64/egg/splash
copying build/lib/splash/argument_cache.py -> build/bdist.linux-x86_64/egg/splash
copying build/lib/splash/defaults.py -> build/bdist.linux-x86_64/egg/splash
copying build/lib/splash/pool.py -> build/bdist.linux-x86_64/egg/splash
copying build/lib/splash/lua.py -> build/bdist.linux-x86_64/egg/splash
copying build/lib/splash/exceptions.py -> build/bdist.linux-x86_64/egg/splash
copying build/lib/splash/sentry.py -> build/bdist.linux-x86_64/egg/splash
copying build/lib/splash/qtrender_image.py -> build/bdist.linux-x86_64/egg/splash
copying build/lib/splash/request_middleware.py -> build/bdist.linux-x86_64/egg/splash
copying build/lib/splash/xvfb.py -> build/bdist.linux-x86_64/egg/splash
copying build/lib/splash/html_element.py -> build/bdist.linux-x86_64/egg/splash
creating build/bdist.linux-x86_64/egg/splash/examples
copying build/lib/splash/examples/har.lua -> build/bdist.linux-x86_64/egg/splash/examples
copying build/lib/splash/examples/block-css.lua -> build/bdist.linux-x86_64/egg/splash/examples
copying build/lib/splash/examples/disable-images.lua -> build/bdist.linux-x86_64/egg/splash/examples
copying build/lib/splash/examples/scroll.lua -> build/bdist.linux-x86_64/egg/splash/examples
copying build/lib/splash/examples/wait-for-element.lua -> build/bdist.linux-x86_64/egg/splash/examples
copying build/lib/splash/examples/run-js.lua -> build/bdist.linux-x86_64/egg/splash/examples
copying build/lib/splash/examples/render-png.lua -> build/bdist.linux-x86_64/egg/splash/examples
copying build/lib/splash/examples/element-screenshot.lua -> build/bdist.linux-x86_64/egg/splash/examples
copying build/lib/splash/examples/with-timeout.lua -> build/bdist.linux-x86_64/egg/splash/examples
copying build/lib/splash/examples/submit-search.lua -> build/bdist.linux-x86_64/egg/splash/examples
copying build/lib/splash/examples/count-divs.lua -> build/bdist.linux-x86_64/egg/splash/examples
copying build/lib/splash/examples/return-title.lua -> build/bdist.linux-x86_64/egg/splash/examples
copying build/lib/splash/examples/phantomjs-follow.lua -> build/bdist.linux-x86_64/egg/splash/examples
copying build/lib/splash/examples/preload-functions.lua -> build/bdist.linux-x86_64/egg/splash/examples
copying build/lib/splash/examples/log-requests.lua -> build/bdist.linux-x86_64/egg/splash/examples
copying build/lib/splash/examples/call-later.lua -> build/bdist.linux-x86_64/egg/splash/examples
copying build/lib/splash/examples/multiple-pages.lua -> build/bdist.linux-x86_64/egg/splash/examples
copying build/lib/splash/examples/preload-jquery.lua -> build/bdist.linux-x86_64/egg/splash/examples
copying build/lib/splash/qtutils.py -> build/bdist.linux-x86_64/egg/splash
creating build/bdist.linux-x86_64/egg/splash/lua_modules
copying build/lib/splash/lua_modules/repr.lua -> build/bdist.linux-x86_64/egg/splash/lua_modules
copying build/lib/splash/lua_modules/element.lua -> build/bdist.linux-x86_64/egg/splash/lua_modules
copying build/lib/splash/lua_modules/response.lua -> build/bdist.linux-x86_64/egg/splash/lua_modules
copying build/lib/splash/lua_modules/splash.lua -> build/bdist.linux-x86_64/egg/splash/lua_modules
copying build/lib/splash/lua_modules/extras.lua -> build/bdist.linux-x86_64/egg/splash/lua_modules
copying build/lib/splash/lua_modules/event.lua -> build/bdist.linux-x86_64/egg/splash/lua_modules
creating build/bdist.linux-x86_64/egg/splash/lua_modules/vendor
copying build/lib/splash/lua_modules/vendor/lexer.lua -> build/bdist.linux-x86_64/egg/splash/lua_modules/vendor
copying build/lib/splash/lua_modules/vendor/inspect.lua -> build/bdist.linux-x86_64/egg/splash/lua_modules/vendor
copying build/lib/splash/lua_modules/completer.lua -> build/bdist.linux-x86_64/egg/splash/lua_modules
creating build/bdist.linux-x86_64/egg/splash/lua_modules/libs
copying build/lib/splash/lua_modules/libs/treat.lua -> build/bdist.linux-x86_64/egg/splash/lua_modules/libs
copying build/lib/splash/lua_modules/libs/json.lua -> build/bdist.linux-x86_64/egg/splash/lua_modules/libs
copying build/lib/splash/lua_modules/libs/base64.lua -> build/bdist.linux-x86_64/egg/splash/lua_modules/libs
copying build/lib/splash/lua_modules/wraputils.lua -> build/bdist.linux-x86_64/egg/splash/lua_modules
copying build/lib/splash/lua_modules/sandbox.lua -> build/bdist.linux-x86_64/egg/splash/lua_modules
copying build/lib/splash/lua_modules/request.lua -> build/bdist.linux-x86_64/egg/splash/lua_modules
copying build/lib/splash/proxy.py -> build/bdist.linux-x86_64/egg/splash
copying build/lib/splash/qtrender_lua.py -> build/bdist.linux-x86_64/egg/splash
copying build/lib/splash/har_builder.py -> build/bdist.linux-x86_64/egg/splash
creating build/bdist.linux-x86_64/egg/splash/ui
copying build/lib/splash/ui/style.css -> build/bdist.linux-x86_64/egg/splash/ui
copying build/lib/splash/ui/main.js -> build/bdist.linux-x86_64/egg/splash/ui
copying build/lib/splash/ui/favicon.ico -> build/bdist.linux-x86_64/egg/splash/ui
copying build/lib/splash/casperjs_utils.py -> build/bdist.linux-x86_64/egg/splash
copying build/lib/splash/__init__.py -> build/bdist.linux-x86_64/egg/splash
copying build/lib/splash/network_manager.py -> build/bdist.linux-x86_64/egg/splash
copying build/lib/splash/render_options.py -> build/bdist.linux-x86_64/egg/splash
copying build/lib/splash/resources.py -> build/bdist.linux-x86_64/egg/splash
copying build/lib/splash/lua_runner.py -> build/bdist.linux-x86_64/egg/splash
copying build/lib/splash/qtrender.py -> build/bdist.linux-x86_64/egg/splash
copying build/lib/splash/conftest.py -> build/bdist.linux-x86_64/egg/splash
copying build/lib/splash/utils.py -> build/bdist.linux-x86_64/egg/splash
copying build/lib/splash/qwebpage.py -> build/bdist.linux-x86_64/egg/splash
copying build/lib/splash/cookies.py -> build/bdist.linux-x86_64/egg/splash
copying build/lib/splash/server.py -> build/bdist.linux-x86_64/egg/splash
copying build/lib/splash/lua_runtime.py -> build/bdist.linux-x86_64/egg/splash
creating build/bdist.linux-x86_64/egg/splash/har
copying build/lib/splash/har/__init__.py -> build/bdist.linux-x86_64/egg/splash/har
copying build/lib/splash/har/schema.py -> build/bdist.linux-x86_64/egg/splash/har
copying build/lib/splash/har/qt.py -> build/bdist.linux-x86_64/egg/splash/har
copying build/lib/splash/har/utils.py -> build/bdist.linux-x86_64/egg/splash/har
copying build/lib/splash/har/log.py -> build/bdist.linux-x86_64/egg/splash/har
copying build/lib/splash/browser_tab.py -> build/bdist.linux-x86_64/egg/splash
creating build/bdist.linux-x86_64/egg/splash/kernel
copying build/lib/splash/kernel/__main__.py -> build/bdist.linux-x86_64/egg/splash/kernel
copying build/lib/splash/kernel/kernel.py -> build/bdist.linux-x86_64/egg/splash/kernel
copying build/lib/splash/kernel/completer.py -> build/bdist.linux-x86_64/egg/splash/kernel
copying build/lib/splash/kernel/__init__.py -> build/bdist.linux-x86_64/egg/splash/kernel
copying build/lib/splash/kernel/lua_parser.py -> build/bdist.linux-x86_64/egg/splash/kernel
creating build/bdist.linux-x86_64/egg/splash/kernel/kernels
creating build/bdist.linux-x86_64/egg/splash/kernel/kernels/splash-py2
copying build/lib/splash/kernel/kernels/splash-py2/kernel.json -> build/bdist.linux-x86_64/egg/splash/kernel/kernels/splash-py2
copying build/lib/splash/kernel/kernels/splash-py2/logo-64x64.png -> build/bdist.linux-x86_64/egg/splash/kernel/kernels/splash-py2
copying build/lib/splash/kernel/kernels/splash-py2/logo-32x32.png -> build/bdist.linux-x86_64/egg/splash/kernel/kernels/splash-py2
creating build/bdist.linux-x86_64/egg/splash/kernel/kernels/splash-py3
copying build/lib/splash/kernel/kernels/splash-py3/kernel.json -> build/bdist.linux-x86_64/egg/splash/kernel/kernels/splash-py3
copying build/lib/splash/kernel/kernels/splash-py3/logo-64x64.png -> build/bdist.linux-x86_64/egg/splash/kernel/kernels/splash-py3
copying build/lib/splash/kernel/kernels/splash-py3/logo-32x32.png -> build/bdist.linux-x86_64/egg/splash/kernel/kernels/splash-py3
copying build/lib/splash/kernel/errors.py -> build/bdist.linux-x86_64/egg/splash/kernel
copying build/lib/splash/kernel/inspections.py -> build/bdist.linux-x86_64/egg/splash/kernel
copying build/lib/splash/kernel/kernelbase.py -> build/bdist.linux-x86_64/egg/splash/kernel
creating build/bdist.linux-x86_64/egg/splash/kernel/inspections
copying build/lib/splash/kernel/inspections/splash.json -> build/bdist.linux-x86_64/egg/splash/kernel/inspections
copying build/lib/splash/kernel/inspections/splash-auto.json -> build/bdist.linux-x86_64/egg/splash/kernel/inspections
copying build/lib/splash/response_middleware.py -> build/bdist.linux-x86_64/egg/splash
byte-compiling build/bdist.linux-x86_64/egg/splash/jsutils.py to jsutils.pyc
byte-compiling build/bdist.linux-x86_64/egg/splash/argument_cache.py to argument_cache.pyc
byte-compiling build/bdist.linux-x86_64/egg/splash/defaults.py to defaults.pyc
byte-compiling build/bdist.linux-x86_64/egg/splash/pool.py to pool.pyc
byte-compiling build/bdist.linux-x86_64/egg/splash/lua.py to lua.pyc
byte-compiling build/bdist.linux-x86_64/egg/splash/exceptions.py to exceptions.pyc
byte-compiling build/bdist.linux-x86_64/egg/splash/sentry.py to sentry.pyc
byte-compiling build/bdist.linux-x86_64/egg/splash/qtrender_image.py to qtrender_image.pyc
byte-compiling build/bdist.linux-x86_64/egg/splash/request_middleware.py to request_middleware.pyc
byte-compiling build/bdist.linux-x86_64/egg/splash/xvfb.py to xvfb.pyc
byte-compiling build/bdist.linux-x86_64/egg/splash/html_element.py to html_element.pyc
byte-compiling build/bdist.linux-x86_64/egg/splash/qtutils.py to qtutils.pyc
byte-compiling build/bdist.linux-x86_64/egg/splash/proxy.py to proxy.pyc
byte-compiling build/bdist.linux-x86_64/egg/splash/qtrender_lua.py to qtrender_lua.pyc
  File "build/bdist.linux-x86_64/egg/splash/qtrender_lua.py", line 1544
    def call_method(self, *args, method_name=method_name):
                                           ^
SyntaxError: invalid syntax

byte-compiling build/bdist.linux-x86_64/egg/splash/har_builder.py to har_builder.pyc
byte-compiling build/bdist.linux-x86_64/egg/splash/casperjs_utils.py to casperjs_utils.pyc
byte-compiling build/bdist.linux-x86_64/egg/splash/__init__.py to __init__.pyc
byte-compiling build/bdist.linux-x86_64/egg/splash/network_manager.py to network_manager.pyc
byte-compiling build/bdist.linux-x86_64/egg/splash/render_options.py to render_options.pyc
byte-compiling build/bdist.linux-x86_64/egg/splash/resources.py to resources.pyc
byte-compiling build/bdist.linux-x86_64/egg/splash/lua_runner.py to lua_runner.pyc
byte-compiling build/bdist.linux-x86_64/egg/splash/qtrender.py to qtrender.pyc
byte-compiling build/bdist.linux-x86_64/egg/splash/conftest.py to conftest.pyc
byte-compiling build/bdist.linux-x86_64/egg/splash/utils.py to utils.pyc
byte-compiling build/bdist.linux-x86_64/egg/splash/qwebpage.py to qwebpage.pyc
byte-compiling build/bdist.linux-x86_64/egg/splash/cookies.py to cookies.pyc
byte-compiling build/bdist.linux-x86_64/egg/splash/server.py to server.pyc
byte-compiling build/bdist.linux-x86_64/egg/splash/lua_runtime.py to lua_runtime.pyc
byte-compiling build/bdist.linux-x86_64/egg/splash/har/__init__.py to __init__.pyc
byte-compiling build/bdist.linux-x86_64/egg/splash/har/schema.py to schema.pyc
byte-compiling build/bdist.linux-x86_64/egg/splash/har/qt.py to qt.pyc
byte-compiling build/bdist.linux-x86_64/egg/splash/har/utils.py to utils.pyc
byte-compiling build/bdist.linux-x86_64/egg/splash/har/log.py to log.pyc
byte-compiling build/bdist.linux-x86_64/egg/splash/browser_tab.py to browser_tab.pyc
byte-compiling build/bdist.linux-x86_64/egg/splash/kernel/__main__.py to __main__.pyc
byte-compiling build/bdist.linux-x86_64/egg/splash/kernel/kernel.py to kernel.pyc
byte-compiling build/bdist.linux-x86_64/egg/splash/kernel/completer.py to completer.pyc
byte-compiling build/bdist.linux-x86_64/egg/splash/kernel/__init__.py to __init__.pyc
byte-compiling build/bdist.linux-x86_64/egg/splash/kernel/lua_parser.py to lua_parser.pyc
byte-compiling build/bdist.linux-x86_64/egg/splash/kernel/errors.py to errors.pyc
byte-compiling build/bdist.linux-x86_64/egg/splash/kernel/inspections.py to inspections.pyc
byte-compiling build/bdist.linux-x86_64/egg/splash/kernel/kernelbase.py to kernelbase.pyc
byte-compiling build/bdist.linux-x86_64/egg/splash/response_middleware.py to response_middleware.pyc
creating build/bdist.linux-x86_64/egg/EGG-INFO
installing scripts to build/bdist.linux-x86_64/egg/EGG-INFO/scripts
running install_scripts
running build_scripts
creating build/scripts-2.7
copying and adjusting bin/splash -> build/scripts-2.7
changing mode of build/scripts-2.7/splash from 644 to 755
creating build/bdist.linux-x86_64/egg/EGG-INFO/scripts
copying build/scripts-2.7/splash -> build/bdist.linux-x86_64/egg/EGG-INFO/scripts
changing mode of build/bdist.linux-x86_64/egg/EGG-INFO/scripts/splash to 755
copying splash.egg-info/PKG-INFO -> build/bdist.linux-x86_64/egg/EGG-INFO
copying splash.egg-info/SOURCES.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying splash.egg-info/dependency_links.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying splash.egg-info/not-zip-safe -> build/bdist.linux-x86_64/egg/EGG-INFO
copying splash.egg-info/requires.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying splash.egg-info/top_level.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
creating dist
creating 'dist/splash-2.3-py2.7.egg' and adding 'build/bdist.linux-x86_64/egg' to it
removing 'build/bdist.linux-x86_64/egg' (and everything under it)
Processing splash-2.3-py2.7.egg
creating /usr/local/services/tjip_python2712_tl2-1.0/lib/python2.7/site-packages/splash-2.3-py2.7.egg
Extracting splash-2.3-py2.7.egg to /usr/local/services/tjip_python2712_tl2-1.0/lib/python2.7/site-packages
  File "/usr/local/services/tjip_python2712_tl2-1.0/lib/python2.7/site-packages/splash-2.3-py2.7.egg/splash/qtrender_lua.py", line 1544
    def call_method(self, *args, method_name=method_name):
                                           ^
SyntaxError: invalid syntax

Removing splash 2.3.1 from easy-install.pth file
Adding splash 2.3 to easy-install.pth file
Installing splash script to /usr/local/services/tjop_python/bin

Installed /usr/local/services/tjip_python2712_tl2-1.0/lib/python2.7/site-packages/splash-2.3-py2.7.egg
Processing dependencies for splash==2.3
Searching for Pillow==4.0.0
Best match: Pillow 4.0.0
Adding Pillow 4.0.0 to easy-install.pth file

Using /usr/local/services/tjip_python2712_tl2-1.0/lib/python2.7/site-packages
Searching for funcparserlib==0.3.6
Best match: funcparserlib 0.3.6
Adding funcparserlib 0.3.6 to easy-install.pth file

Using /usr/local/services/tjip_python2712_tl2-1.0/lib/python2.7/site-packages
Searching for xvfbwrapper==0.2.9
Best match: xvfbwrapper 0.2.9
Adding xvfbwrapper 0.2.9 to easy-install.pth file

Using /usr/local/services/tjip_python2712_tl2-1.0/lib/python2.7/site-packages
Searching for adblockparser==0.7
Best match: adblockparser 0.7
Adding adblockparser 0.7 to easy-install.pth file

Using /usr/local/services/tjip_python2712_tl2-1.0/lib/python2.7/site-packages
Searching for psutil==5.0.1
Best match: psutil 5.0.1
Adding psutil 5.0.1 to easy-install.pth file

Using /usr/local/services/tjip_python2712_tl2-1.0/lib/python2.7/site-packages
Searching for qt5reactor==0.3
Best match: qt5reactor 0.3
Adding qt5reactor 0.3 to easy-install.pth file

Using /usr/local/services/tjip_python2712_tl2-1.0/lib/python2.7/site-packages
Searching for Twisted==16.2.0
Best match: Twisted 16.2.0
Adding Twisted 16.2.0 to easy-install.pth file

Using /usr/local/services/tjip_python2712_tl2-1.0/lib/python2.7/site-packages
Searching for olefile==0.44
Best match: olefile 0.44
Adding olefile 0.44 to easy-install.pth file

Using /usr/local/services/tjip_python2712_tl2-1.0/lib/python2.7/site-packages
Searching for zope.interface==4.3.3
Best match: zope.interface 4.3.3
Adding zope.interface 4.3.3 to easy-install.pth file

Using /usr/local/services/tjip_python2712_tl2-1.0/lib/python2.7/site-packages
Searching for setuptools==33.1.1
Best match: setuptools 33.1.1
Processing setuptools-33.1.1-py2.7.egg
setuptools 33.1.1 is already the active version in easy-install.pth
Installing easy_install script to /usr/local/services/tjop_python/bin
Installing easy_install-2.7 script to /usr/local/services/tjop_python/bin

Using /usr/local/services/tjip_python2712_tl2-1.0/lib/python2.7/site-packages/setuptools-33.1.1-py2.7.egg
Finished processing dependencies for splash==2.3

**Comment by kmike** [comment]
Sorry, Python 2 support will be dropped soon.
