### ISSUE TITLE
Splash is not rendering JS based page

### ISSUE THREAD

**Issue by Vineeth-Mohan** [scrapinghub/splash#581]
http://localhost:8050/render.json?url=http://demo.dronofly.com:14502/&viewport=1280x1024&html=1&wait=5&resource_timeout=10

I tried all the possible configurations and for the life of me , I am not able to get this working.
Any help here would be greatly appreciated. 
It would be great if we can tap into console of the browser and capture all JS console logs and JS error raised by the browser on running the site.

**Comment by kmike** [comment]
I can confirm this page doesn't render in Splash 2.3.3. https://github.com/scrapinghub/splash/pull/614 fixes the issue.
