### ISSUE TITLE
TypeError: SplashJsonResponse url must be str, got unicode

### ISSUE THREAD

**Issue by wenxzhen** [scrapinghub/splash#584]
My Splash version is in 2.3.2:

> 2017-03-23 10:24:49.591255 [-] Splash version: 2.3.2
> 2017-03-23 10:24:49.592435 [-] Qt 5.5.1, PyQt 5.5.1, WebKit 538.1, sip 4.17, Twisted 16.1.1, Lua 5.2
> 2017-03-23 10:24:49.592688 [-] Python 3.4.3 (default, Nov 17 2016, 01:08:31) [GCC 4.8.4]
> 2017-03-23 10:24:49.592960 [-] Open files limit: 99999
> 2017-03-23 10:24:49.593182 [-] Can't bump open files limit
> 2017-03-23 10:24:49.703665 [-] Xvfb is started: ['Xvfb', ':1', '-screen', '0', '1024x768x24', '-nolisten', 'tcp']
> 2017-03-23 10:24:49.911082 [-] proxy profiles support is enabled, proxy profiles path: /etc/splash/proxy-profiles
> 2017-03-23 10:24:50.651053 [-] verbosity=1
> 2017-03-23 10:24:50.651382 [-] slots=50
> 2017-03-23 10:24:50.651615 [-] argument_cache_max_entries=500
> 2017-03-23 10:24:50.652616 [-] Web UI: enabled, Lua: enabled (sandbox: enabled)
> 2017-03-23 10:24:50.659033 [-] Site starting on 8050
> 2017-03-23 10:24:50.659403 [-] Starting factory <twisted.web.server.Site object at 0x7f332408a240>

While my Scrapy splash is in 0.7.1, and run with Python 2.7 as described below. Is it an issue in the python version?

> 2017-03-23 19:10:05 [scrapy.core.scraper] ERROR: Error downloading <GET http://192.168.6.115:8050/render.json>
> Traceback (most recent call last):
>   File "/root/wenxzhen/python27_env/lib/python2.7/site-packages/Twisted-17.1.0-py2.7-linux-x86_64.egg/twisted/internet/defer.py", line 1301, in _inlineCallbacks
>     result = g.send(result)
>   File "/root/wenxzhen/python27_env/lib/python2.7/site-packages/scrapy/core/downloader/middleware.py", line 53, in process_response
>     spider=spider)
>   File "/root/wenxzhen/python27_env/lib/python2.7/site-packages/scrapy_splash/middleware.py", line 387, in process_response
>     response = self._change_response_class(request, response)
>   File "/root/wenxzhen/python27_env/lib/python2.7/site-packages/scrapy_splash/middleware.py", line 402, in _change_response_class
>     response = response.replace(cls=respcls, request=request)
>   File "/root/wenxzhen/python27_env/lib/python2.7/site-packages/scrapy/http/response/text.py", line 50, in replace
>     return Response.replace(self, *args, **kwargs)
>   File "/root/wenxzhen/python27_env/lib/python2.7/site-packages/scrapy/http/response/__init__.py", line 79, in replace
>     return cls(*args, **kwargs)
>   File "/root/wenxzhen/python27_env/lib/python2.7/site-packages/scrapy_splash/response.py", line 95, in __init__
>     super(SplashJsonResponse, self).__init__(*args, **kwargs)
>   File "/root/wenxzhen/python27_env/lib/python2.7/site-packages/scrapy_splash/response.py", line 33, in __init__
>     super(_SplashResponseMixin, self).__init__(url, *args, **kwargs)
>   File "/root/wenxzhen/python27_env/lib/python2.7/site-packages/scrapy/http/response/__init__.py", line 21, in __init__
>     self._set_url(url)
>   File "/root/wenxzhen/python27_env/lib/python2.7/site-packages/scrapy/http/response/__init__.py", line 43, in _set_url
>     type(url).__name__))
> TypeError: SplashJsonResponse url must be str, got unicode:

Thanks,

**Comment by kmike** [comment]
I haven't seen this error myself. Is there a way to reproduce it?

**Comment by kmike** [comment]
Could you please open an issue at https://github.com/scrapy-plugins/scrapy-splash issue tracker instead?

**Comment by wenxzhen** [comment]
Thanks to @kmike, will go to scrapy-splash instead.

**Comment by wenxzhen** [comment]
@kmike One question is about the encoding of the response from Splash. If Splash runs on Python 3x, will it send the URL of the response in Unicode?

**Comment by kmike** [comment]
Thanks @wenxzhen!

> One question is about the encoding of the response from Splash. If Splash runs on Python 3x, will it send the URL of the response in Unicode?

It doesn't work this way - regardless of a Python version Splash is running, it sends language-agnostic JSON in the response. Client then decodes this JSON data. Unicode is not something you can send; it is only possible to send bytes over the wire, and Splash sends the same bytes regardless of Python version it is running. It depends on a client how to decode & process these bytes.
