### ISSUE TITLE
How to get plain text from response ?

### ISSUE THREAD

**Issue by slotix** [scrapinghub/splash#585]
Trying to execute the following script
`function main(splash)
  local url = "http://google.com/robots.txt"
  splash:set_result_header(
      "Content-Type", "text/plain")
  assert(splash:go(url))
  assert(splash:wait(0.5))
  return {
    html = splash:html()
  }
end`
As a result I get the robots.txt file wrapped by 
`<html><head></head><body><pre style="word-wrap: break-word; white-space: pre-wrap;">
...
</pre></body></html>`
How to get plain text from response?

**Comment by kmike** [comment]
`splash:html()` returns a snapshot of DOM, and browsers adds these elements. 
If you need to just fetch a file without processing it in a browser you can use [splash:http_get](http://splash.readthedocs.io/en/stable/scripting-ref.html#splash-http-get).

**Comment by slotix** [comment]
Thanks this code works now 
`function main(splash)
  local url = splash.args.url
 	local response = splash:http_get(url).info
  assert(splash:wait(0.5))
  return {
    response
  }
end`
