### ISSUE TITLE
Splash stops with error "unregister_netdevice: waiting for lo to become free"

### ISSUE THREAD

**Issue by vionemc** [scrapinghub/splash#586]
`kernel:[1476369.644116] unregister_netdevice: waiting for lo to become free. Usage count = 1`

I got that error then Splash will stop working and I have to run the docker from the beginning again. I heard it's related with docker. How to stop getting this issue?

Is it related to low RAM? My linux server's spec is 512MB RAM and 1vCPU.

**Comment by kmike** [comment]
Hey @vionemc,

You're facing this Docker bug: https://github.com/docker/docker/issues/5618. I don't think we can do anything in Splash to workaround it. It seems the only fix is to upgrade linux kernel, and even this may not fix the issue completely (though it should help).

**Comment by vionemc** [comment]
Thanks!

**Comment by wenxzhen** [comment]
@kmike 

From the /var/log/messages, it seemed it's the Splash triggered the error condition:

> **Message from syslogd@DM-02 at Apr 26 09:38:19 ...fault at 14 ip 00007f0a41a3af84 sp 00007ffee37f2c60 error 4 in libQt5WebKit.so.5.5.1[7f0a410f2000+20a9000]**
>  kernel:unregister_netdevice: waiting for lo to become free. Usage count = 10" level=error msg="Error closing logger: invalid argument"
> Apr 25 18:11:29 DM-02 kernel: docker0: port 1(veth4a2239b) entered disabled state
> Message from syslogd@DM-02 at Apr 26 09:38:29 ...h4a2239b) entered disabled state
>  kernel:unregister_netdevice: waiting for lo to become free. Usage count = 1
> Apr 25 18:11:29 DM-02 kernel: docker0: port 1(veth4a2239b) entered disabled state
> Message from syslogd@DM-02 at Apr 26 09:38:39 ...  [1493158289.4487] device (veth2f2a824): driver '(null)' does not support carrier detection.
>  kernel:unregister_netdevice: waiting for lo to become free. Usage count = 1vice (veth2f2a824): driver 'veth' does not support carrier detection.
> Apr 25 18:11:29 DM-02 NetworkManager[884]: <info>  [1493158289.4501] manager: (veth2f2a824): new Veth device (/org/freedesktop/NetworkManager/Devices/34)
> Message from syslogd@DM-02 at Apr 26 09:38:49 ...  [1493158289.4522] device (veth2f2a824): driver 'veth' does not support carrier detection.
>  kernel:unregister_netdevice: waiting for lo to become free. Usage count = 1vice (veth4a2239b): driver 'veth' does not support carrier detection.
> Apr 25 18:11:29 DM-02 NetworkManager[884]: <info>  [1493158289.4535] device (veth4a2239b): released from master device docker0
> 
> 
> Apr 25 18:18:09 DM-02 kernel: unregister_netdevice: waiting for lo to become free. Usage count = 1
> Apr 25 18:18:19 DM-02 kernel: unregister_netdevice: waiting for lo to become free. Usage count = 1
> Apr 25 18:18:29 DM-02 kernel: unregister_netdevice: waiting for lo to become free. Usage count = 1
> Apr 25 18:18:39 DM-02 kernel: unregister_netdevice: waiting for lo to become free. Usage count = 1
> Apr 25 18:18:49 DM-02 kernel: unregister_netdevice: waiting for lo to become free. Usage count = 1
> Apr 25 18:18:59 DM-02 kernel: unregister_netdevice: waiting for lo to become free. Usage count = 1

**Comment by wenxzhen** [comment]
find another occurrence: 

> **Apr 26 12:38:11 DM-02 kernel: Qt HTTP thread[21286]: segfault at 8 ip 00007f760accd11a sp 00007f7538fa68e0 error 4 in libQt5Network.so.5.5.1[7f760ac7c000+151000]** 
> Apr 26 12:38:12 DM-02 dockerd: time="2017-04-26T12:38:12.286549180-04:00" level=error msg="Error closing logger: invalid argument" 
> Apr 26 12:38:12 DM-02 kernel: docker0: port 1(vethe43bd8e) entered disabled state 
> Apr 26 12:38:12 DM-02 kernel: docker0: port 1(vethe43bd8e) entered disabled state 
> Apr 26 12:38:12 DM-02 kernel: device vethe43bd8e left promiscuous mode 
> Apr 26 12:38:12 DM-02 kernel: docker0: port 1(vethe43bd8e) entered disabled state
