### ISSUE TITLE
nil Request object

### ISSUE THREAD

**Issue by slotix** [scrapinghub/splash#587]
Splash returns nil object after executing the following script. 
` function main(splash)
			local url = splash.args.url
			local reply = splash:http_get(url).info
			assert(splash:wait(1))
			return {
				reply.request
			}
			end
`
How to get request object ?

**Comment by kmike** [comment]
http://splash.readthedocs.io/en/stable/scripting-response-object.html#response-object say it should be `local reply = splash:http_get(url)` and then `return {reply.request.info}`, something like that (see http://splash.readthedocs.io/en/stable/scripting-request-object.html).

Response.info returns HAR response object (see http://www.softwareishard.com/blog/har-12-spec/#response) - it doesn't have 'request' field.

**Comment by slotix** [comment]
Thank you very much for your assistance !
