### ISSUE TITLE
Force http_get to return content after loading it to the browser

### ISSUE THREAD

**Issue by slotix** [scrapinghub/splash#595]
I'm using the following script for getting request and response structures:
```
function main(splash)
    local url = splash.args.url
    local reply = splash:http_get(url)
    assert(splash:wait(1))
    return {
		    reply.request.info,	
		    reply.info
		}
end
```
From documentation  - splash:http_get method returns content without loading result to the browser. 
Actually I would need to get content.text as it is returned by splash:go(url) method after loading content to the browser.
Is it possible to don't call two separate methods twice?

**Comment by kmike** [comment]
Sorry, could you please clarify it; I'm not sure I follow? What does 'content.text' mean? 

As a side note, there is no need to use `assert(splash:wait(1))` in your script because splash:http_get waits for URL to be downloaded; this wait just adds a delay and nothing happens during this delay.

**Comment by slotix** [comment]
I'm sorry for misunderstanding. I have to retrieve both request & response from `splash:http_get` method 
and
html page after loading it to browser after js scripts loaded which is returned by `splash:go` method. 
So how to get them all and don't request the same page twice?

**Comment by kmike** [comment]
@slotix I think there are two options:

1) get response using splash:http_get, then use [splash:set_content](http://splash.readthedocs.io/en/stable/scripting-ref.html#splash-set-content) to load it in a browser, then call splash:html to get the processed version.
2) use [splash:on_response](http://splash.readthedocs.io/en/stable/scripting-ref.html#splash-on-response) to store response body of the first non-redirect response; it will require setting [splash.response_body_enabled](http://splash.readthedocs.io/en/stable/scripting-ref.html#splash-response-body-enabled) to `true`.

**Comment by slotix** [comment]
Thanks ! I will try them.

**Comment by slotix** [comment]
Dear Mikhail, 
It seems the first solution doesn't work for me by some reason. 
I'm trying the following script 
```
base64 = require("base64")
function main(splash)
			local url = splash.args.url
			local response = splash:http_get(url)
  		data = base64.decode(response.info.content.text)
			ok, reason = splash:set_content(data)
      assert(splash:wait(0.5))   
			return {
  			 ok = ok,
  			 reason = (reason==nil),
	       png = splash:png(),
         html= splash:html(),
    		 request = response.request.info,	
				 response = response.info
      }
end
```
against https://drony.heureka.sk as an example. 

![screenshot 2017-04-16 22 30 48](https://cloud.githubusercontent.com/assets/684169/25073702/940f6470-22f4-11e7-8a66-7fdf1a796863.jpg)

The first screenshot shows the page rendered with standard  splash:go() method with processed JS code outlined by Red.  

![screenshot 2017-04-16 22 30 34](https://cloud.githubusercontent.com/assets/684169/25073701/93bcef56-22f4-11e7-9f58-1dc2929655a4.jpg)

The bottom screenshot shows the page rendered using the custom script listed above.

**Comment by slotix** [comment]
This script listed below works well. I'm getting a list of response objects here. 
```
treat = require("treat")
function main(splash)
  local responses = {}
  local url = splash.args.url
  splash:set_viewport_size(1024, 2048)
  splash.response_body_enabled = true
  splash:on_response(function (response) 
     table.insert(responses, response.info)
    end)
  assert(splash:go(url))
  assert(splash:wait(0.5))
  
  return {
    result = treat.as_array(responses),
    splash:png(),
  }
end
```

In some cases there are more than one set of properties with the following characteristics in responses list.  
```
mimeType: "text/html; charset=utf-8"
ok: true
redirectURL: ""
status: 200
statusText: "OK"
url: ""
```

Initial url may lead to another domain for example. 
Is it a way to determine the final url object exactly from the list of objects?

**Comment by slotix** [comment]
The following code works for me perfectly 
```
function string.ends(String,End)
  return End=='' or string.sub(String,-string.len(End))==End
end

function main(splash)
  local url = splash.args.url
  if not string.ends(url, "/") then
    url = url .. "/"
  end
  splash:on_response(function (response)
  if response.info.url == url then
    status = response.info.status
    is_redirect = status == 301 or status == 302
    if is_redirect then
      url = response.info.redirectURL
    elseif status == 200 then
      r = response
    end
  end
  end)
  assert(splash:go(url))
  assert(splash:wait(1))
  if r ~= nil then
    return {
      request = r.request.info,
      response = r.info,
      html = splash:html(),
    }
  else
    return {
      "Splash: Invalid response",
      html = splash:html(),
    }
  end
end
```
