### ISSUE TITLE
Facing errors while installing splash in Ubuntu 16.04

### ISSUE THREAD

**Issue by ashlesh688** [scrapinghub/splash#598]
When I try to install Splash using the "Provisions.sh" file in Ubuntu 16.04 I am facing issues such as

E: Unable to locate package qt55base
E: Unable to locate package qt55webkit
E: Unable to locate package qt55svg
E: Unable to locate package libre2
E: Package 'libicu52' has no installation candidate

My system is i386 based desktop and I tried to resolve the above issues by running the below commands.

"dpkg --add-architecture i386" and "apt-get update" but even this did not work can anyone please help me resolve the above issues.

**Comment by David1119** [comment]
use server,not desktop

**Comment by kmike** [comment]
provision.sh from Splash 2.3.3 is for Ubuntu 14.04, it is not compatible with Ubuntu 16.04. 
Splash is switched to Ubuntu 16.04 in #614; using docker is still recommended though.
