### ISSUE TITLE
Rendering imcompletely when page contains urls without protocol

### ISSUE THREAD

**Issue by aristoler** [scrapinghub/splash#600]
When I do the below task, the result is not as that in the browser.
`curl 'http://localhost:8050/render.png?url=https://www.taobao.com&timeout=10&wait=10&render_all=1' > taobao.png`

The problem may be caused by the urls contained as this:
`<img src="//img.alicdn.com/tfs/TB1ILwrQFXXXXXtXFXXXXXXXXXX-520-280.jpg_q90_.webp" alt="">
`

How to tackle with such situations?

**Comment by kmike** [comment]
I don't think `//` URLs are a problem; the following script seems to render everything on taobao for me:

```lua
function main(splash)
  assert(splash:go(splash.args.url))
  splash:set_viewport_full()
  assert(splash:wait(10))
  return {
    html = splash:html(),
    png = splash:png(),
    har = splash:har(),
  }
end
```
