### ISSUE TITLE
Update from Qt WebKit to Qt WebEngine

### ISSUE THREAD

**Issue by mokrea** [scrapinghub/splash#603]
Splash plans update from qt webkit to qt webengine?

I'm not a python or QT expert. I tryed change webkit functions and imports to webengine, check functions..... that works in parts, but there are some changes that may affect the result.

If you try download and use splash in last version of python and QT you need change the code to run the splash server.

**Comment by kmike** [comment]
Hey @mokrea, this is discussed in https://github.com/scrapinghub/splash/issues/349. I don't think we should move from QtWebKit to QtWebEngine, but having QtWebEngine support in addition to QtWebKit support would be great.
