### ISSUE TITLE
string module not found in lua

### ISSUE THREAD

**Issue by rbs392** [scrapinghub/splash#604]
I'm trying to match a particular pattern of url but getting this error
{
    "error": 400,
    "info": {
        "error": "module 'string' not found",
        "line_number": 3,
        "type": "LUA_ERROR",
        "source": "[string \"function main(splash)\r...\"]",
        "message": "Lua error: [string \"function main(splash)\r...\"]:3: module 'string' not found"
    },
    "type": "ScriptError",
    "description": "Error happened while executing Lua script"
}

What am i doing wrong. 
P.S Im using the docker image

**Comment by kmike** [comment]
Could you please paste the whole script?
