### ISSUE TITLE
splash:history() may return empty list

### ISSUE THREAD

**Issue by myrfy001** [scrapinghub/splash#605]
The splash:history() may return empty results.

I wang't to use the following code to get the page's headers, and if redirected, use the last one.

I use `http://example.com` to test, but only the first request will get an result returned. All the following request to this url will get an empty result. 

If restart the splash process, then the next request will work well and then go wrong.

```python
local entries = splash:history()
local last_entry = entries[#entries]
return {headers=last_entry.response.headers}
```

**Comment by slotix** [comment]
myrfy001 , I have the same issue described at https://github.com/scrapinghub/splash/issues/613 
how did you solve it ?
Thank you

**Comment by myrfy001** [comment]
@slotix 
Not really.
But use the `_gc` API will have the same effect as restart the splash process.

Hope this will help.  ;)

**Comment by slotix** [comment]
Thank you ! It solves the problem
