### ISSUE TITLE
Unexpected result when combining POST with gzip encoding.

### ISSUE THREAD

**Issue by rmax** [scrapinghub/splash#61]
When using splash as a proxy, and making a POST request with gzip encoding header, it seems the content does not get decoded before taking the screenshot. This does not happen when the method is GET or the encoding is deflate. The render method html is affected too.

For example:
- POST request with deflate encoding
  
  ```
  curl -x localhost:8051 -X POST -H 'Accept-Encoding: deflate'  -H 'X-Splash-render: png' -H 'X-Splash-wait: 1' http://www.facebook.com
  ```
  
  ![Result as expected.](http://i.imgur.com/x0vyEo5.png)
- POST request with gzip encoding
  
  ```
  curl -x localhost:8051 -X POST -H 'Accept-Encoding: gzip'  -H 'X-Splash-render: png' -H 'X-Splash-wait: 1' http://www.facebook.com
  ```
  
  ![Unexpected result.](http://i.imgur.com/iekhNkj.png)

**Comment by laoyur** [comment]
sorry to reply this closed issue, but I have the same problem in Splash 2.1

**Comment by kmike** [comment]
@laoyur is there a way to reproduce it?
