### ISSUE TITLE
render loss when dealing with taobao

### ISSUE THREAD

**Issue by zperfet** [scrapinghub/splash#611]
I use splash for the first time, and when i use splash to render pages from https://www.taobao.com/,i just found that splash can only render part of pages i wanted.The other pages are not rendered. I increased wait time but it's useless.I use docker on centos7 to start splash. I  looked through splash's doc but i found nothing mentioned it. I wonder if i did something wrong or some other reason i do not know. Any help will be appreciated!

**Comment by kmike** [comment]
Which pages are not rendered correctly, could you please give an example?
