### ISSUE TITLE
splash:history() returns an error launching the second time

### ISSUE THREAD

**Issue by slotix** [scrapinghub/splash#613]
The following LUA script from documentation works just once for some sites.

```
function main(splash)
    assert(splash:go("https://scrapinghub.com"))
    local entries = splash:history()
    -- #entries means "entries length"; arrays in Lua start from 1
    local last_entry = entries[#entries]
    return {
       headers = last_entry.response.headers,
    }
end
```
It returns the following error after web browser page refresh until splash server restarted

```
{
    "description": "Error happened while executing Lua script",
    "info": {
        "source": "[string \"function main(splash)\r...\"]",
        "line_number": 7,
        "message": "Lua error: [string \"function main(splash)\r...\"]:7: attempt to index local 'last_entry' (a nil value)",
        "error": "attempt to index local 'last_entry' (a nil value)",
        "type": "LUA_ERROR"
    },
    "error": 400,
    "type": "ScriptError"
}
```

**Comment by slotix** [comment]
calling of garbage collector curl -X POST http://localhost:8050/_gc solves the problem as suggested by  @myrfy001

**Comment by kmike** [comment]
Hm, the problem is that pages may be absent from HAR output if they are cached; history and HAR only contains actual HTTP requests / responses, not responses fetched from cache. I can see how this can be an issue for splash:history.

**Comment by slotix** [comment]
Actually it would be better to retrieve results from cache instead of calling _gc endpoint.  Should save_args  and load_args be used for getting cached results ?

**Comment by kmike** [comment]
@slotix nope, save_args and load_args control a different kind of caching - caching of input arguments at Splash side, not caching of web page resources.

**Comment by slotix** [comment]
ok is there a way to retrieve cache data ?

**Comment by kmike** [comment]
There is nothing implemented in Splash for that. I haven't checked if it is possible in qt/qtwebkit. It would be a good feature to have.

**Comment by slotix** [comment]
Thank you for your response. Calling _gc endpoint would be  a solution for the moment.

**Comment by botzill** [comment]
Hi. Currently I'm facing this issue while using splash with scrapy. So, I want to take the current request/response made by splash and seems that `splash:history()` is the only way? Now, if I call `_gc` each time I make a request then this will be a blocking operation, is there any workaround this ?
