### ISSUE TITLE
How to set User-Agent over HTTP API

### ISSUE THREAD

**Issue by thebennos** [scrapinghub/splash#628]
Hey
I am using Splash over the HTTP API and I want to set the User Agent ? 

I have found 
http://splash.readthedocs.io/en/latest/scripting-ref.html?highlight=agent#splash-set-user-agent
but it is not useable over the http API. 

I have also looked at the code where the default user agent is set, but not found it. 

Hopefully somebody can help me . 
thx
Benjamin

**Comment by kmike** [comment]
Hi @thebennos,

To set user-agent in render.??? endpoints just pass User-Agent header in `headers` argument. Unlike other headers, User-Agent should be "sticky" - see http://splash.readthedocs.io/en/stable/api.html#arg-headers

**Comment by thebennos** [comment]
hmm. maybe I do not get it. 
as argument in the url like this 
&headers={"name":"User-Agent","value":"TESTING"}

I think I do not see the trees in the wood. Can you give me an example?

**Comment by kmike** [comment]
Could you give an example? I'm not sure `headers` argument can be used as a GET argument, you may need to use JSON POST requests for it to work properly. Format is also different: either 
`[["User-Agent", "TESTING"]]` or `{"User-Agent": "TESTING"}`.

**Comment by thebennos** [comment]
Tested around but nothing seems to work. 
I get only...
{
    "info": {
        "argument": "headers",
        "type": "bad_argument",
        "description": "'headers' must be either a JSON array of (name, value) pairs or a JSON object"
    },
    "description": "Incorrect HTTP API arguments",
    "type": "BadOption",
    "error": 400
}

**Comment by kmike** [comment]
How are you constructing the request? This works for me:

```py
import requests
resp = requests.post('http://localhost:8050/render.html', json={
    'url': 'http://httpbin.org/headers', 
    'headers': {'User-Agent': 'TEST'}
})
print(resp.text)
```

Output:

```
<html><head></head><body><pre style="word-wrap: break-word; white-space: pre-wrap;">{
  "headers": {
    "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8",
    "Accept-Encoding": "gzip, deflate",
    "Accept-Language": "en,*",
    "Connection": "close",
    "Host": "httpbin.org",
    "User-Agent": "TEST"
  }
}
</pre></body></html>
```

**Comment by thebennos** [comment]
ah, got it. writing mistake. thx for your help.
