### ISSUE TITLE
HtmlResponse received instead of SplashJsonResponse when run as a script

### ISSUE THREAD

**Issue by umrashrf** [scrapinghub/splash#642]
I played with https://docs.scrapy.org/en/latest/topics/practices.html#run-from-script

My spider uses Scrapy-Splash so I received a weird error on callback of a SplashRequest and turns out running a script while using Scrapy-Splash doesn't work as expected.

I will try to reproduce in a fresh project but not sure if I'll get time for this.

**Comment by kmike** [comment]
Where are you defining project settings? If you just use CrawlerProcess(), `settings.py` is not applied.
