### ISSUE TITLE
Lua Script Won't Execute Scrapy + Splash

### ISSUE THREAD

**Issue by thib57410** [scrapinghub/splash#645]
Hello everyone.

As part of my Machine Learning Project, I have to scrape comments from tripadvisor, but I noticed that scrapy wasn't enough as tripadvisor executes javascript to render people's profile or to retrieve the whole comment.
Therefore, I need to use Splash.

I am new on Splash, and I tried a simple script. But it seems like the LUA script doesn't work.
Could somebody help me and explain how it works please ?

Here's how I execute the code from the script :

```
def main():
    configure_logging()
    runner = CrawlerRunner({
          'FEED_FORMAT': 'json',
          'FEED_URI': 'resultat.json', ##config de la sortie de la spider
    })
    runner.crawl(tuto)
    reactor.run()

```

And below you will find my scrapy spider :
```
class tuto(scrapy.Spider):
    name = "tuto"
    start_urls = ['https://www.tripadvisor.fr/Hotel_Review-g612353-d736372-Reviews-Tamassa-Bel_Ombre.html']

    script1 = """
    function main(splash)
        assert(splash:go(splash.args.url))
        splash:wait(2)
        local
        title = splash:evaljs("document.title")
        return {title=title}
    end
    """

    # http_user = 'splash-user'
    # http_pass = 'splash-password'

    def parse(self, response):
        yield SplashRequest(
        response.url,
        self.parse_link,
        endpoint='execute',
          args={
                'har': 1,
                'html': 1,
                'lua_source': self.script1,
                'wait' : 0.5,
          }
        )

```

From what I've understood, the SplashRequest element will send back a response to the parse function after having executed the LUA script, so I assumed that this function would have returned the title of the page :

```
    def parse_link(self, response):
        yield {'reponse' : response.body}
```

But I got the full HTTP response

Thibaut

**Comment by lagenar** [comment]
Try with `response.data['title']` instead of `response.body`
