### ISSUE TITLE
splash:go() does not always return the same HAR data

### ISSUE THREAD

**Issue by k-liao** [scrapinghub/splash#646]
When I call splash:go() using the url http://bit.ly/1dNVPAW and wait for 0.5 seconds using splash:wait(), I don't always get the same HAR entries (see screenshots). I'm interested in using splash:history() to build up a redirection chain that includes both JS and HTTP redirects from a given url, but I've found the HAR data to be inconsistent. 

Is there a better/more reliable API call to help with building the redirection chain?

Here's the Lua script that I'm using:
```
function main(splash)
    assert(splash:go(splash.args.url))
    splash:wait{time=0.5}
    return {
    har = splash:har(),
    }
end
```

<img width="1198" alt="screen shot 2017-07-12 at 2 37 32 pm" src="https://user-images.githubusercontent.com/12633479/28141275-bc8929f8-6710-11e7-80ac-4394639c7a3b.png">
<img width="1179" alt="screen shot 2017-07-12 at 2 37 44 pm" src="https://user-images.githubusercontent.com/12633479/28141281-c3da84ea-6710-11e7-82ff-3a9bf2caf5b5.png">

**Comment by nirvana-msu** [comment]
This is likely due to the fact that cached requests/responses do not appear in har/history. More discussion at https://github.com/scrapy-plugins/scrapy-splash/issues/168. You could solve that problem by building a custom Splash image where caching is disabled.
