### ISSUE TITLE
Splash-Jupyter not working on Docker

### ISSUE THREAD

**Issue by pleaz** [scrapinghub/splash#647]
http://splash.readthedocs.io/en/latest/kernel.html#installation
all doing as you write, but it didn't work
when run second command it write - use --allow-root (but i can't because docker don't know that command and how i can use that command i don't know)
when i run from non-root user it says not permissions for create .. /.jupyter and how to fix that path i don't know.
so it's impossible to run on docker...(and also with non-docker i had many errors too, its about pyqt5.webkit)
splash working fine.

**Comment by lordoftheflies** [comment]
+1

**Comment by marshygeek** [comment]
+

**Comment by korovkinand** [comment]
+1

**Comment by zoltan-toth-mw** [comment]
+1

**Comment by thsheep** [comment]
This is the official test problem: create splash_jupyter mirror when the shell script to start writing a less parameters ---- allow-root；

Refer to this Dcokerfile:

`FROM scrapinghub/splash:master
RUN apt-get update -q && \
    apt-get install --no-install-recommends -y \
        libzmq-dev \
        libsqlite3-0 \
        libssl-dev \
        python3-dev \
        build-essential \
        python3-cryptography \
        python3-openssl \
        libsqlite3-dev

RUN pip3 install ipython[notebook]==5.4.0 notebook==5.0.0

RUN python3 -m splash.kernel install && \
    echo '#!/bin/bash\nSPLASH_ARGS="$@" jupyter notebook --allow-root --no-browser --NotebookApp.iopub_data_rate_limit=10000000000 --port=8888 --ip=*' > start-notebook.sh && \
    chmod +x start-notebook.sh

VOLUME /notebooks
WORKDIR /notebooks

EXPOSE 8888
ENTRYPOINT ["/start-notebook.sh"]`

**Comment by deck1187hw** [comment]
+1

**Comment by 664956016** [comment]
is there anyone fix this problem?

**Comment by acowpy** [comment]
+1

**Comment by kmike** [comment]
I was able to reproduce it before the release (i.e. in Splash 3.0), but not now (i.e. with Splash 3.1). The following works:
```
docker pull scrapinghub/splash-jupyter
docker run -it -p8888:8888 scrapinghub/splash-jupyter
```
So I'm closing this issue; feel free to reopen if something is still wrong!
