### ISSUE TITLE
How should I scraping an Angular website?

### ISSUE THREAD

**Issue by lordoftheflies** [scrapinghub/splash#648]
When I try to scrape a website, written in angular, as I understand, I have to make a request to the ```...render.html``` with:

- Enable javascript
- Enable iframes

In the response the view's are not redered. How could I simulate the environment to get the same HTML result in a response as in a browser?

**Comment by kmike** [comment]
Hey,

Could you try it with Private Mode disabled? See http://splash.readthedocs.io/en/stable/faq.html#website-is-not-rendered-correctly

**Comment by lordoftheflies** [comment]
And if I click a button from a splash request attached javascript, and the button is navigate to another url (behave as a link), hogy shoul I get the new url?

**Comment by kmike** [comment]
@lordoftheflies I suggest writing a Lua script to click on this button, something like

```lua
function main(splash, args)
  splash.private_mode_enabled = false
  assert(splash:go(args.url))
  assert(splash:wait(1.0))
  splash:select('.my-button'):mouse_click()
  assert(splash:wait(5.0))
  return {
    html = splash:html(),
    final_url = splash:url()
  }
end
```

**Comment by shi-cong** [comment]
I had recvie splash rendered html output that is.
![image](https://user-images.githubusercontent.com/32175764/31977088-d24f1b7a-b900-11e7-8b39-f8b6ae04c7f1.png)

**Comment by Gallaecio** [comment]
Closing as the original issue has been solved.
