### ISSUE TITLE
Unable to docker push scrapinghub/splash:3.0

### ISSUE THREAD

**Issue by dschroh** [scrapinghub/splash#649]
In my Dockerfile (in which I'm adding proxy and filters files), I updated the `FROM` to Splash 3.0.  While I can build my derived image, I can not push it anywhere.  After testing, I found the Splash 3.0 image can't be re-tagged and pushed.  Tried on two different Macs.  Try pushing to two different private repos (one local, one in AWS Container Services).

Simple steps to reproduce:
```
docker pull scrapinghub/splash:3.0
docker tag scrapinghub/splash:3.0 xxxxx.dkr.ecr.us-east-1.amazonaws.com/my-splash:3.0
docker push xxxxx.dkr.ecr.us-east-1.amazonaws.com/my-splash:3.0
```
The result, regardless of where I try and push this tagged image, is the same layer fails every time:

```
95746a4dd561: Layer already exists
bd2322474497: Layer already exists
2cb1fcbc9ee5: Layer already exists
f81675fd8a1c: Layer already exists
f1af5605b6ac: Pushing [==================================================>]  1.011GB/1.011GB
5c117f2f586f: Layer already exists
17e82f80a5d9: Layer already exists
0566c118947e: Layer already exists
6f9cf951edf5: Layer already exists
182d2a55830d: Layer already exists
5a4c2c9a24fc: Layer already exists
cb11ba605400: Layer already exists
open /var/lib/docker/overlay2/53a6d892bc24241123ed66695cc3383d9fa64203a33fe74bc6d00e482f0afb85/merged/opt/qt59/5.9.1/gcc_64/include/Qt3DAnimation/5.9.1/Qt3DAnimation/private/evaluateblendclipanimatorjob_p.h: no such file or directory

```

Note that I have deleted my local Docker VM and re-created it, and ensured Docker for Mac is up-to-date.  Also, the same steps work fine for `splash:2.3.3`

As a workaround, I'll try to mount volumes in AWS ECS instead.

**Comment by kmike** [comment]
Hey,

I haven't seen this error, not idea what's this :( 

The intended way to set up filters and proxy profiles is to use volumes, but I can see how it can be harder, as it is no longer a single docker image. Currently I'm using docker-compose to bring this all together (see https://github.com/TeamHG-Memex/aquarium).

**Comment by dschroh** [comment]
OK, thanks.  I'll find another way.
