### ISSUE TITLE
Handle onclick event for all links in a page

### ISSUE THREAD

**Issue by ijharulislam** [scrapinghub/splash#650]
I am trying to do a simple task. But It looks very difficult to me. 
1. I want to make a list of all href's which contain onclick event like, 
`<a href="javascript:void(0);" onclick="searchAdcd('34');" id="hiroshima"><font><font>Hiroshima</font></font></a>`
Here is an url. 
https://map.yoshinoya.com/p/shopmap/
You can see around 50 hrefs contain onclick attribute. I want to click every one.

2. Then, run a loop for each a tag, load every next page by clicking onclick. I need the next page url and html content. This is very easy in selenium. But splash looks very difficult.
I tried with this lua script. But It dose not work. it is returning the same page. 

```
treat = require("treat")
function main(splash)
  local url = splash.args.url
  assert(splash:go(url))
  local links = splash:select_all('a[onclick]')
  count = 0
  local results = {}
  for i, v in ipairs( links ) do
    obj = {}
    count = count + 1
    v:click()
    obj["html"] = splash:html()
    obj["url"] = splash:evaljs("window.location.href")
    results[#results+1] = obj
  end
  return {
    html = splash:html(),
    results = treat.as_array(results),
    count = count
  }
end
```

**Comment by kmike** [comment]
`element:click()` is asynchronous, so you may need to wait until new page is loaded, e.g. by adding splash:wait after `v:click`, or by writing a loop which checks that URL changes and wait for a small amount of time if URL has not changed.

**Comment by ijharulislam** [comment]
Hi kmike,
Thanks for your quick answer. I tried with that. I am getting this error.

```
{
    "error": 400,
    "type": "ScriptError",
    "description": "Error happened while executing Lua script",
    "info": {
        "message": "Lua error: [string \"treat = require(\"treat\")\r...\"]:11: JsError({'message': 'JS error: \\'TypeError: undefined is not an object (evaluating \\\\\\'window[\"43bfe4e2-6d98-11e7-8921-0242ac130021\"][\"43c03c94-6d98-11e7-8921-0242ac130021\"]\\\\\\')\\'', 'js_error': 'TypeError: undefined is not an object (evaluating \\'window[\"43bfe4e2-6d98-11e7-8921-0242ac130021\"][\"43c03c94-6d98-11e7-8921-0242ac130021\"]\\')', 'js_error_message': 'undefined is not an object (evaluating \\'window[\"43bfe4e2-6d98-11e7-8921-0242ac130021\"][\"43c03c94-6d98-11e7-8921-0242ac130021\"]\\')', 'type': 'JS_ERROR', 'js_error_type': 'TypeError'},)",
        "source": "[string \"treat = require(\"treat\")\r...\"]",
        "type": "LUA_ERROR",
        "line_number": 11,
        "error": "JsError({'message': 'JS error: \\'TypeError: undefined is not an object (evaluating \\\\\\'window[\"43bfe4e2-6d98-11e7-8921-0242ac130021\"][\"43c03c94-6d98-11e7-8921-0242ac130021\"]\\\\\\')\\'', 'js_error': 'TypeError: undefined is not an object (evaluating \\'window[\"43bfe4e2-6d98-11e7-8921-0242ac130021\"][\"43c03c94-6d98-11e7-8921-0242ac130021\"]\\')', 'js_error_message': 'undefined is not an object (evaluating \\'window[\"43bfe4e2-6d98-11e7-8921-0242ac130021\"][\"43c03c94-6d98-11e7-8921-0242ac130021\"]\\')', 'type': 'JS_ERROR', 'js_error_type': 'TypeError'},)"
    }
}
```

**Comment by kmike** [comment]
Aha, this happens because you moved to another page, so old page is no longer loaded, and you can't click on a link from that page. So you need to go back inside the loop, after processing the target page. You may also have to select the element again, as reference is no longer valid. Currently Splash doesn't support several "browser tabs" in a single script, so it must go back and forth in such cases.

I can see a few other issues with a script: Count is not defined (Lua is case-sensitive, so it should be `count`); `splash:runjs("window.location.href")` returns nil (you likely wanted splash:evaljs; there is also `splash:url()`).

**Comment by ijharulislam** [comment]
Can you give en example of going back and forth inside loop. I edited my code. Thanks.

**Comment by kmike** [comment]
Hm, if onclick executes arbitrary JavaScript then you can't revert to a previous state; it doesn't matter if you use multiple tabs or not. So there is no a general way to "go back". It seems the best you can do it to re-load the original page by calling splash:go again. 
Likely you will also have to call splash:select again, as elements would be destroyed. You can check if an element still existis in DOM by calling [elem:exists()](http://splash.readthedocs.io/en/stable/scripting-element-object.html#element-exists).

**Comment by ijharulislam** [comment]
Thank you very much.

**Comment by wpxgit** [comment]
Is it possible to collect only the urls i've clicked instead of open them in same splash instance and return them as an array? That would it make easier to process this pages?

**Comment by ijharulislam** [comment]
@wpxgit You have to wait little bit for every click. In fact, it will not work. Because there is a time out issue in splash. If you run splash instance remotely, you can't change the global time out limit. If you have 200 onclick urls in a page, then you have to wait for every clicks of these urls. So, it is not the suggested way. 

I did the task with a simple hack. Here is my working code snippet.
Scrapy Code:

```
def parse(self, response):
        response = HtmlResponse(url=self.shops_root_url, body=response.body)
        all_links = response.xpath('*//a/@href').extract()
        link_index = 0
        for link in all_links:
          link_index = link_index + 1
          yield SplashRequest(url=self.shops_root_url, callback=self.parse_via_pages, endpoint='execute', args={'lua_source': script,'link_index':link_index})

```
Here I am getting all href's and running a loop. Actually I am sending the index of the loop to lua script as an argument.

Here is the Lua script.

```
treat = require("treat")
function main(splash)
  local url = splash.args.url
  local link_index = splash.args.link_index
  assert(splash:go(url))
  splash:wait(3)
  local links = splash:select_all('a')
  local results = {}
  for i, v in ipairs( links ) do
    if i == link_index then
        obj = {}
        links[link_index]:click()
        splash:wait(5)
        obj["html"] = splash:html()
        obj["url"] = splash:evaljs("window.location.href")
        obj["title"] = splash:evaljs("document.title")
        results[#results+1] = obj
    end
  end
  return {
    results = treat.as_array(results)
  }
end
```

You can see that I am getting all href's  here and running the same loop, but getting the only element I passed as a link_index. I hope, It will help you.

**Comment by wpxgit** [comment]
Hi ijhar,
thanks for the answer. It helps a little bit. But it's hard to use for my case because i need to filter the duplicates of new urls (doning it at the moment with scrapy dedupe filter). Don't want to write own deupe filter for lua o_O
Michael
