### ISSUE TITLE
could not get the value of document.querySelector in splash.

### ISSUE THREAD

**Issue by negabaro** [scrapinghub/splash#651]
In the next HTML, I would like to click the button whose class value is "btn login-button btn-submit btn-small" with scrapy-splash.

```
<html>
<head></head>
<body>
  <form class="login-form">
  <button class="btn login-button btn-submit btn-small" type="submit" autocomplete="off" tabindex="0" data-
  reactid="25"><!-- react-text: 26 -->login<!-- /react-text --></button>
  </form>

  <form class="login-form" action="" method="post" data-reactid="40"><div class="facebookForm regOption" data-
  reactid="41"><div class="fb-minimal" data-reactid="42"><hr data-reactid="43"><button class="btn minimal-login 
  btn-submit btn-small" type="submit" autocomplete="off" tabindex="0" data-reactid="44">Facebook Login</form>
</body>
</html>
```

my lua source is as follows.

```
function main(splash, args)
  splash:autoload([[
    function get_document_button(){
      return document.querySelector('.btn.login-button.btn-submit.btn-small');
    }
  ]])
  assert(splash:go(args.url))
  assert(splash:wait(0.5))

local search_input = splash:select('input[name=email]')
search_input:send_text("xx")
local search_input = splash:select('input[name=password]')
search_input:send_text("xx")
assert(splash:wait(5))
splash:runjs("document.querySelector('.btn.login-button.btn-submit.btn-small').click()")

return {
local title = splash:evaljs("document.title")
button = splash:evaljs("get_document_button()")

}
```
The following error appears when executed.

result:

```
 error happened while executing Lua script
'main' returned bad result. Lua function objects are not allowed.
{
    "description": "Error happened while executing Lua script",
    "error": 400,
    "info": {
        "message": "'main' returned bad result. Lua function objects are not allowed.",
        "type": "BAD_MAIN_ERROR"
    },
    "type": "ScriptError"
}
```

I don't know why couldn't get the result of "get_document_button".

I got the value of the title. but it could not take the value of a button
firstly, I'd like to check with lua script of splash to see if it is getting correctly or console.log.
any idea?

Finally, I would like to do is to log in to "netflix.com/login" and press the user select button created with javascript.

Please let me know if there is something other than the way I am going to do.

Thank you for reading my question.

**Comment by kmike** [comment]
The problem is that you're returning an Element object, which is currently not supported. Use something like `splash:evaljs("get_document_button()").outerHTML`.

See https://github.com/scrapinghub/splash/issues/564 and https://github.com/scrapinghub/splash/issues/557#issuecomment-273245797.

**Comment by negabaro** [comment]
@kmike Thank you for your commenting.
I solved this problem.
