### ISSUE TITLE
How to log Lua script execution?

### ISSUE THREAD

**Issue by gypapp** [scrapinghub/splash#652]
This is rather a question than a bug report.

I have to tackle a bit complex login process in a certain site and it would be awesome to see how my Lua script gets executed, which branches it passes and so. A sort of logging what I am searching for ... 

Unfortunately I haven't found hints or tips in the documentation so the best I could come up with so far is:

```
local element = splash:select("div.js-login")
if element then
  summary[#summary+1] = "js-login element found"
end
...
return {
  summary = summary
}
```

**Comment by kmike** [comment]
If you're running Splash locally, you can also use print("js-login element found"); these statements appear in Splash log.

**Comment by gypapp** [comment]
Thanks @kmike. It is sufficient for the time being.
