### ISSUE TITLE
Splash will terminal all the threads if one of the thread fetch the same page finish?

### ISSUE THREAD

**Issue by genius001** [scrapinghub/splash#655]
Sorry for my doubt, I remembered seems splash will stop continue fetch the same page if one of the threads finished fetch the same page. Maybe my memory is  wrong?

Assume Splash create 100 requests at the same time for fetching http://wwww.example.com
If one of the requests finished, the remain 99 requests will stop to fetch www.example.com.

Note: Maybe my memory is wrong or My test is wrong.

If Splash is doing so, I think it's not a good idea.

For example, I'm going to crawling a site's info (site such as: example.com),
I will using 100 keywords and 100 http-proxy-ip concurrently and independently,
but if one of the thread's page load finish, the remain 99 threads will stop working. that's too bad.
This will cause most of keywords request threads cannot be fetched.

Is that so?

**Comment by kmike** [comment]
Splash should not doing what you've described; if this happens it is a bug.

**Comment by genius001** [comment]
@kmike

Hey, I will close this issue.
If I encountered what I've mentioned issues and I can make sure Splash has this issue I will reopen this issue.
