### ISSUE TITLE
cannot call string.match or string.gmatch

### ISSUE THREAD

**Issue by jiaruita** [scrapinghub/splash#658]
When I tried to call string.match or string.gmatch, error reported as this: 
"error": "attempt to call field 'gmatch' (a nil value)",

If I change to use find, with everything else unchanged, it will succeed.
I'm new to splash and lua, is there anything I misunderstand?

codes are here:
```
function main(splash, args)
	assert(splash:go(args.url))
	assert(splash:wait(2))
	results = {}
	html = splash:html()
	result = string.gmatch(html, "<a href=javascript:(.-)>")
	return {
		html = html,
		htmltype = type(html),
		findresult = result,
	}
end
```

thanks!

**Comment by jiaruita** [comment]
Okay, I tried adding --disable-lua-sandbox argument and it worked.
However, as the document(http://splash.readthedocs.io/en/latest/scripting-libs.html#standard-library) says, string library is one of the standards libraries available when sandbox is enabled?

**Comment by kmike** [comment]
There is a note below: 

> Not all functions from these libraries are currently exposed when Sandbox is enabled.

All available functions are listed here: https://github.com/scrapinghub/splash/blob/master/splash/lua_modules/sandbox.lua

**Comment by jiaruita** [comment]
thanks, my mistake!
