### ISSUE TITLE
Can i use io.read() in Lua script?

### ISSUE THREAD

**Issue by gilarus** [scrapinghub/splash#659]
I try to build an interactive spider by using io.read() of lua in script like this:

`local line = io.read()`

But Splash hang up... whatever i type in stdin, it never give a response. WHY?

ps: sandbox  was turned off,   `docker run -it -p 8050:8050 scrapinghub/splash --disable-lua-sandbox`

**Comment by kmike** [comment]
No idea why isn't it working. I didn't have this use case in mind and have never tried it. There is no special stdin handling in Splash. I'm fine with merging a pull request to make this work, but unfortunately I won't have time to debug the issue myself.

**Comment by gilarus** [comment]
@kmike maybe i found why, i login my server twice with two open (putty) ssh window. And one used for launching docker, let's call it docker terminal, another one used for scrapy, let's call it scrapy terminal. Whatever i do input on scrapy terminal, it never response. Then i switch to docker terminal and type something and do ENTER. It works. :-)
