### ISSUE TITLE
qt.network.ssl error?

### ISSUE THREAD

**Issue by genius001** [scrapinghub/splash#661]
qt.network.ssl: QSslSocket: cannot resolve SSLv2_client_method
qt.network.ssl: QSslSocket: cannot resolve SSLv2_server_method

Above info is created by launch 'python3 -m splash.server'
but Splash not crashed, it can continues work.

**Comment by onepiece8971** [comment]
+1
2.3.3 can work
3.0/latest always *.js 404 153

**Comment by amarynets** [comment]
+1
Have the same issue
Use Docker with Splash 3.0, Linux Mint 18.1

**Comment by shi-cong** [comment]
+1
use with docker, latest splash
