### ISSUE TITLE
How can i edit the content of form which embedded in iframe?

### ISSUE THREAD

**Issue by gilarus** [scrapinghub/splash#663]
I did know render.json can render iframes perfectly. But i need to do some input by using Lua script with /execute ep. And the fact was that /execute will not render iframe .(this was the standard behavior of browser). So, is there any way to do that ?

ps: I need to input some data, and submit the data( do click on the button which embedded with iframe too).

**Comment by gilarus** [comment]
i think it can be solved by using [_Splash Scripts API_ ](https://splash.readthedocs.io/en/stable/scripting-ref.html#splash-send-text).

**Comment by ezDataCode** [comment]
@ghost, how did you resolve this issue?
I too am having difficulty using lua script to interact with a form that is within an iframe. Did you find a solution?
