### ISSUE TITLE
why will we have different results with splash and chrome accessing same website?

### ISSUE THREAD

**Issue by habout632** [scrapinghub/splash#666]
why will we have different results with splash and chrome accessing same website?
https://flight.qunar.com/site/oneway_list_inter.htm?searchDepartureAirport=%E6%B7%B1%E5%9C%B3&searchArrivalAirport=%E4%BC%A6%E6%95%A6&searchDepartureTime=2017-09-27&searchArrivalTime=2017-09-30&nextNDays=0&startSearch=true&fromCode=SZX&toCode=LON&from=qunarindex&lowestPrice=null&favoriteKey=&showTotalPr=null&adultNum=1&childNum=0&cabinClass=

**Comment by habout632** [comment]
we found lost some cookie info

**Comment by habout632** [comment]
we don not know the reason

**Comment by kmike** [comment]
Hey, I haven't looked at the website yet, but have you tried suggestions from http://splash.readthedocs.io/en/stable/faq.html#website-is-not-rendered-correctly?

**Comment by habout632** [comment]
ok i will try
https://flight.qunar.com/twell/flight/inter/search?depCity=%E6%B7%B1%E5%9C%B3&arrCity=%E4%BC%A6%E6%95%A6&depDate=2017-09-27&adultNum=1&childNum=0&from=qunarindex&ex_track=&es=F3kz7NpJ7Ny%2B7IpJ%2FLSh7dom%2FLeoeUzJ%2FLgz%3D%3D%3D%3D%7C1504945616333

**Comment by habout632** [comment]
![qq 20170909013229](https://user-images.githubusercontent.com/3166070/30238982-3ddaeab8-9507-11e7-8e31-af964b210d52.png)

**Comment by habout632** [comment]
![qq 20170909013311](https://user-images.githubusercontent.com/3166070/30238985-50ea95ae-9507-11e7-9feb-a789b5e357a6.png)

**Comment by habout632** [comment]
above picture shows splash result following used chrome

**Comment by liangWenPeng** [comment]
Hey ，Can you try this url ?http://v.cmcm.com/video.html?vid=W-5OYeHeVDiUBgIzR0LlNg&uid=IfvpUzE2tMewLlIUy/qAdg==&vid=W-5OYeHeVDiUBgIzR0LlNg
I have set wait=5, splash:set_viewport_size(1980, 1020) splash.plugins_enabled = true ,but it doesn't work.

**Comment by kmike** [comment]
@liangWenPeng this script works for your website:

```lua
function main(splash, args)
  splash.plugins_enabled = true
  splash.private_mode_enabled = false
  assert(splash:go(args.url))
  assert(splash:wait(5))
  return {
    html = splash:html(),
    png = splash:png(),
    har = splash:har(),
  }
end
```

Note added `splash.private_mode_enabled = false`; see [FAQ](http://splash.readthedocs.io/en/stable/faq.html#website-is-not-rendered-correctly) for the explanation on why this may help. It also works for @habout632's website. I'm using Splash 3.0.

**Comment by liangWenPeng** [comment]
@kmike Thank you very much. It's effective.

**Comment by magichuihui** [comment]
@kmike Can you help me with this url？http://yuntv.letv.com/bcloud.html?uu=vbdcxh1r0y&vu=19daac6381&auto_play=1&width=480&height=320&lang=zh_CN
I have tried what u said above, but it didn't work.
