### ISSUE TITLE
How to release memory in splash 3.0

### ISSUE THREAD

**Issue by syncml** [scrapinghub/splash#674]
I'm using splash 3, and when render pages are growing, memory doesn't seem to be released, and when it grows to a certain extent, the docker container be force stoped. Where can I release memory?.
BTW, I'm using the scrapy-splash operation splash

Thanks for everyone

**Comment by cristianocca** [comment]
I believe python processes never really release the all the requested memory to the OS on linux, for some specific reasons, so over time the process will have as much memory as it needed at some point and never release it back unless killed.
https://stackoverflow.com/questions/15455048/releasing-memory-in-python
