### ISSUE TITLE
Can't release memory in splash 3.0

### ISSUE THREAD

**Issue by lt82654993** [scrapinghub/splash#676]
I'm also can't release memory in splash 3.0. Using command “curl -X POST http://localhost:8050/_gc” can collection a part of GC, but still exist and increasing memory with  following requests. Then, it will be forced stop .How can  I solves it? Thanks very much.

**Comment by toshunster** [comment]
@lt82654993 there are --restart=always and --rssmax options. 
`docker run -p 8050:8050 -p 5023:5023 --restart=always scrapinghub/splash --max-timeout 90 --slots 3 --maxrss 300`

**Comment by lt82654993** [comment]
what's means `slots` ? So far, I don't  find  it out. The "maxrss" param means that one process will consume 300KB?

**Comment by toshunster** [comment]
@lt82654993 slots it's

> Splash renders requests in parallel, but it doesn’t render them all at the same time - concurrency is limited to a value set at startup using --slots option. When all slots are used a request is put into a queue. The thing is that a timeout starts to tick once Splash receives a request, not when Splash starts to render it. If a request stays in an internal queue for a long time it can timeout even if a website is fast and splash is capable of rendering the website.

maxrss means 300mb for one process.

**Comment by lt82654993** [comment]
Thanks a lot !

**Comment by syncml** [comment]
@lt82654993 

Hi, what is the result?

**Comment by iamsoorena** [comment]
this is serious.

**Comment by Gallaecio** [comment]
See #674
