### ISSUE TITLE
[Authentication Problem]docker render server can be private ?

### ISSUE THREAD

**Issue by edwards1990** [scrapinghub/splash#687]
thanks for so useful web spider server.
now I want create my private scrapy-splash docker server on AWS  for many scrapy tasks.
but on the product the 8050 port be published ,it may take a risk.
it will have any key authentiation or user\password as paramters to stop un-auth users？

sorry about my poor English, 
wish you can understand what i said.
look forward your reply...

**Comment by toshunster** [comment]
Did you try [Aquarium](https://github.com/TeamHG-Memex/aquarium)?
It' load balancer daemon, when you init it you can pass login and password for it.

**Comment by kmike** [comment]
Yeah, the idea is to run something like Aquarium. It is needed for other reasons as well.
