### ISSUE TITLE
Proxy in splash not loading all elements

### ISSUE THREAD

**Issue by toshunster** [scrapinghub/splash#692]
I tried to use proxy via splash (via params 'proxy=user:password@ip:port') but some content of the page is not visible (left menu is infinity loading status). However, when I use this proxy via a browser (Firefox) everything is ok!

The example link: https://www1.ticketmaster.com/new-jersey-devils-vs-florida-panthers-newark-new-jersey-11-11-2017/event/020052DAA46A2DAE

[Link to image where right menu is loading](https://i.stack.imgur.com/Q8Xlo.png)

Why can't I load all elements?

**Comment by Gallaecio** [comment]
Did you solve your issue?

**Comment by toshunster** [comment]
> Did you solve your issue?

Actually not, but this is no longer relevant to me.
