### ISSUE TITLE
Use of https proxy with splash

### ISSUE THREAD

**Issue by cp2587** [scrapinghub/splash#693]
Hello,

We are trying to use a proxy that only accepts https connection together with the `proxy` parameter of the `execute` endpoint. To better explain this, it means the proxy we are using only uses the CONNECT method, you cannot use a regular http:// request.

When doing so we are getting the following error: Invalid proxy URL format.

Would you accept PR to fix this issue ? Do you have a clue on where to start ?

**Comment by kmike** [comment]
Hm, if you need to use different proxy for http and https requests, you can set proxy dynamically in splash:on_request based on request URL. Would it work for you?
