### ISSUE TITLE
why cookie can not be init or added?

### ISSUE THREAD

**Issue by SethWen** [scrapinghub/splash#694]
I installed docker container of scrapinghub/splash. I wrote lua script according your official doc.But request cookie can not be set successfully. The code is folowing.

     function main(splash, args)
       print('1111111111111 --> ')
       splash:add_cookie{"sessionId", "237465ghgfsd", "/", domain="http://www.baidu.com"}
       local ok, reason = splash:go('http://www.baidu.com/')
       print('result --> ', ok)
  
       return {
         html = splash:html(),
         png = splash:png(),
         har = splash:har(),
       }
     end

**Comment by kmike** [comment]
I'm not sure it is the only thing which causes a problem for you, but 'domain' should be `www.baidu.com`, `.baidu.com` or `baidu.com`, not `http://www.baidu.com`.
