### ISSUE TITLE
setting proxy server is useless

### ISSUE THREAD

**Issue by SethWen** [scrapinghub/splash#695]
I want to set proxy server. I test it using Fiddler. I can not find the request in fiddler, and also, I set a invalid host，also request successfully。That is my code.
 
    function main(splash, args)
    splash:on_request(function(request)
        request:set_proxy{
            host = '127.0.0.1',
            port = 8888,
            username = '',
            password = '',
            type = "HTTPS",
        }
    		end)
    local ok, reason = splash:go('http://www.baidu.com/')
  
    print('result --> ', ok)
  
    return {
       html = splash:html(),
       png = splash:png(),
       har = splash:har(),
     }
    end

**Comment by landoncope** [comment]
Try:

`splash:on_request(function(request)
    request:set_proxy{
        '127.0.0.1',
        8888,
        username = '',
        password = '',
        type = "HTTPS",
    }`

**Comment by kmike** [comment]
"HTTPS" is not a valid proxy type, use "HTTP" (it works for https as well). See http://splash.readthedocs.io/en/stable/scripting-request-object.html#request-set-proxy.
