### ISSUE TITLE
Some pages take over 60s to render

### ISSUE THREAD

**Issue by nikola-barac** [scrapinghub/splash#696]
Hey Team,

Some pages take over 1min to be retrieved, eg:
http://www.ebay.de/itm/Original-Volkswagen-Lego-T1-Bulli-Campingbus-211099320-BL9-10220/263312959468?epid=129670778

I don't believe the site has some kind of a protection since in the end the page is retrieved (I also tried with PhantomJS and was able to render it in a few seconds)

This is the command I used:
`curl 'http://localhost:8050/render.html?url=http://www.ebay.de/itm/Original-Volkswagen-Lego-T1-Bulli-Campingbus-211099320-BL9-10220/263312959468?epid=129670778&timeout=90'`

Do you have any hints if this can be fixed on a client (my side) or at least the way to debug it to see why it takes that long? 

The possible reason might be the **iframes** on this page and since the `resource_timeout` stops the execution, would it be possible to grab what the browser got when the timeout occurred?

Cheers,
Nikola

**Comment by kmike** [comment]
You can use Splash UI to check which resources take long time to load, and filter them out using either splash:on_request or adblock filters. Another option is to use more aggressive respource_timeout - in your example command resource_timeout is not used at all.
