### ISSUE TITLE
Use element:mouse_click

### ISSUE THREAD

**Issue by wansisi** [scrapinghub/splash#704]
I tried to use element:mouse_click to load the next page,here is my code. The code can work properly, but to see consequences of click reflected in page source  I have to use splash:wait(3). In the official document, it saied "Unlike splash:mouse_hover, element:mouse_hover waits until event is propagated, so to see consequences of click reflected in a page there is no need to call splash:wait.", so ,I don't know if I can get the consequences of click reflected in a page without using splash:wait

`function main(splash, args)
  assert(splash:go(args.url))	
  local element2=splash:select('.scy_tylb_fy-nr ul li:nth-child(7) a')
  local bounds = element2:bounds()
  assert(element2:mouse_click(x=bounds.width/3, y=bounds.height/3))
  splash:wait(3)
  		
  return {
    html = splash:html(),
    png = splash:png(),
  }
end`

**Comment by kmike** [comment]
Even if event is propagated, you may still have to wait for a page load if there is a redirect or other async action. Technically, docs are correct: a consequece of click is that a redirect starts, but you still need to wait for it to finish.
