### ISSUE TITLE
Splash doesn't load webpage

### ISSUE THREAD

**Issue by ievgenburdin** [scrapinghub/splash#705]
Hello everyone!
I am new with splash. After run docker image, splash doesn't load any web pages. It doesnt work from web interface or from scrapy spider. May be somebody solved that problem.

![image](https://user-images.githubusercontent.com/22210549/33882307-593dd062-df40-11e7-83aa-9bafb208f213.png)

![image](https://user-images.githubusercontent.com/22210549/33882541-1b7e868a-df41-11e7-83b3-3f622ceb7ab6.png)

**Comment by kmike** [comment]
Splash returns "host not found" error, maybe there was a temporary issue with your internet connection? I can't reproduce the issue, rendering works fine for me for this website with latest Splash.
