### ISSUE TITLE
Splash does not support the getEventListeners function?

### ISSUE THREAD

**Issue by dean2021** [scrapinghub/splash#718]
Splash does not support the getEventListeners function?  My code:

// JS events that trigger all DOM element binding
var eles = document.getElementsByTagName('*');
for (x in eles) {
    elm = eles[x]
    if (typeof(elm) == 'object') {
        dom_event = getEventListeners(elm)
        if (JSON.stringify(dom_event) != "{}") {
            for (event_name in dom_event) {
                try {
                    dom_event[event_name][0].listener.call(elm);
                } catch (err) {console.log(err)}
            }
        }
    }
}

**Comment by Gallaecio** [comment]
Did you solve your issue?

**Comment by dean2021** [comment]
> Did you solve your issue?

yes
