### ISSUE TITLE
Add Wiki page or someting similar to explain how to use splash with scrapy

### ISSUE THREAD

**Issue by redapple** [scrapinghub/splash#72]
Although splash and scrapy are independent project, they are often used together.

But the setup is apparently not that straightforward (see for example https://stackoverflow.com/questions/21564234/how-to-integrate-javascript-rendering-module-to-scrapy)

It would be nice to have a step-by-step guide on how to make scrapy and splash work together nicely.

**Comment by pawelmhm** [comment]
responding to @redapple original comment, now we have 

https://github.com/scrapinghub/scrapy-splash

does it mean we can close this ticket?

**Comment by pablohoffman** [comment]
Yeah, it's even in the README (although it says ScrapyJS instead of scrapy-splash) so I think we can consider this closed.
