### ISSUE TITLE
Content Security Policy

### ISSUE THREAD

**Issue by mhsn06** [scrapinghub/splash#720]
splash:select('title')

The following errors occur on the above line
[string "function main(splash, args)
..."]:33: cannot select the specified element {'message': 'JS error: \'EvalError: Refused to evaluate a string as JavaScript because \\\'unsafe-eval\\\' is not an allowed source of script in the following Content Security Policy directive: "script-src \\\'report-sample\\\' \\\'sha256-6gLjSWp3GRKZCUFvRX5aGHtECD1wVRgJOJp7r0ZQjV0=\\\' \\\'unsafe-inline\\\' 

How to handle this error?

**Comment by kmike** [comment]
Currently there is no good workaround; you can strip CSP headers using a proxy in front of Splash to disable these checks.

**Comment by kmike** [comment]
Closing it as a duplicate of https://github.com/scrapinghub/splash/issues/313.
