### ISSUE TITLE
Monitoring Splash from command line

### ISSUE THREAD

**Issue by hpntk** [scrapinghub/splash#728]
Is there a way to monitor Splash activity similar to the output given when running the `run` command? Say the command line window closed, how would you get back to that output?

I'm aware it's possible to monitor processes with `_debug`, `docker stats` and `top`, but looking for something that will print the Splash "activity log" so to speak. Similar to `_debug` but a consistent output.

Thanks!

**Comment by kmike** [comment]
There is `docker logs` command; you can also mount a folder and write log to a file using Splash `--logfile` option.

**Comment by hpntk** [comment]
`sudo docker logs -t --tail=50 -f` worked perfectly for me. Thanks!
