### ISSUE TITLE
Got detected by Trivago

### ISSUE THREAD

**Issue by vionemc** [scrapinghub/splash#729]
If I try to scrape Trivago using Splash, the first scrape is okay, but I always get captcha for the next ones

**Comment by lopuhin** [comment]
Hey @vionemc ,

We're using Scrapy issue tracker to track Scrapy bugs and discuss new Scrapy features; for support there are better channels like https://stackoverflow.com (use tag "scrapy") or https://www.reddit.com/r/scrapy/.

**Comment by lopuhin** [comment]
Hey @We're using Scrapy issue tracker to track Scrapy bugs and discuss new Scrapy features; for support there are better channels like https://stackoverflow.com (use tag "scrapy") or https://www.reddit.com/r/scrapy/.

**Comment by kmike** [comment]
Hey @vionemc,

I'm not sure it is a right place to discuss such issues. Splash is a headless browser after all, not a captcha bypass service.
