### ISSUE TITLE
Add authentication to splash server

### ISSUE THREAD

**Issue by tamoyal** [scrapinghub/splash#73]
Would authentication be a welcomed feature or do you suggest it's handled elsewhere?  I did some quick [poking around](http://twistedmatrix.com/documents/current/core/howto/cred.html) and it doesn't seem too difficult to add.  I'm still evaluating splash but happy to do it if I move forward with it!

**Comment by kmike** [comment]
Now I think that way to go is to setup HTTP auth in a load balancer. I'm closing this ticket now, but will be happy to reopen and  discuss it further if someone disagrees.
