### ISSUE TITLE
Discussion regarding GSoc 18

### ISSUE THREAD

**Issue by K-ratos** [scrapinghub/splash#731]
Hello 
I am Abhishek, currently a Computer Science udergrad student at BIT Mesra,Ranchi India. I am aiming for GSoc this year. I read about splash and interested in it, i'd like contribute to this project please give me some pointers where to start.

Thank You!!

**Comment by kmike** [comment]
Hey @K-ratos,

Sorry for a late answer! We were not preparing a GSoC for Splash specifically, but adding WebEngine support can be a GSoC project which I can mentor. A general idea is this: https://github.com/scrapinghub/splash/issues/349#issuecomment-280772041.

**Comment by K-ratos** [comment]
hey @kmike 
I read your comment and i tried to read through browsertab.py, if i am not mistaken i have to implement those methods which are implemented using qtwebkit, again using qtwebengine. should i draft the proposal, so that you can review it or should i first do something with splash ? please help me with the proposal.

**Comment by kmike** [comment]
Hey @K-ratos,

Yes, that's right - implement methods which use QtWebKit, but using QtWebEngine. Likely there should be BaseBrowserTab class with common logic and WebkitBrowserTab + WebEngineBrowserTab classes with engine-specific code. It is fine to not refactor classes this way at the beginning - e.g. we can rename current BrowserTab class to WebkitBrowserTab and create a minimal WebEngineBrowserTab from scratch.

For the applications we require both a proposal and contribution. I suggest starting with a prototype. A perfect prototype is 

1) an option to switch to QtWebEngine for the render.html endpoint; 
2) render.html endpoint which works with QtWebEngine when this option is enabled - it doesn't have to support any arguments for now - js_source, wait, etc. - the goal is just to make it render something; 
3) a test for this change.

I think after implementing this prototype you can get a basic understanding of Splash codebase, and it would be easy to write a proposal at this stage. By doing it you also can demonstrate that you can handle this project, such prototype can be very convincing.
