### ISSUE TITLE
--lua-sandbox-allowed-modules flag/argument on Docker container not working

### ISSUE THREAD

**Issue by tosaddler** [scrapinghub/splash#733]
I am trying to run the splash Docker container on Ubuntu 16.04 and when I try and run the following command:

`docker run -p 8050:8050 -p 5023:5023 -v /modules:/etc/splash/lua_modules --lua-sandbox-allowed-modules 'module1' --name splash scrapinghub/splash`

I receive the following message:  "unknown flag: --lua-sandbox-allowed-modules"

[I was following the directions on this page.](http://splash.readthedocs.io/en/stable/install.html?highlight=modules) Are the directions out of date, am I running the command incorrectly, or is there another issue? I am able to get the Docker container running using the command `--disable-lua-sandbox` but it would be nice to get it working properly.

**Comment by kmike** [comment]
Thanks for the heads up @tosaddler! Command in docs was incorrect - you need to pass Docker options before the image name, and Splash options after the image name. So it should be something like this:

 `docker run -p 8050:8050 -p 5023:5023 -v /modules:/etc/splash/lua_modules --name splash scrapinghub/splash --lua-sandbox-allowed-modules 'module1' `.
