### ISSUE TITLE
Splash not obeying cpuset

### ISSUE THREAD

**Issue by hpntk** [scrapinghub/splash#737]
Running on CentOS 2xCPU box with:

`sudo docker run -it --cpuset-cpus=0 -d -p 8050:8050 -p 5023:5023 --restart=always scrapinghub/splash --maxrss 4000 --slots=50`

Everything seemed to work fine when load was minimal (beginning of chart), Splash maxed at 50-60% of CPU power which seems correct.  When number of requests increased, CPU blew past this and maxed out both cores it seems (right side of chart).

Any thoughts on why this is happening?

![cpu](https://user-images.githubusercontent.com/27933405/36407916-1305699a-15d0-11e8-9f3c-f47465648cb2.png)

**Comment by lopuhin** [comment]
@hpntk does this also happen if you use ``--cpus 1`` instead of ``--cpuset-cpus=0``?

**Comment by hpntk** [comment]
Sorry to abandon this issue @lopuhin, but I've moved to the Aquarium / HAProxy setup and no longer have an environment (or time) to test your suggestion on.

My only thought is that there could be some sort of internal "load balancing" that the machine does (Google Compute Instance) when running processes, sending new requests to execute on the CPU with the least load. Long shot since I believe setting `--cpus` binds the process to the uuid of the processor (?), but it's my only thought.

**Comment by lopuhin** [comment]
Thanks for an update @hpntk , indeed GCE might be important here! Great to hear that you moved to Aquarium.

>  Long shot since I believe setting --cpus binds the process to the uuid of the processor (?), but it's my only thought.

I'm not sure myself, but from past experience docker processes running under ``--cpus`` could end up running on any core on a multi-core machine.
