### ISSUE TITLE
JS error:  'TypeError: undefined is not an object'

### ISSUE THREAD

**Issue by tosaddler** [scrapinghub/splash#738]
```
function main(splash)
    splash:autoload([[
        function pubchem_scroll() {
            var pubchem_sections = ["Pharmacology-and-Biochemistry", "Absorption-Distribution-and-Excretion"];
            for (i = 0; i < pubchem_sections.length; i++) {
                $('html,body').animate({scrollTop: $("#"+pubchem_sections[i]).offset().top}, 250);
            }
        }
    ]])
  
  assert(splash:go("https://pubchem.ncbi.nlm.nih.gov/compound/2242"))
  splash:wait(1)
  splash:evaljs("pubchem_scroll()")
  return splash:html()
end
```

I am trying to scrape websites [like this](https://pubchem.ncbi.nlm.nih.gov/compound/2244). I am running Splash 3.1 in a Docker container and inputting this script in the web interface. When I run it I am getting this error:
```
{
    "type": "ScriptError",
    "error": 400,
    "description": "Error happened while executing Lua script",
    "info": {
        "type": "JS_ERROR",
        "line_number": 13,
        "js_error_message": "undefined is not an object (evaluating '$(\"#\"+pubchem_sections[i]).offset().top')",
        "message": "[string \"function main(splash)\r...\"]:13: JS error: 'TypeError: undefined is not an object (evaluating \\'$(\"#\"+pubchem_sections[i]).offset().top\\')'",
        "error": "JS error: 'TypeError: undefined is not an object (evaluating \\'$(\"#\"+pubchem_sections[i]).offset().top\\')'",
        "splash_method": "evaljs",
        "js_error": "TypeError: undefined is not an object (evaluating '$(\"#\"+pubchem_sections[i]).offset().top')",
        "js_error_type": "TypeError",
        "source": "[string \"function main(splash)\r...\"]"
    }
}
```

When I go to the webpage and input my function into the developer console then call it, it works just fine. When I put it into the lua script though I've tried a million different things to get it to work. Is this a splash error or am I just being a noob. Thanks for any assistance that you may be able to give me.

**Comment by ImNotRoot** [comment]
I have the same error, but I with splash:select(".foo").mouse_click()

**Comment by Gallaecio** [comment]
@tosaddler Did you ever manage to solve your issue?

**Comment by tosaddler** [comment]
@Gallaecio I did not, and to be honest I gave up on Splash for my particular purpose.

I discovered the website I was trying to scrape (PubChem) actually had a undocumented functions in their API that gave me the information that I needed. Also, their website has been heavily updated since I last tried to use Splash for this purpose and it may work differently now than it did in the past.

You can close this issue if you wish.
