### ISSUE TITLE
Splash slots and HA Proxy health checks.

### ISSUE THREAD

**Issue by nehakansal** [scrapinghub/splash#748]
Hi,

I am using HA Proxy (via Aquarium) to run Splash. In the version that I am using, Splash slots are set to 5 and the HA Proxy is set up to perform a health check every 2 seconds. Does the health check need an empty slot and the timeout setting gets applied to the health check as well? So basiclly, if all 5 slots of a splash instance are busy executing a request for longer than (2 seconds + the timeout value) - does that mean that the health check will fail? 

Thanks,
Neha.

**Comment by kmike** [comment]
Hey @nehakansal,

Splash slot is not needed to perform a health check, slots only limit a number of /render.??? and /execute jobs executed in parallel.

**Comment by nehakansal** [comment]
Okay, good to know, thanks. There are times when I notice, in the docker logs, that the health checks dont get logged for some time (may be when splash is unresponsive for some reason even though I dont see any logs that show it went down) and then I see a bunch of health checks all together logged within one second. Any idea what scenarios would cause that to happen?

**Comment by kmike** [comment]
It may happen when there is some long-running CPU-intensive task. Splash is single process, concurrency is achieved using event loop. It means that e.g. when Splash is encoding a screenshot, it can't answer for network requests, as it doesn't yield to the event loop. Same thing may happen if a website does something which stops the event loop (though I'm not sure I've seen this).

**Comment by nehakansal** [comment]
Okay, thanks, that is helpful.
