### ISSUE TITLE
Using HA Proxy (Aquarium), still getting lot of 504/503 errors.

### ISSUE THREAD

**Issue by nehakansal** [scrapinghub/splash#750]
I am using HA Proxy (via Aquarium) and I also increased the timeout setting to 300 just to have a higher value for testing. I get a bunch of 504 timeout errors (in the docker logs) on urls that I am pretty sure are quick to crawl. And I also get 503s service unavailable errors (in the crawl logs - running Splash for Undercrawler - https://github.com/TeamHG-Memex/undercrawler). HA Proxy stats page shows that it couldnt reach Splash for a few minutes and I don't see splash-going-down related errors. Each crawl is different, doesnt produce similar number of errors each time. I would think that since HA Proxy manages the request queue, 503/504 should not ideally happen.  What could cause these errors?

**Comment by nehakansal** [comment]
It seems I was most like getting these due to running out of memory. Please see issue #757

**Comment by Gallaecio** [comment]
Closing this in favor of https://github.com/scrapinghub/splash/issues/757
