### ISSUE TITLE
Click button doesn't work on avito.ru

### ISSUE THREAD

**Issue by alexanderlukanin13** [scrapinghub/splash#753]
We are scraping some pages from avito.ru, and there is one particular button ("Display phone") that we can't click via Splash. Everything else works. We've tried multiple different ways to click, but all attempts were unsuccessful. And, of course, we checked validity of selector many times - the problem is not in selector, the same JS code works in Chrome.

The problem is described in detail and with illustrations here: https://stackoverflow.com/q/49276401/902013

And here's the minimal example to reproduce it
https://github.com/alexanderlukanin13/splash-avito-phone

We finally gave up and implemented a workaround, so it's not a big problem for us. But still, I'm reporting this issue, in case you want to do something about it.

**Comment by kmike** [comment]
I've answered it in stackoverflow: selector was wrong, and website required `splash.private_mode_disabled=true`. http://splash.readthedocs.io/en/stable/faq.html#website-is-not-rendered-correctly has a list of common issues and their workarounds.
