### ISSUE TITLE
How is the timeout limit reached calculated?

### ISSUE THREAD

**Issue by nehakansal** [scrapinghub/splash#758]
I read [here](http://splash.readthedocs.io/en/stable/faq.html#splash-instance-is-overloaded), that a timeout starts to tick once Splash receives a request, not when Splash starts to render it. So, if HA Proxy is being used (via aquarium), does the timeout start to tick as soon as the request gets added to the HA proxy queue?

**Comment by landoncope** [comment]
No, the timeout does not start to tick in that case. Splash doesn't know about the request while it resides in the HA Proxy queue (you may need to increase http request timeouts in your code though). Splash does its own queueing as well. If a request gets put in the Splash queue then yes, the timeout would start to tick.

However, that is never an issue if you are setting your HAProxy maxconn to the same value as your Splash --slots setting.

**Comment by nehakansal** [comment]
So Splash's own queueing will be used only when HA Proxy maxconn > Splash slots, correct?

**Comment by landoncope** [comment]
> So Splash's own queueing will be used only when HA Proxy maxconn > Splash slots, correct?

Correct
