### ISSUE TITLE
Splash slots and HA Proxy maxconn.

### ISSUE THREAD

**Issue by nehakansal** [scrapinghub/splash#759]
I am using Aquarium for my Splash setup. I wanted to make sure I understand the interaction between Splash slots and HA Proxy maxconn correctly. If the Splash slots are set to 10, but the maxconn is set to 5 - does that mean only 5 slots will be used because HA Proxy won't send more than 5 requests at a time? Thanks.

**Comment by landoncope** [comment]
Slots are basically browser tabs. Your understanding is correct.
