### ISSUE TITLE
how to simulate a call or click on button in python script 

### ISSUE THREAD

**Issue by jayjgal** [scrapinghub/splash#768]
Hello: I am new to splash and writing a python script that uses splash by adapting code from the example found here: https://github.com/EdmundMartin/SplashCrawler/blob/master/splashscrape.py

I would like to be able to add in splash functions that allow me to do things like take a screenshot and click on buttons. Specifically, I need to click on a button that loads additional data into the web page.

I believe the lua script needs to be put inside a python function or method based on the format below that's described here: http://splash.readthedocs.io/en/stable/faq.html#using-http-api

I have read the documents and also numerous questions and issues and tried various ways to use splash:select and mouse:click functions but can't get anything to work with a python function. 

Any additional explanation or ideally examples would be greatly appreciated. 

script = """
splash:go(args.url)
return splash:png()
"""
resp = requests.post('http://localhost:8050/run', json={
    'lua_source': script,
    'url': 'http://example.com'
})
png_data = resp.content

**Comment by Gallaecio** [comment]
Please, use [StackOverflow](https://stackoverflow.com/tags/splash-js-render) to ask this type of questions.
