### ISSUE TITLE
Splash Not Rendering The Right Page

### ISSUE THREAD

**Issue by andreg3g3** [scrapinghub/splash#771]
I was trying to scrape some pages from lazada using scrapy-splash :

- https://www.lazada.sg/shop-mobiles/?page=1
- https://www.lazada.sg/shop-mobiles/?page=2
- https://www.lazada.sg/shop-mobiles/?page=3

And here is my script : 
```
function main(splash, args)
  local num_scrolls = 3
  local scroll_delay = 2.0
  assert(splash:go(args.url))
  assert(splash:set_viewport_full())
  assert(splash:wait(5.0))
  return {
    html = splash:html(),
    png = splash:png(),
    har = splash:har(),
  }
end
```

When I compared the real website and image + html rendered from the first link using Web UI of splash, I found that they're different. Then I splash rendered the other links, the render results are same, even the links are different, they have the same images! I have tried many wait delays : 2.0 , 3.0 , 5.0 and 10.0 but the results still the same. I couldn't even download the rendered image from the Web UI, it said download failed - Network error. What did I miss?

**Comment by Gallaecio** [comment]
Please, use [StackOverflow](https://stackoverflow.com/tags/splash-js-render) to ask this type of questions.
