### ISSUE TITLE
Issue with Splash returning multiple html snapshots

### ISSUE THREAD

**Issue by rohitkoganti** [scrapinghub/splash#785]
Hi,

I'm trying to return multiple html pages using splash scripts (in a single response, as in the documentation) and extracting the links from them. But I found that in the response.text and response.body, the html content is morphed whenever there's more than one page returned.  This is not the case with response.data which works fine. Why is this happening? 

I tried this on the same code (and website) as in the documentation- http://splash.readthedocs.io/en/stable/scripting-ref.html#splash-html (from the later part, from the example for multiple html snapshots)

This is my splash request-->
```
 yield Request(url= url, callback= self.parse, dont_filter=True, meta={
     'splash': {
          'args': {'lua_source': self.lua_source, 'timeout': 200},
          'endpoint': 'execute',
       },
 })
```
The lua script looks like this -->
```
  function page_info(splash, url)
      splash:go(url)
      local res = {
        html=splash:html(),
       }
      return res
  end
  
  function main(splash, args)
      local base = "https://news.ycombinator.com/news?p="
      local result = treat.as_array({})
      for i=1,3 do
        local url =  base .. i
        result[i] = page_info(splash, url)
      end
      return result
  end
```
The resulting response:
response.data -->
`{u'html': u'<html op="news"><head><meta name="referrer" content="origin"><meta name="viewport" content="width=device-width, initial-scale=1.0"><link rel="stylesheet" type="text/css" href="news.css?i7azI8MkFRPfcPhHQ7HD">\n            <link rel="shortcut icon" href="favicon.ico">\n          <link rel="alternate" type="application/rss+xml" title="RSS" href="rss">\n        <title>Hacker News</title>`

response.text and response.body -->
`u'[{"html": "<html op=\\"news\\"><head><meta name=\\"referrer\\" content=\\"origin\\"><meta name=\\"viewport\\" content=\\"width=device-width, initial-scale=1.0\\"><link rel=\\"stylesheet\\" type=\\"text/css\\" href=\\"news.css?i7azI8MkFRPfcPhHQ7HD\\">\\n            <link rel=\\"shortcut icon\\" href=\\"favicon.ico\\">\\n          <link rel=\\"alternate\\" type=\\"application/rss+xml\\" title=\\"RSS\\" href=\\"rss\\">\\n        <title>Hacker News</title></head>`

Notice the extra \ \ in the second case. These might be escape characters or something, but they're messing with the LinkExtractor which uses the response.text and is resulting in broken links. Again, this happens only when I'm returning an array of html responses. 
What am I missing here?

**Comment by zbassil** [comment]
@rohitkoganti I have the same issue. I see you closed the ticket. Were you able to figure it out?
