### ISSUE TITLE
Private mode not keeping user signed

### ISSUE THREAD

**Issue by JackSeaton** [scrapinghub/splash#794]
I'm trying to sign into a website on an initial visit, then check a `Remember Me` button. This way on future visits some time can be saved by not having to sign in again.

I've started docker with `--disable-private-mode` and have `splash.private_mode_enabled = false` set at the top of the `main` function, however I'm still required to sign in on subsequent visits to the website.

I also saw on https://splash.readthedocs.io/en/stable/faq.html#how-do-i-disable-private-mode:

_Note that if you disable private mode then browsing data may persist between requests (cookies are not affected though)._

I'm not sure if I have to set a cookie that's not persisting between visits?

Any suggestions on how to get around this would be much appreciated. Thanks

**Comment by waydegg** [comment]
Did you ever figure this out? I'm running into a similar situation and was wondering if you had a solution :)

**Comment by JackSeaton** [comment]
@waydegg IIRC I pulled the cookies out using [`get_cookies()`](https://splash.readthedocs.io/en/stable/scripting-ref.html#splash-get-cookies) after a sign in, stored them in a file (could also do a DB if you liked). 
I would then take those same cookies on next startup and inject them by looping the list of cookies and using [`add_cookie()`](https://splash.readthedocs.io/en/stable/scripting-ref.html#splash-add-cookie)

However, not long after I asked the question I ended up switching to [Puppeteer](https://github.com/puppeteer/puppeteer) and have had much better success using that over Splash.

Hopefully that helps
