### ISSUE TITLE
PNG render displays overly large footer

### ISSUE THREAD

**Issue by darkrho** [scrapinghub/splash#80]
I'm using latest revision and rendering this pages shows a difference in the footer layout being overly large:
* http://localhost:8050/render.png?url=http://www.tfsadvisors.com/blog/irs-and-treasury-department-provide-guidance&viewport=full&wait=10
* http://localhost:8050/render.png?url=http://www.tfsadvisors.com/resources/articles-by-dale/managing-risk-dont-be-caught-insurance-poor&viewport=full&wait=10

![Comparison](http://i.imgur.com/XMzx6tU.png)

Is there a workaround to avoid this behavior?

**Comment by kmike** [comment]
This is fixed in master branch. It took us less than a year!
