### ISSUE TITLE
Not calling custom downloader redirect middleware

### ISSUE THREAD

**Issue by Gb-forks** [scrapinghub/splash#810]
I had an existing Scrapy project which had a custom redirect middleware like this:

```
DOWNLOADER_MIDDLEWARES = {
    'scrapy.downloadermiddlewares.redirect.RedirectMiddleware': None,
    'my_scraper.middlewares.CustomRedirectMiddleware': 600,
}
```

I modified the project to use splash as described in [this](https://www.youtube.com/watch?v=VvFC93vAB7U) video.  When I  run the crawl, the custom redirect  middleware is not called.

**Comment by realslimshanky** [comment]
@Gb-forks can you please share the code to your middleware as well?

**Comment by kmike** [comment]
This issue belongs to scrapy-splash, but I'm not sure this can be fixed, as Splash doesn't have any access to Scrapy's downloader middlewares, and it can be impossible to support them because of implementation differences.
