### ISSUE TITLE
ConnectionError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',))

### ISSUE THREAD

**Issue by Sanjeetkumar163** [scrapinghub/splash#820]
ConnectionError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',))

I am using python-3.6.5 and Django-2.0.0, getting above error most of the time, please help me out. 
Below is the python script that I am using to get content from URL.

**Comment by Julienh** [comment]
Same problem since few weeks !

**Comment by Gallaecio** [comment]
Please, use [StackOverflow](https://stackoverflow.com/tags/splash-js-render) to ask this type of questions.
