### ISSUE TITLE
Question - Is there any alternative way to call the Splash instead of using HTTP API ?

### ISSUE THREAD

**Issue by Mideen** [scrapinghub/splash#838]
Hi,
    Sorry for this silly Question ...
      With phantomjs, We are using selenium to submit the URL to the browser(without making HTTP call to the browser). Is there any similar way to submit the URL to the splash instance without making HTTP request?

**Comment by JavierRuano** [comment]
Here, there is a comparative with Phantom 
https://github.com/scrapinghub/splash/blob/master/docs/scripting-tutorial.rst#where-are-my-callbacks
I am newbie with splash too.

**Comment by lopuhin** [comment]
@Mideen AFAIK there is no official way to call splash directly bypassing the HTTP API, although it should be possible to do so by writing some code. But that's definitely going to be more difficult than calling it via HTTP API.

**Comment by Mideen** [comment]
Thank you @lopuhin

**Comment by Mideen** [comment]
Shall I know which companies are using their own hosted scrapinghub-splash/Aquarium ?

**Comment by lopuhin** [comment]
> Shall I know which companies are using their own hosted scrapinghub-splash/Aquarium ?

@Mideen I know of some companies using Aquarium, and I know that scrpainghub provides hosted splash, but probably I didn't quite get your question, what did you mean to ask?

**Comment by Mideen** [comment]
Sorry ..!  My question is that whether the companies are using their own hosted Aquarium instead of using Scrapinghub's hosted splash?

**Comment by lopuhin** [comment]
@Mideen I think yes, I also know that some switched to using the SH hosted splash. From my point of view (which can be quite biased), Aquarium works good if you need to do a large volume of crawling in some limited amount of time (e.g. weeks), and if something fails it's not a huge issue (also I recommend using latest kernel and docker versions for it). On the other hand, if you need the rendering service which is always available, then Aquarium will need some modest amount of support (I remember having several incident per year, which needed rebooting the service/docker/whole server).

**Comment by Mideen** [comment]
Thank you for your instant reply and valuable suggestions.  We are trying to use own hosted Aquarium for web crawling. We will take your suggestions while implementing.
