### ISSUE TITLE
what it the last stable docker image?

### ISSUE THREAD

**Issue by davesmits** [scrapinghub/splash#839]
we try to use splash but not really sure what version we should use?

https://hub.docker.com/r/scrapinghub/splash/tags/

3.2 seems the last one but beeing 9 months old while master been updated two weeks ago. What is the recommended one to use?

**Comment by lucywang000** [comment]
You can read the CHANGES file to find the lastest release, for example the Splash 3.3 is released recently. Then use that tag in your work.
