### ISSUE TITLE
Docker/Splash on RPI3 - 207: exec user process caused "exec format error"

### ISSUE THREAD

**Issue by GMD99** [scrapinghub/splash#876]
I am trying to follow a tutorial on using Docker and Splash. I set up Docker and it appears to have been properly setup ("hello-world"). 

However when I try the command "sudo docker run -p 8050:8050 scrapinghub/splash" I get the following error : standard_init_linux.go:207: exec user process caused "exec format error"

This is on a RPI3B+ running Raspian Stretch

Any ideas on how I fix this?

**Comment by kmike** [comment]
No idea how to fix it unfortunately. It seems to be a problem with ARM processors. See https://github.com/scrapinghub/splash/issues/876 and https://github.com/scrapinghub/splash/issues/373. I'm closing it in favor of #876.
