### ISSUE TITLE
Best way of mantaining a logged in session

### ISSUE THREAD

**Issue by 0xfede7c8** [scrapinghub/splash#881]
Which is the recommended way to log in to a site and mantaining the session between requests if possible at all?
It's probably about sending captured cookies back to the other request, but I want to know if there is another kind of mechanism. 

Thanks

**Comment by 0xfede7c8** [comment]
Sorry, already in docs. Thanks.

**Comment by mwbelt** [comment]
@0xfede7c8 , where did you find it in the docs?  I came here for just this reason.

**Comment by 0xfede7c8** [comment]
Don't remember where exactly.
Though I found this into scrapy-splash plugin docs which is useful:

https://github.com/scrapy-plugins/scrapy-splash#session-handling

This handles the cookies for you.
