### ISSUE TITLE
AttributeError: module 'tornado.web' has no attribute 'asynchronous'

### ISSUE THREAD

**Issue by rafikahmed** [scrapinghub/splash#887]
Hello there, 
There is a dependency problem in the last splash-jupyter commit.
<img width="673" alt="nbconvert" src="https://user-images.githubusercontent.com/41229637/54269945-9f297180-457e-11e9-9754-3c84686fbb14.PNG">
<img width="960" alt="Capture" src="https://user-images.githubusercontent.com/41229637/54269957-a2246200-457e-11e9-8103-140d65d598d2.PNG">
Because of the update of nbconvert, tornado version 6 has been changed.
I think we should downgrade nbcovert to a version where tornado version 5 is used.
I'm gonna try with that and let you know.
Kind regards,
Ahmed.

**Comment by rafikahmed** [comment]
Hi again,
I managed to fix the issue: 
Simply you need to uninstall nbconvert and tornado 
```
pip uninstall tornado
pip uninstall nbconvert
```
After that re-install nbconvert==5.3.1 and tornado version 4.2
```
pip install nbconvert==5.3.1
pip install tornado==4.2
```
Next you need to re-build the image after you exit.
`docker ps -a `
copy the container ID and rebuild the image:
`docker commit <container_id> jupyter_splash:test `
Now to launch it you simply need to use the following command:
`docker run --entrypoint="../start-notebook.sh" -p 8888:8888 -it jupyter_splash:test
`
Kind regards,
Ahmed.

**Comment by apremgeorge** [comment]
This is not a solution right... what if I should use tornado 6.0

**Comment by Teque5** [comment]
A much better solution for those running into this issue is to do `pip install --upgrade nbconvert`. This allows you to keep tornado6.

**Comment by apremgeorge** [comment]
Thanks @Teque5

**Comment by RaoTianlong** [comment]
@Teque5 thanks

**Comment by Ben-Epstein** [comment]
@Teque5  This solution does not work with nbconvert==5.6.0 and tornado==6.0.3

We should reopen this issue

**Comment by sclmaomao** [comment]
> A much better solution for those running into this issue is to do `pip install --upgrade nbconvert`. This allows you to keep tornado6.

That works for me! Thank you.

**Comment by saravanakkumar-rs** [comment]
i am using tornado 6.0.3 but i am still facing the issue

**Comment by linzhi** [comment]
I have the same question, i am using tornado 6.0.3 but, still facing the issue

**Comment by louis925** [comment]
Updating nbconvert to 5.6.1 with tornado 6.0.3 works for me.

**Comment by Rajwinders13** [comment]
I have tornado 6.1 and nbconvert 6.0.7, upgrading does not works for me either.

**Comment by ChristianPao** [comment]
tornado 6.1 + nbconvert 5.6.1 = working for me.

**Comment by kshitijKamlakar** [comment]
> A much better solution for those running into this issue is to do `pip install --upgrade nbconvert`. This allows you to keep tornado6.

Thanks
