### ISSUE TITLE
UUID file '/etc/machine-id' should contain a hex string of length 32, not length 0, with no other text

### ISSUE THREAD

**Issue by BinhMinhs10** [scrapinghub/splash#894]
i was typed: dbus-uuidgen >/etc/machine-id  but it still NOT work

i readed post but not work:
https://stackoverflow.com/questions/48312044/splash-issues-d-bus-qsslsocket-libpng
https://github.com/scrapinghub/splash/issues/491
=====================
Splash version: 3.3.1

**Comment by BinhMinhs10** [comment]
i was fixed problem instead of type: 
$ sudo docker run -p 8050:8050 scrapinghub/splash
you should type like below
$ sudo docker run --net="host" -p 8050:8050 -p 5023:5023 scrapinghub/splash -v4

**Comment by Gallaecio** [comment]
The Splash 3.1 documentation already indicates the need to open that additional port: https://splash.readthedocs.io/en/3.1/install.html

`--net="host"` should not be needed.
