### ISSUE TITLE
Lua scripts in scrapy

### ISSUE THREAD

**Issue by kc1** [scrapinghub/splash#916]
I'm working with scrapy 1.6 and splash 3.2 I have:

    import scrapy
    import random
    from scrapy_splash import SplashRequest
    from scrapy.utils.response import open_in_browser
    from scrapy.linkextractors import LinkExtractor

    USER_AGENT = 'Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:48.0) Gecko/20100101 Firefox/48.0'

    class MySpider(scrapy.Spider):

        start_urls = ["http://yahoo.com"]
        name = 'mytest'

        def start_requests(self):
            for url in self.start_urls:
                yield SplashRequest(url, self.parse, endpoint='render.html', args={'wait': 2.5},headers={'User-Agent': USER_AGENT,'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8'})

        def parse(self, response):
            # response.body is a result of render.html call; it
            # contains HTML processed by a browser.
            # from scrapy.http.response.html import HtmlResponse
            # ht = HtmlResponse('jj')
            # ht.body.replace =response
            open_in_browser(response)
            return None

I'm reading through https://blog.scrapinghub.com/2015/03/02/handling-javascript-in-scrapy-with-splash and in this they give the example of:

    function main(splash)
    assert(splash:go(splash.args.url))
    splash:wait(0.5)
    local title = splash:evaljs("document.title")
    return {title=title}
    end

Obviously I can't put Lua in my python script. Where do I put it and how do I access it to pass to my splash request?

Its also here:  

https://stackoverflow.com/questions/56756925/lua-scripts-in-scrapy

**Comment by Gallaecio** [comment]
Please, see https://splash.readthedocs.io/en/stable/scripting-tutorial.html
