### ISSUE TITLE
There is no provision.sh anymore

### ISSUE THREAD

**Issue by NightMachinary** [scrapinghub/splash#925]
Please restore manual install. docker is too heavy for cheap VPSes which are great for personal use.

**Comment by kmike** [comment]
Hey @NightMachinary! Individual commands are in https://github.com/scrapinghub/splash/tree/master/dockerfiles/splash now, and their order is described at https://github.com/scrapinghub/splash/blob/master/Dockerfile. `provision.sh` file shouldn't be too hard to write (it may call these scripts), but I don't want to maintain it, as it is not needed for the "default" install method, we're not using it, and it'd be hard to test it on CI (current Docker setup is tested).

Is it really that heavy to use Docker? With Docker you'll be saving resources required e.g. to build dependencies, and Splash may start building webkit at some point; I was thinking that using Docker can be a more lightweight, not more heavyweight way to install Splash - you need to download less data, it uses less CPU and RAM resources to build the whole thing, as you don't need to run the build on VPS.

I'm closing this ticket, but can merge a pull request with provision.sh file, as soon as it is stated that this file is a starting point, and may not be kept in sync.

Are you concerned about runtime Docker overhead?

**Comment by NightMachinary** [comment]
After using it via Docker, I’m actually quite happy with it. Thanks!

**Comment by yaizudamashii** [comment]
I would like provision.sh.  I can run splash in Docker, it is a great tool, thank you very much.  however, I need to use it as a process (or at least run the server within Docker separately) because I want to run the headless browser while running vpn.  In order to configure and start vpn, the Docker box must be able to call splash server.
Alternatively, I can modify the splash Docker container and start another web server in the same container to configure and run vpn.  Which of these approaches would you suggest @kmike ?

**Comment by yaizudamashii** [comment]
If you could at least modify the install instructions in 
https://splash.readthedocs.io/en/stable/install.html
it will save a lot of confusion, I think.

**Comment by kmike** [comment]
Thanks for the feedback @yaizudamashii! 

Instructions are modified here: https://splash.readthedocs.io/en/latest/install.html; for current stable branch it should be still possible to use provision.sh file from https://github.com/scrapinghub/splash/tree/3.3.1/dockerfiles/splash.

Regarding vpn + Splash, I'm not sure I understood the problem you're having - can you please clarify it? You can run many Docker containers on the same server. 

If several dockerized services needs to be started, something like docker-compose can help, e.g. this is how https://github.com/TeamHG-Memex/aquarium adds Tor support to Splash.

**Comment by yaizudamashii** [comment]
Thank you for the pointers @kmike so it seems I will set up two containers, and the main container will call the splash container which will request the main container's endpoint, at which point the main container will act as a proxy after starting vpn and then relay the web response that comes back to the splash container for rendering, which after rendering sends the rendered response to the main container.
