### ISSUE TITLE
provision.sh doesn't work

### ISSUE THREAD

**Issue by Lablado** [scrapinghub/splash#934]
I need to deploy splash in an environment without docker, but I have encountered a problem according to the tutorial. It will report an error when executing the installation script. How can I solve it?
`Executing command: prepare_install
sed: -i: No such file or directory
sed: /etc/apt/sources.list: No such file or directory
Command failed (exitcode: 1), exiting...`

**Comment by Gallaecio** [comment]
The [manual installation instructions](https://splash.readthedocs.io/en/stable/install.html#ubuntu-16-04-manual-way) are for **Ubuntu 16.04**.

If you are using a different distribution, you have these options:
* Install Docker.
* Switch to Ubuntu 16.04.
* Figure out how to reproduce what the manual installation scripts do in your distribution.

I strongly suggest option 1 :slightly_smiling_face:
