### ISSUE TITLE
Splash and the window.onload event

### ISSUE THREAD

**Issue by oliverw** [scrapinghub/splash#938]
I'm trying to wait for the page to be fully loaded using:

```lua
function main(splash)
    splash:go("http://example.com")
    
    local result, error = splash:wait_for_resume([[
        function main(splash) {
            window.onload = (e)=> {
                console.log('page is fully loaded');

                splash.set("foo", "bar");
                splash.resume("ok");
            };
        }
    ]])

    return result
end
```

Unfortunately, I always receive an error in the console:

`"error": {"info": null, "error": 0, "description": "Raised when trying to create a Failure from the current interpreter\n    exception state and there is no current exception state.", "type": "NoCurrentExceptionError"}`

Is waiting for this event not supported in Splash?

**Comment by kmike** [comment]
If I'm not mistaken, splash:go waits for onload by default

**Comment by kmike** [comment]
the exact error you're getting doesn't look good (looks like a bug), but I expect code in the example to never return, as window.onload shouldn't be called

**Comment by kmike** [comment]
also, I'm not sure arrow functions are supported

**Comment by oliverw** [comment]
@kmike `splash:go()` appears to wait for `DOMContentLoaded`, otherwise custom Javascript code couldn't run before the page is rendered as stated by the docs.

ES2015 arrow functions work fine btw :)
