### ISSUE TITLE
Order of returned variables causes LUA_INIT_ERROR

### ISSUE THREAD

**Issue by liuyigh** [scrapinghub/splash#946]
I would like to return 6 variables in a lua script like this:

`return {a, b, c, d, gapUp, gapDown}`
It will work.

If I change it to
`return {gapUp, gapDown, a, b, c, d}`

The script will not run and I get this error in `response.content` instantly:

`{"error": 400, "description": "Error happened while executing Lua script", "info": {"message": "[string \\"...\\"]:46: \'}\' expected near char(239)", "error": "\'}\' expected near char(239)", "line_number": 46, "type": "LUA_INIT_ERROR", "source": "[string \\"...\\"]"}, "type": "ScriptError"}'`

Can someone explain why the order matters? Thanks!

**Comment by kmike** [comment]
hey! Could you please provide a more complete example?

**Comment by liuyigh** [comment]
I am very sorry that I could not reproduce this error anymore. I will close the ticket.
