### ISSUE TITLE
Docker userns remap breaks builds

### ISSUE THREAD

**Issue by AngryUbuntuNerd** [scrapinghub/splash#948]
When building a Dockerfile with Scrapy base image in a BitBucket pipeline, it now breaks on the first build step (FROM scrapinghub/splash) with this error:

> failed to register layer: Error processing tar file(exit status 1): Container ID 834600147 cannot be mapped to a host ID

According to the [BitBucket help page](https://community.atlassian.com/t5/Bitbucket-articles/Changes-to-make-your-containers-more-secure-on-Bitbucket/ba-p/998464) this issue is due to the fact that they have enabled [userns remapping](https://docs.docker.com/engine/security/userns-remap/) for security reasons. They also say that some images will not handle this properly, and Scrapy is seemingly one of them.

Until this is fixed, the Scrapy docker image can essentially not be used in BitBucket pipelines, or anywhere that activates this feature.

**Comment by kmike** [comment]
Do you know what caused this error in Splash Docker image? Is it the use of USER directive?
FTR, we had to use non-default (non-root) user in Splash because Chromium doesn't work under root.

**Comment by AngryUbuntuNerd** [comment]
It seems this issue is now fixed, a rerun of the same pipeline works.
