### ISSUE TITLE
Cannot find `provision.sh` in `splash/dockerfiles/splash` directory

### ISSUE THREAD

**Issue by develagasca** [scrapinghub/splash#952]
I'm trying to install Splash the manual way using [this guide](https://splash.readthedocs.io/en/stable/install.html#ubuntu-16-04-manual-way) but `provision.sh` doesn't exist.

```shell
vagrant@ubuntu-xenial:~$ git clone https://github.com/scrapinghub/splash
Cloning into 'splash'...
remote: Enumerating objects: 206, done.
remote: Counting objects: 100% (206/206), done.
remote: Compressing objects: 100% (147/147), done.
remote: Total 11845 (delta 99), reused 127 (delta 58), pack-reused 11639
Receiving objects: 100% (11845/11845), 3.58 MiB | 728.00 KiB/s, done.
Resolving deltas: 100% (8706/8706), done.
Checking connectivity... done.
```
Tried to find it…
```shell
vagrant@ubuntu-xenial:~/splash$ find . -type f -name "provision.sh"
vagrant@ubuntu-xenial:~/splash$ 
```
…but it's not there.

Here's a `git log` of the commit at the time I tried this:

```shell
vagrant@ubuntu-xenial:~/splash$ git log --all --decorate --graph --oneline
* a1f4488 (HEAD -> master, tag: 3.4b1, origin/master, origin/HEAD) splash-jupyter: update inspections file
* 6105d79 disable scrollbars for chromium
*   9fda128 Merge pull request #939 from scrapinghub/http2
|\ 
< …truncated output… >
```

So either the documentation is out of date or `provision.sh` has gone missing.

**Comment by kmike** [comment]
Hey @develagasca! This is a documentation issue: docs are for Splash stable (3.3.1), but they ask to clone& checkout splash from github master; code on github is already for the next relese, where provision.sh is removed. 

You can get provision.sh file by checking out 3.3.1 tag (https://github.com/scrapinghub/splash/tree/3.3.1). But keep in mind that this file will be gone in the next release.
