### ISSUE TITLE
Python3.7 render.html don't work

### ISSUE THREAD

**Issue by UnknowName** [scrapinghub/splash#963]
when render a javascript html.it also return origin html. I don't know why.But use like Chrome access the render URL. it worked.

**Comment by bfkkkd** [comment]
I meets the same issue, looks like some js scripts did not rendered

**Comment by UnknowName** [comment]
I know how fix it. It's not bug.
example:
Your splash addr is  http://127.0.0.1:8095. And you will access the www.example.org by splash. 
You programe mush access  http://127.0.0.1:8095/render.html?url=www.example.org&wait=2&images=0
