### ISSUE TITLE
[Question] Why Splash can not able to fetch the page of Linkedin

### ISSUE THREAD

**Issue by Mideen** [scrapinghub/splash#968]
I have tried to get the page source of Linkedin. But I cannot able to fetch even for one URL. I got the response like "Failed loading page"

Few samples,
https://www.linkedin.com/company/amazon
https://www.linkedin.com/company/apple

Splash version: 3.4
OS: Ubuntu

**Comment by Gallaecio** [comment]
Please, ask questions in [StackOverflow](https://stackoverflow.com/search?tab=votes&q=%5bsplash-js-render%5d%20linkedin).

**Comment by Mideen** [comment]
For reference 
https://stackoverflow.com/questions/59064951/why-splash-headless-browser-can-not-able-to-fetch-the-page-of-linkedin
