### ISSUE TITLE
Proxy-authorization is not being sended on 'CONNECT' method

### ISSUE THREAD

**Issue by Urahara** [scrapinghub/splash#969]
I'm using [AnyProxy](https://anyproxy.io/en/) and i can't use proxy on https endpoints with Splash, the authorization headers are not sended on **CONNECT** method, so i received **407 Proxy Authentication Required** error.

The proxy works normaly on HTTP endpoints.

**Comment by Gallaecio** [comment]
How are you configuring your proxy? Are you using [proxy profiles](https://splash.readthedocs.io/en/stable/api.html#proxy-profiles)?

**Comment by Urahara** [comment]
@Gallaecio Yes! I'm running splash using docker:

```sh
docker run -v ~/proxy-profiles:/etc/splash/proxy-profiles --network=host -it -p 8050:8050 scrapinghub/splash
```

**default.ini:**
```cfg
[proxy]
host=127.0.0.1
port=8001
username=test
password=
type=HTTP
```

### Logs from AnyProxy

- HTTPS (https://httpbin.org/get)
```
[AnyProxy Log][2019-11-29 11:43:04]: received https CONNECT request httpbin.org
{
  'proxy-connection': 'keep-alive',
  host: 'httpbin.org',
  'user-agent': 'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/602.1 (KHTML, like Gecko) splash Version/9.0 Safari/602.1'
}
```
- HTTP (http://httpbin.org/get):
```
[AnyProxy Log][2019-11-29 11:49:21]: received request to: GET httpbin.org/get
{
  'User-Agent': 'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/602.1 (KHTML, like Gecko) splash Version/9.0 Safari/602.1',
  Accept: 'text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8',
  'Proxy-Authorization': 'Basic dGVzdDo=',
  Connection: 'Keep-Alive',
  'Accept-Encoding': 'gzip, deflate',
  'Accept-Language': 'en,*',
  Host: 'httpbin.org'
}
```

**Comment by Urahara** [comment]
@Gallaecio Can you take a look at this? There's something i can do to make this work?

**Comment by Gallaecio** [comment]
I’m busy with other projects at the moment, and I’m not familiar enough with using Splash with proxies to suggest any workaround. If you think this may be a configuration issue on your side, I would suggest trying [asking in Stackoverflow](https://stackoverflow.com/questions/tagged/splash-js-render) or checking existing questions. Otherwise, we’ll have to wait until this is confirmed to be a bug (e.g. someone else reproducing the issue).

**Comment by Urahara** [comment]
It's seems that the Splash or Qt have a different flow from others apps like cURL.

Because the **CONNECT** method don't send **Proxy-Authorization** but all others methods like **GET/POST/etc** send this header, when all others apps do the opposite, sends **Proxy-Authorization** on **CONNECT** and not on other methods.

So i was able to solve this, dealing with this flow, now my application is working fine with proxies.
